### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#102]
Spigot username: Nexima (https://www.spigotmc.org/members/nexima.40441/)
ProQuest version: latest
spigot version: 1.12.2

Errors;
https://hastebin.com/keneneqife.css
https://hastebin.com/febuqucife.vbs

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=221386
