### ISSUE TITLE
Breeder quest bug

### ISSUE THREAD

**Issue by xDacon** [JCulley/ProQuests-Documentation#105]
https://www.spigotmc.org/members/dacon.6544/

- Using latest version
- Using latest Paper spigot 1.12.2

Log: https://hastebin.com/ewomucahag.md

This is my first breeder quest: https://hastebin.com/efosaqihiw.go
people are having issues not being able to complete it. Their progress bar goes up, but stays @ full and quest never completes

There's an error spammed about the breeder quest https://hastebin.com/orecihines.vbs

**Comment by xDacon** [comment]
Error is spammed even if I deleted the breeder quests https://hastebin.com/nopaqesino.vbs

I deleted because I believe it played a part in crashing my server frequently (only error spammed before the crash, which was entity related)

**Comment by xDacon** [comment]
/quests kick doesn't work either, says player does not exist or quest does not exist

**Comment by JCulley** [comment]
Paper Spigot is passing a null event so it is unfortunately something I cannot fix in reference to your error. The cancel command only works if the player is online and they have the specified quest added.

**Comment by xDacon** [comment]
Switched to latest spigot instead of paper, get same exact error
https://hastebin.com/veneqexevu.vbs

**Comment by JCulley** [comment]
https://hastebin.com/nopaqesino.vbs has no reference to ProQuests whatsoever, this https://hastebin.com/veneqexevu.vbs does. These are not the same errors and if they are you only provided me a snippet of the full error originally.

**Comment by xDacon** [comment]
Ok I guess they're not identical errors. 

They still both start off with 
[07:23:43 ERROR]: Could not pass event CreatureSpawnEvent to ProQuests v2.0.4
