### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by hipporunner** [JCulley/ProQuests-Documentation#107]
https://www.spigotmc.org/members/hipporunner.41806/
2.0.4
SPIGOT 1.8.8
https://pastebin.com/69tW8938

When ever players try and turn Items into the "Quest Keeper" on my server it gives the error of :
[17:02:32] [Server thread/INFO]: [ProQuests] ERROR: Attempted to get duplicate itemstack for a null object

Sorry for not following the format last time.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=223522
