### ISSUE TITLE
Break quests not finishing

### ISSUE THREAD

**Issue by Hitosherizu** [JCulley/ProQuests-Documentation#109]
I've multiple break quests set up to finish after breaking X amount of blocks and reward the player with economy, and message them saying it's been completed. After complaints that one of the quests was not finishing (Netherrack/Nether Quartz), I tested it myself. The required materials was 250 Netherrack and 75 Nether Quartz (325 blocks total), I've destroyed well over 250 netherrack and nether quartz. (Mined nearly 300 of each in nether and then did 3 waves of 150 of each with worldedit). No errors in console, all quests are loaded.

**Comment by JCulley** [comment]
Does not follow the error guidelines
