### ISSUE TITLE
Break Quest

### ISSUE THREAD

**Issue by Hitosherizu** [JCulley/ProQuests-Documentation#110]
Spigot accounts: https://www.spigotmc.org/members/hitosherizu.388450/ (I am a plugin dev who does work on servers, I do not own the plugin but the owner of the server does.)
https://www.spigotmc.org/members/zsound.521445/ (owns the plugin and server it is used on)
Spigot Version: 1.12.2
Plugin Version: Latest
Log: Not needed as no errors are thrown in console

I've multiple break quests set up to finish after breaking X amount of blocks and reward the player with economy, and message them saying it's been completed. After complaints that one of the quests was not finishing (Netherrack/Nether Quartz), I tested it myself. The required materials was 250 Netherrack and 75 Nether Quartz (325 blocks total), I've destroyed well over 250 netherrack and nether quartz. (Mined nearly 300 of each in nether and then did 3 waves of 150 of each with worldedit). No errors in console, all quests are loaded.

**Comment by JCulley** [comment]
Closed for 3 reasons:

1. You did not provide the log file, I could care less if you think I need it or not.

2. You’re not a buyer

3. You chose not to provide me any information regarding the specific quest you are referring to as it is more than likely a configuration issue.

**Comment by Hitosherizu** [comment]
There is no log file to provide. If this is a config issue (Which it isn't as I've used this before and have had no issues.) then why would you need the log file

I have proof of purchase of the plugin for the server which I am the sole person working on plugins.

I have MULTIPLE QUESTS meaning MORE THAN ONE, meaning there isn't a SPECIFIC quest, all of them with the type "Break quest" are doing this. Rather than be helpful and explain either one way or another, We will be refunding the plugin due to you being a massive cunt and it not working as explained in any documentation stages. Enjoy your day.
