### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by hipporunner** [JCulley/ProQuests-Documentation#112]
https://www.spigotmc.org/members/hipporunner.41806/
2.0.4.1
SPIGOT 1.8.8
https://pastebin.com/1XSe4Q67

This happens when ever they spam right click or left click on the NPC that opens the quest menu.

**Comment by JCulley** [comment]
Hardly enough detail, but regardless the error seems to be the fact that you have players with active quests which were saved to their player object however the quest itself may have been unable to load due to a configuration or something of the sort resulting in a null quest object.
