### ISSUE TITLE
Legacy version?

### ISSUE THREAD

**Issue by SwishMasters** [JCulley/ProQuests-Documentation#114]
Quick question is there a legacy version of ProQuest, Packages, and Tournaments that supports 1.7 because that is what I need.

**Comment by JCulley** [comment]
Can you please provide your spigot account link.

**Comment by JCulley** [comment]
Nevermind, confirmed you are the one who opened 3 claims against me. You will be banned from the GitHub page until the claims are closed and PayPal releases the funds for all 3 transactions.
