### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by darkblazeman** [JCulley/ProQuests-Documentation#118]
Hi, this is not a suggestion for the plugin, however I'm wanting to make a suggestion that the wiki's permissions of the plugin are updated. For example what permission you need to give a player for them to be able to start a quest.

**Comment by darkblazeman** [comment]
![2018-05-17_22 07 39](https://user-images.githubusercontent.com/39388141/40204024-0452ba2c-5a1f-11e8-8975-e97b01e3d298.png)

**Comment by JCulley** [comment]
> /proquests start {identifier} - proquests.quest.start.{identifier}

Straight from the commands/permissions page.
