### ISSUE TITLE
About ProQuest Help!

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#120]
Hello,
My quest this;
https://hastebin.com/akenigasiw.bash

Everything okey.
I break 384 stone but quest not finished and not giving rewards ?
What is wrong ?

ProQuest version: latest
Spigot version: 1.12.2

Note: this problem was no in 1.9.4 spigot version.

**Comment by JCulley** [comment]
Closing this issue as it does not follow the error guidelines. Feel free to reopen with the proper format and required information. https://github.com/JCulley/ProQuests-Documentaion/wiki/Error-Guidelines

**Comment by NeximaOzi** [comment]
Hello,
Spigot name: Nexima
Spigot Account Link: https://www.spigotmc.org/members/nexima.40441/
ProQuest version: Latest
Spigot version: 1.12.2
Log: https://hastebin.com/kalaqoyepo.md

My quest this;
https://hastebin.com/akenigasiw.bash

Everything okey.
I break 384 stone but quest not finished and not giving rewards ?
What is wrong ?

Note: this problem was no in 1.9.4 spigot version.
