### ISSUE TITLE
I can't /quest reset all

### ISSUE THREAD

**Issue by dewobedil** [JCulley/ProQuests-Documentation#121]
**My Spigot account:** https://www.spigotmc.org/members/dewobedil.64311/
**Plugin version:** version 2.0.4.1
**Spigot version:** CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Server logs:** https://pastebin.com/RRWAi2rD

**Information:** So this command doesnt seems work in console and ingame either. When i execute quest reset number and it does not do anything. No information or error about the command

![Preview](https://i.imgur.com/GQNjHa0.png)

Please for the help. Thank you.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=226243
