### ISSUE TITLE
About BREAK_QUEST and KILL_QUEST

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#122]
Hello,
Spigot name: Nexima
Spigot Account Link: https://www.spigotmc.org/members/nexima.40441/
ProQuest version: Latest
Spigot version: 1.12.2
Log: https://hastebin.com/kalaqoyepo.md

Break_Quest this;
https://hastebin.com/akenigasiw.bash

Kill_Quest this;
https://hastebin.com/uhosukokaf.bash

Everything okey and my other quests no problem. But this two quest have a problem.
I break 384 stone but quest not finished and not giving rewards ? Also same for Kill_Quest.
What is wrong ?

Note: this problem was no in 1.9.4 spigot version.

**Comment by JCulley** [comment]
There was no issue discovered with the "KILL_QUEST" type however v2.0.4.3 addresses the issue with the "BREAK_QUEST" type while using required materials.

https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=226268

**Comment by NeximaOzi** [comment]
Thanks for help :)
