### ISSUE TITLE
QuestUpdateEvent exception

### ISSUE THREAD

**Issue by Tyloonie** [JCulley/ProQuests-Documentation#123]
Spigot Account: https://www.spigotmc.org/members/tyloonie.130061/

I'm using the latest version of ProQuests, Spigot version CraftBukkit version git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT).

Hello, I have been getting this error recently. Since it has not always been there, I am well aware that I am the cause of the issue. However I have no clue what I have done wrong or/if I discovered a bug in the plugin.

As far as I can tell, it has something to do with Buycraft. Someone just bought something on my server, so this might be the cause of the error?

https://hastebin.com/alukeheqod.bash

**Comment by JCulley** [comment]
1) Please provide your log file as stated in the guidelines

2) Based on the small snippet you provided you are not using the latest version however it’s probably irrelevant as there have been no changes to buycraft integration in months

3) Do you use Buycraft quests? It’s hard for me to completely understand and issue if you do not provide me with complete details regarding your specific setup. If you do have Buycraft quests please provide the actual configurations.

Thanks.

**Comment by Tyloonie** [comment]
1. Here is more of the log file. As you can see, the error persists to happen once every X seconds - every time Buycraft quests are updating: https://hastebin.com/ifamifunud.sql

2: I'm using ProQuests 2.0.4.1, so yes I'm 2 versions behind.

3. Yes, as I have stated I'm using a Buycraft quests which checks for people spending $10. I have attached the quest file.

[buycraft_1.zip](https://github.com/JCulley/ProQuests-Documentation/files/2023966/buycraft_1.zip)

**Comment by JCulley** [comment]
Please provide a link to the entire log file, not just parts of it please.

**Comment by Tyloonie** [comment]
Entire log file: https://hastebin.com/uzojawuqug.md
Buycraft quest file: https://hastebin.com/iwimuleyak.bash

**Comment by JCulley** [comment]
Thanks, I'll look into it when I get a chance

**Comment by Tyloonie** [comment]
Thank you. Hope you can get it fixed.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=226442
