### ISSUE TITLE
ProQuest About Repeat Delay

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#126]
Hello,
Spigot name: Nexima
Spigot Account Link: https://www.spigotmc.org/members/nexima.40441/
ProQuest version: Latest
Spigot version: 1.12.2
New Log: https://hastebin.com/oxucefoban.md

I have big bungeecord server. And i use this plugin in my faction server.
I set "repeat_delay: 86400" (1 day) for all quests.
For example a player get a quest and finish this quest when going to main lobby. Again join to faction server and again can get same quest. So don't wait 1 day.
What can i do for this ?

You was say me before ticket;
"Due to the fact I have no knowledge of your setup or how you have configured your quests theres not much I can grasp from this which would help me in any way. If you're using MySQL and have all of your servers connected to the same database then you'll probably need to increase your database delay. Otherwise your log is useless as you have only provided a startup and as far as I can see has nothing related to this issue seems how you didn't give me the log where this actually happened i'm assuming. I'm going to go ahead and close this issue until you can provide sufficient details/information."

I was no use mysql. Now i put latest version and i'm now using mysql.
But when server opened im getting this error;
https://hastebin.com/juxeputeve.vbs

also when i try "/proquests reload" im getting this warn;
https://hastebin.com/nusivakewo.sql

**Comment by JCulley** [comment]
Please try to work out your own it problems through trial and error before resorting to opening an issue. You obviously used the server /reload command or are using a plugin to load/unload plugins dynamically which will not be supported. Closing this issue as it’s irrelevant to ProQuests and rather how you choose to manage your operations which as I may add should not be done this way.
