### ISSUE TITLE
About repeat delay

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#127]
Hello again..
Spigot name: Nexima
Spigot Account Link: https://www.spigotmc.org/members/nexima.40441/
ProQuest version: Latest
Spigot version: 1.12.2
Log: https://hastebin.com/oholikepuj.md
A Quest: https://hastebin.com/kilusapaci.bash
Config: https://hastebin.com/rogohacoje.php

I set "repeat_delay: 86400" (1 day) for all quests.
For example a player get a quest and finish this quest when going to main lobby. Again join to faction server and again can get same quest. So don't wait 1 day.
What can i do for this ?

and i will try connect to mysql maybe if i use mysql will be fixed this problem with mysql idk i just try.
But when i try connect to mysql im getting this error;
https://hastebin.com/ujisoharep.vbs

Note: my other plugins no this mysql erro. All plugins work.

Please help for this my issues. I can't solved this problems. And i don't know what can i do.

**Comment by JCulley** [comment]
This is due to your MySQL configuration limiting your column size has nothing to do with ProQuests. Please stop posting useless issues or you will be banned from the GitHub
