### ISSUE TITLE
About Repeat Delay !

### ISSUE THREAD

**Issue by NeximaOzi** [JCulley/ProQuests-Documentation#129]
Spigot name: Nexima
Spigot Account Link: https://www.spigotmc.org/members/nexima.40441/
ProQuest version: Latest
Spigot version: 1.12.2
A Quest: https://hastebin.com/kilusapaci.bash
Config: https://hastebin.com/rogohacoje.php
Here is full daily Log;
https://drive.google.com/file/d/1v62xSh29kMJu9AsRYDl3WYXkltYGuQoo/view?usp=sharing
I can't put hastebin because log too long.

I set "repeat_delay: 86400" (1 day) for all quests.
For example a player get a quest and finish this quest when going to main lobby. Again join to faction server and again can get same quest. So don't wait 1 day.
I don't use mysql so what can i do for this ?

Repeat delay options not working for bungee servers. Because when players going to main lobby and joined again server, again can get same quest not waiting time..

NOTE= if player in top10 for player points then can not get again same quest so must wait repeat delay time. But if player not in top10 then always can get same quest go lobby and join again server and can do again same ques. So no wait repeat delay time.

**Comment by JCulley** [comment]
The log is not text based, I will not download any files for my own security.

**Comment by JCulley** [comment]
You continue to ignore my comments and have opened far too many issues with the exact same information provided. Closed, not to be reopened.
