### ISSUE TITLE
Fails to load up

### ISSUE THREAD

**Issue by HyperGaming18** [JCulley/ProQuests-Documentation#131]
Username Spigot: HyperGaming18

Server Log: https://hastebin.com/tewamovama.md

Error: https://hastebin.com/diluqoxafe.vbs

If you need anything else let me know.

**Comment by JCulley** [comment]
Yes I need you to follow the guidelines, next time thanks. https://github.com/JCulley/ProQuests-Documentation/wiki/Error-Guidelines

The error is related to the fact you are using a version of AutoRank which ProQuests currently does not support, I’m not sure what version, in addition you aren’t using the latest ProQuests so support will not be provided until you update.

**Comment by HyperGaming18** [comment]
Welp. I dm'd you this error a while back and it's still not resolved because you told me to bring it to github. I just got all the latest stuff for proquests and autorank and it's still not working.
