### ISSUE TITLE
Breaks with 2 main plugins

### ISSUE THREAD

**Issue by HyperGaming18** [JCulley/ProQuests-Documentation#132]
Pretty sure i followed your requirements correctly.

Spigot Username: HyperGaming18
Link to spigot account: https://www.spigotmc.org/members/hypergaming18.83251/
Spigot Version: 1.12.2

Link to server log: https://hastebin.com/umoqekumap.md

Link to Error: https://hastebin.com/kobidopaji.vbs

( Autorank has issues with this and im using Version 4.2.3 of autorank )

**Comment by HyperGaming18** [comment]
2 days later and no reply, pretty sure this isn't being worked on :(

**Comment by JCulley** [comment]
If the issue is still open then it is still pending/in progress. I currently do not have time to investigate and post any updates however will do so when I get a chance.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=228231
