### ISSUE TITLE
DELIVERY_QUEST Issue

### ISSUE THREAD

**Issue by hipporunner** [JCulley/ProQuests-Documentation#134]
https://www.spigotmc.org/members/hipporunner.41806/
2.0.4.4
SPIGOT 1.8.8
https://pastebin.com/PUAK31y4

Okay here is a video explaining it in voice but, When you have 2 or more Delivery Quests accepted and a player tries to turn them into a npc it does not work. There is no error log but a video to show the error.

Video : https://youtu.be/39bJG2bZmsg

**Comment by hipporunner** [comment]
I think I have a bit more info I am using an Outdated version of citizens because I run in 1.8 and you support the new citizens for 1.10-1.12 only. Is there any way to get a copy with the old citizens?

**Comment by JCulley** [comment]
Even with the video I have no clue what you are talking about, it was so low resolution I couldn't even read any of the text. Regardless as I already stated this doesn't look like an "error" at all and is rather a specific way you want to set something up meaning you need to modify your configuration files.

**Comment by hipporunner** [comment]
Okay Delivery Quests, the quests you give items to mobs/npcs I use an outdated version of citizens so my quests break after you accept 3 or more of them for having you give the npc/mobs the item you are trying to give them. It will not allow you to turn them into the mobs/npc it give no error and it does not allow me to fix them I created 3 new quests for that video only using your gui and I could not even select the npc so I had a player stand in the npc so I could set the point of turn in.

**Comment by JCulley** [comment]
Citizens would not affect the turning in of quests whatsoever. Delivery quests are not to be run parallel and are to be run one at a time (get items, come back, get another quest) hence the quest NPC type of you are trying to run multiple in sequence I don’t understand why you wouldn’t just use obtain quests with the NPC having an associated menu. I will not provide advice on configuration in the future that is your responsibility, and making up some assumption that citizens has anything to do with it makes no sense whatsoever. If it was the case older plugin references will not be supported.
