### ISSUE TITLE
Doesn't support placeholderapi v2.8.7/v2.8.2

### ISSUE THREAD

**Issue by Mayomi** [JCulley/ProQuests-Documentation#135]
Profile Link:
https://www.spigotmc.org/members/soutou.53340/

Version:
ProQuests v2.0.4.5 via Spigot 1.12.2
PlaceholderAPI v2.8.7 / v2.8.2

Details: 
No response on v2.8.2 / v2.8.7 - Non PAPI-expansion
Got error on v2.8.2 - (https://pastebin.com/BAun28XE) - Via PAPI-expansion

**Comment by JCulley** [comment]
This is not an error whatsoever the expansion is no longer needed the placeholders are built into the plugin.

**Comment by Mayomi** [comment]
So I deleted expansion, then plugin hooked successfully.
But till no response. Is it not error?

https://imgur.com/a/aoKbDao
