### ISSUE TITLE
Tournament Wiki

### ISSUE THREAD

**Issue by WarnDangerous** [JCulley/ProQuests-Documentation#136]
Hey ! 

The tournament wiki has not been updated, so impossible to use the files, is it possible to update it for ProQuests v2 please ?

Cordially

**Comment by JCulley** [comment]
Not an error or a suggestion so closing the issue.

**Comment by WarnDangerous** [comment]
So how can I ask you to update it ?

**Comment by JCulley** [comment]
There’s nothing to update, use the in-game editor if you wish to create tournaments.
