### ISSUE TITLE
No Dupe

### ISSUE THREAD

**Issue by WarnDangerous** [JCulley/ProQuests-Documentation#137]
Hey !
 I wanted to make quests like "break 15 diamond blocks", but I thought that people just have to break the block, place it, break it, 15 times, and he achieve the quest easily, do you think there is a solution to avoid placing and breaking same blocks ?

**Comment by JCulley** [comment]
This isn't a QA section. No break quests will only check for how many blocks the player has broken it will not take into account blocks they break and place themselves. It is your responsibility to manage circumstances such as these using other solutions such as not allowing a specific block to be placed using WorldGuard.
