### ISSUE TITLE
In game NPC creator not working

### ISSUE THREAD

**Issue by Iapet** [JCulley/ProQuests-Documentation#139]
I am currently running a 1.12.2 spigot server and i realised that the in-game NPC creator is somehow malfunctioning. When you press the "next page" button in the "no quest action & linked quest(for quest npc) /menu (for menu npc)" inventory page, it will not move on. 

p.s. I am using Citizens v2.0.22-SNAPSHOT (build 1493) and ProQuests v2.0.4.6 for the test server.
If you need more info. please tell me. I can take a video. Thanks.

**Comment by JCulley** [comment]
Please update to include details to adhere to the guidelines in place. In addition I need a better explanation with pictures or something as your description is very vague and I cannot grasp much from this other than it’s related to the NPC creator. If you don’t update this in 48 hours it will be closed.

**Comment by Iapet** [comment]
Sorry for not providing enough info. for you to determine the issue.
I have taken a ~1 minute video to indicate this problem. It should give you more info.
https://drive.google.com/file/d/1vnk_R5RuOZ-vp2ojeCXcNUEQLLKSpoF2/view

p.s. The console had no error log. 
If u need more info. please tell me. Thanks.

**Comment by JCulley** [comment]
This still does not follow the guidelines. Provide your console log and also a link to your Spigot account. I’m not asking for much.

**Comment by Iapet** [comment]
Arrr.. I am so sorry. I didn't read that page before.

Spigot Profile: https://www.spigotmc.org/members/iapetos_.35855/
Server Version: CraftBukkit version git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2)
Log: https://pastebin.com/tuVkax8A

**Comment by JCulley** [comment]
There is no error here as there is no next page. You didn't provide a location for the NPC which is required which is why the save button did not appear. You cannot save any creations unless they have all the required elements.
