### ISSUE TITLE
This issue is regarding plugin's WIKI page

### ISSUE THREAD

**Issue by MrRobotMann** [JCulley/ProQuests-Documentation#140]
I'm trying to click on Tournaments page and it directs me to Error Guideline. 

Spigot Page: https://www.spigotmc.org/members/mrrobotman.263842/
Server Version/Server log: N/A I don't believe that this information is essential for this kind of question ;p

**Comment by MrRobotMann** [comment]
I'm trying to see how this addon works ! please help!

**Comment by JCulley** [comment]
This is not an error or suggestion. There’s not much to it the description is on the plugin page. If you wish to create a tournament quest use the in-game editor. The wiki is currently in the process of being updated however won’t be completed for a few weeks

**Comment by MrRobotMann** [comment]
Can you please at least tell me how can I set up a tournament quest ?

**Comment by JCulley** [comment]
> If you wish to create a tournament quest use the in-game editor.

**Comment by MrRobotMann** [comment]
Ok, I tried and used in-game editor for this but when I'm trying to edit anything on this tab http://prntscr.com/jtuh8j nothing appears to be happening no console logs nothing!

Running on spigot 1.8.8

**Comment by MrRobotMann** [comment]
Please help!
