### ISSUE TITLE
In-game editor problems!

### ISSUE THREAD

**Issue by MrRobotMann** [JCulley/ProQuests-Documentation#141]
I'm using your one of your addons (Tournaments),Trying to create a tournament using the ingame editor there is one issue! Pressing any button on this tab http://prntscr.com/jtuh8j it closes the GUI and directs to the chat in order to type a value for the following option BUT when I'm typing the value, the plugin stays IDLE, no errors on console no error messages I'm just stack on this option until I log out!

Spigot Profile: https://www.spigotmc.org/members/mrrobotman.263842/
Server Version: 1.8.8 SPIGOT
Server log: N/A (As I mentioned before there was no error on console while doing that!)

**Comment by JCulley** [comment]
Provide your log file (not a suggestion), provide a better explanation of what you were trying to do when it goes”IDLE”, explain what you mean by idle. Unfortunately I cannot understand the issue if you don’t explain the issue.

**Comment by MrRobotMann** [comment]
Server Log File: https://hastebin.com/otizemulaw.md
And give a second I will upload a video to understand what I mean by telling you that the plugin stays IDLE ^-^

**Comment by MrRobotMann** [comment]
here is the youtube video regarding this issue! 
https://www.youtube.com/watch?v=_DkKcPQYsgQ&feature=youtu.be

**Comment by MrRobotMann** [comment]
so ? have you find a solution to this problem ?

**Comment by JCulley** [comment]
I don’t have time to look at it today, and regardless even if I did if there is an issue a fix would not be immediate. So be patient.

**Comment by MrRobotMann** [comment]
Is there any way to create a tournament using console and not in game editor ?

**Comment by JCulley** [comment]
Was going to investigate however the video provided is not available to view. Will have to come back to this at a later point.

**Comment by MrRobotMann** [comment]
Hey at least view the video provided I changed the video settings so you can view it!
https://www.youtube.com/watch?v=_DkKcPQYsgQ

**Comment by JCulley** [comment]
Please stop spamming these issues. I don't have every second of my day to investigate issues. From initial glances it appears as though ProQuests is not even receiving the chat event to parse whatever was typed in as it would either send you a message stating its invalid or throw an error in console. Now although you thought there was "nothing" in your console I can clearly see ProQuests outputting you have referenced a quest which does not exist named test.

You can attempt to remove plugins which use the chat event to see if that fixes the issue and also remove the reference to the tournament you have created with an invalid quest (if you don't have any tournaments in your configs let me know).

I am currently at work so I am unable to look into the code and test locally on my development server until later.

**Comment by MrRobotMann** [comment]
Alright thanks!

**Comment by MrRobotMann** [comment]
Okay, so I tried to run ProQuests and the addon on a seperate test server without any other plugins and the same issue still occurs. Also I don't have any tournaments on my configs.

**Comment by MrRobotMann** [comment]
[20:47:57 INFO]: Mr_RobotMan_ issued server command: /quest create test
[20:47:59 INFO]: [ProQuests] Linked quest for 'test' is invalid
[20:48:12 INFO]: [ProQuests] Linked quest for 'test' is invalid
[20:48:16 INFO]: [ProQuests] Linked quest for 'test' is invalid
[20:48:33 INFO]: [ProQuests] Linked quest for 'test' is invalid
This is the console log when I tried to create a quest using /quest create

**Comment by MrRobotMann** [comment]
Also can you provide a tournament quest example ? At least to edit it using notepad and not with ingame editor ^-^

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-tournaments-add-on.30049/update?update=229390
