### ISSUE TITLE
Catch Creator Exceptions For All Quests

### ISSUE THREAD

**Issue by MrRobotMann** [JCulley/ProQuests-Documentation#143]
The console pops up an error https://hastebin.com/dusukocizi.md ( line 248 )

Spigot Profile: https://www.spigotmc.org/members/mrrobotman.263842/
Spigot Version: Spigot 1.8.8
Server Logs: https://hastebin.com/dusukocizi.md

**Comment by MrRobotMann** [comment]
Also I cannot understand how tournaments working! Can you please provide an example file ? Like the one you showed case on your plugin's spigot page? Thanks!

**Comment by JCulley** [comment]
Please do not open issues without sufficient information. This is not an error whatsoever as you entered an invalid value not specifying all of the required parameters for a required material in your Break Quest. This is only a missed exception handler so not really an issue regarding functionality however i'll address it later on. 

Also, keep issues open related to one specific topic, they should not be used as a Q&A. No I do not have any example files to provide at this time.

**Comment by MrRobotMann** [comment]
Oh okay, Wanted to keep all my issues in one ticket so I don't spam you ;p

**Comment by MrRobotMann** [comment]
Also, I see now that this error does not cause any issue on the quests but I still need an example file for your tournaments addon please!

**Comment by JCulley** [comment]
> No I do not have any example files to provide at this time.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=229947
