### ISSUE TITLE
Bug with in game editor

### ISSUE THREAD

**Issue by carl7345** [JCulley/ProQuests-Documentation#146]
So I'm trying to add a mining quest where the player has to mine iron. I tired setting the required materials iron and the format it said to use was <Material>:<Data>:<Amount>. I tired using 15:0:10 (15 for the material iron, data 0 since it has no other block types like wool does, and amount 10). And it gives me the message  "The value you have entered is invalid". I realize this is most likely me just doing this wrong but I made a post about it earlier asking for help and the response I got was "This is in no way an error". I only posted here because the spigot page says "The only place to ask for assistance is through a Github issue". And also the wiki didn't cover the issue I'm having. Sorry to be a nuisance, I'm just looking for some assistance.

Spigot account: https://www.spigotmc.org/members/carl7345.117002/
Spigot version: Spigot 1.12.2. Also using the latest version of the plugin
Nothing comes up in console.

**Comment by JCulley** [comment]
I already told you read the format that the message tells you, you’re clearly not following it
