### ISSUE TITLE
Break quest not registering when I break a block 

### ISSUE THREAD

**Issue by carl7345** [JCulley/ProQuests-Documentation#147]
So I have a quest where you have to mine iron, it was working perfectly fine last night but I've woke up today and now it's not counting any iron you mine towards a quest. I changed nothing on the quest, however I did reload the plugin a few times. Any help would be appreciated.  
 
Spigot account: https://www.spigotmc.org/members/carl7345.117002/
Spigot version: Spigot 1.12.2. Also using the latest version of the plugin
No errors in console
Quest config:  https://pastebin.com/PgjjtKdi

**Comment by JCulley** [comment]
Alright so let’s go over a couple things here.

First even after you complained and left a review where you stated the support is “flat out terrible” and that I “straight up refused to help” and I responded stating you didn’t provide enough information you still opened this issue not provided sufficient information. In addition why would I offer support for someone taking the time out of my day to assist you when you don’t appreciate it and think it’s “terrible”?

So let’s get into what you didn’t provide me:

1) You failed to provide me a log file. As stated in the guidelines you MUST provide your ENTIRE log file, it doesn’t matter if you don’t see any errors or even if you do I ask for the entire thing. I’m asking for a log file not just errors.

2) You failed to actually explain the issue in any manner which I could work with. You state it was “working perfectly fine” last night and now it’s “not counting”. So I have no idea what you think “fine” is seems how you have left so many holes in this statement I don’t even know the conditions of the scenario. For all I know you don’t even have the quest active.

Now I can say I had a quick glance at your config file and their is absolutely no way it was “working perfectly fine” when your required items do not match any existing item in Minecraft. I’ll leave it at that, please don’t come back here asking for help if you’re going to publicly complain and insult the support.

**Comment by carl7345** [comment]
@JCulley  The reason I said the support was terrible is because on the last post I made you clearly know what I was trying to do and what I was doing wrong. However instead of telling me what I was doing wrong, you just told that it wasn't an error and then in the next post you told me to go read the format. As for the format, it says <Material>;<Data>;<Amount> I put the material as IRON_ORE (Every other plugin I use recognizes iron ore as that material name), Data as 15, and amount as 20. Please can you just help me, you know what I'm doing wrong and I don't see why you're not telling me.

**Comment by carl7345** [comment]
As for the log: https://pastebin.com/iB24nH7X

**Comment by JCulley** [comment]
Correct the separator is ‘;’ not ‘:’ as you were initially using. The issues section is not for configuration assistance if you don’t know which materials and data values to use you should read up on the topic. However seems how you posted a review criticizing my support I don’t feel inclined to provide you any.

**Comment by carl7345** [comment]
@JCulley  I deleted the review. I'm using ; instead of :. And on the spigot page it says to come here for assistance, says nothing about only errors and suggestions, that's why I came here. I have read up on materials and data values, I've used them many times before with other plugins. All the material names I've found is IRON_ORE, iron_ore and minecraft:iron_ore.

**Comment by JCulley** [comment]
Still doesn’t negate the fact you opened it in the first place. It clearly states the wiki page will provide information and you must follow the guidelines before opening an issue which this does not fall into either issues category being errors or suggestions. Regardless read up here if as need assistance with data values https://minecraft.gamepedia.com/Java_Edition_data_values

**Comment by carl7345** [comment]
@JCulley Yeah this is one of the pages I used. It says the material name is minecraft:iron_ore but it says the value you have entered is invalid.

**Comment by JCulley** [comment]
IRON_ORE is correct there is no such data value 15 for IRON_ORE if you actually read what I’ve been telling you, you would have learned something. Read the page I linked as you obviously have no clue what a data value even is.

**Comment by carl7345** [comment]
Well thanks for finally helping me after 3 posts, as for the data value you said material id on the review comment that's why I was using 15. Like if you was nice and helped people without them having to make 3 posts over over 10 comments underneath maybe your plugin would have more than only 3 stars. You didn't only waste my time with dragging this out, you wasted your own. It's just much easier if you're nice and helpful to people. Thanks for the support.

**Comment by JCulley** [comment]
If you had acknowledged what I stated in the first post we wouldn't be having this discussion. If you had acknowledged the advice I had given it wouldn't have been dragged out. Maybe help yourself before asking for help.
