### ISSUE TITLE
Citizen & MVdWPlaceholderAPI Hook Updates

### ISSUE THREAD

**Issue by Iapet** [JCulley/ProQuests-Documentation#149]
Both citizen2 & mvdwplaceholderapi has been updated to a new version. If you have time, can you update the hook reference jar file too. 
Cause I am having some troubles with the quest npc and i'm still finding the reason...
Thank you.

Spigot: https://www.spigotmc.org/members/iapetos_.35855/
Version: git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2)

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=230894
