### ISSUE TITLE
How do I disable auto-starting quests?

### ISSUE THREAD

**Issue by minepaoz** [JCulley/ProQuests-Documentation#150]
Ask About Proquests 2.0.5
how can i disable join quests?
when player join server A quest will automatic accept the quest
but i want to disable it

**Comment by minepaoz** [comment]
i cannot progress a project if something are problem, i can't create more quest because i need to disable auto-starting quest

**Comment by PickleZPlayZ** [comment]
Its a permission given to a player. Read the wiki
