### ISSUE TITLE
Block Break Error

### ISSUE THREAD

**Issue by Ragnarak123** [JCulley/ProQuests-Documentation#151]
Hi , at first I'm Turkish so sorry for my bad English

I've purchased ur plugin "Pro Quest" but player's can't complete the break quests.
I can when I'm OP.
When server is restart player complete the quest.
How can i fix that

And yes , I use the lastest version of plugin.

**Comment by JCulley** [comment]
Completely off-topic and not even an error or configuration question. Please read the wiki.

**Comment by Ragnarak123** [comment]
I read the wiki but i can't find the error.
