### ISSUE TITLE
NPC folder files not loading

### ISSUE THREAD

**Issue by Iapet** [JCulley/ProQuests-Documentation#152]
In the past few days, I have been investigating on the issue that the NPC menu malfunctioning after server restart. And I found out that, when the general configuration "**use_folders:**" is set to "**true**", the npcs will not be detectable after a server restart.

It seems like proquest skipped to load any npc config file when "**use_folders: true**"

This is the "**use_folders: true**" server log (for proquest initialising).

> [14:55:52] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:55:52] [Server thread/INFO]: [ProQuests] Loading quests...
> [14:55:52] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'break-quest' quest
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'chat-quest' quest
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'enchant-quest' quest
> [14:55:52] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:55:52] [Server thread/INFO]: [ProQuests] Loading menus...
> [14:55:52] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'completed-leaderboard' menu
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'default' menu
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'lifetime-leaderboard' menu
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'monthly-leaderboard' menu
> [14:55:52] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'weekly-leaderboard' menu
> _------- Other plugin loading -------_

This is the when "**use_folders: false**" server log will look like (for proquest initialising).
> [14:58:53] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:58:53] [Server thread/INFO]: [ProQuests] Loading quests...
> [14:58:53] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:58:53] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'test' quest
> [14:58:53] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:58:53] [Server thread/INFO]: [ProQuests] Loading menus...
> [14:58:53] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:58:53] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'TEST' menu
> _------- Other plugin loading -------_
> [14:59:00] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:59:00] [Server thread/INFO]: [ProQuests] Loading NPCS...
> [14:59:00] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> [14:59:00] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'test' NPC

Spigot: https://www.spigotmc.org/members/iapetos_.35855/
Version: git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2)
Plugin Version: ProQuests v2.0.5

**Comment by JCulley** [comment]
Full log file please.

**Comment by Iapet** [comment]
Server log with use_folders set to true (after restart)
https://pastebin.com/X7U2By0Q

yml file in the NPC folder
https://pastebin.com/TeirX7Vh

Idk why, but when the use_folders is set to "true", after a server restart, all the npc config will not load. 
U can only open the npc menu in the same server session that u created it.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=230894
