### ISSUE TITLE
[ProQuest v2.0.6.1 | Spigot 1.12] Not access to the ports used

### ISSUE THREAD

**Issue by Melowelei** [JCulley/ProQuests-Documentation#154]
Hello ! ProQuest is using ports, but to use a specific port I have to ask at my host if I want it, so how can I fix this issue please ? Thanks.

**Comment by JCulley** [comment]
If you're going to open an issue please follow the guidelines. Regardless the ports are a future planned feature for synchronizing data between servers however at the current time it only sends diagnostics, there is no impact if it connects or not.

**Comment by Melowelei** [comment]
I understand that you need this function, but the thing is my host are crashing my machine at the time of when ProQuest is using a port, because on my host it isn't allowed to use port not previously reserved, also ProQuest are using all time (restart) a different port, so I can't ask my host to get a specific port, if you make a fix or configurable port for this feature, I would be able to fix my issue by just asking this specific port to my host :c
Hope you understand, thanks !

**Comment by JCulley** [comment]
The plugin simply looks for any port available at the time, and will only make so many attempts to find one. I'll consider changing it however I would recommend you reach out to whatever hosting company you deal with as they could simply block the ports if they don't want them being used rather than shutting your server down.

**Comment by Melowelei** [comment]
Thanks for your support @JCulley,
Yes you are right, I just asked if they can improve the system about what you told me, but I don't know if they will work on it.
But other then that, do you think you would be able to add a simple config option ? Like this I can just set this to false and be able to use the plugin, also it will be great for people who will have the same problem one day (maybe).

**Comment by Melowelei** [comment]
@JCulley,
Any news please ?
