### ISSUE TITLE
Add crafting quest

### ISSUE THREAD

**Issue by darkblazeman** [JCulley/ProQuests-Documentation#156]
I like obtain quest and how it works, however I think making another quest type being based around crafting would be good. the quest is completed as soon as you exit the crafting table (or counted as progressing if multiple items are required to craft).
Main reason for asking this is because I want to encourage people to go back to the basics of crafting, obtaining can be completed by receiving items which is why I am asking for this. 
This is just a suggestion, thanks.

**Comment by JCulley** [comment]
Originally this was suggested a while ago however there is no craft event so it’s rather difficult to determine what someone is crafting without creating an extensive system for checking and also validating the item was created. I’ll try a couple things within the next week but it’ll probably be leaning towards not being added as it’s more of a cosmetic effect when you could accomplish the same thing with an obtain or delivery quest.

**Comment by darkblazeman** [comment]
Yeah I understand. I know the same thing can be accomplished but some players can buy the item I want crafted from others which is why I wanted to suggest this. Thanks for replying and taking interest, either way whatever happens is fine, thanks.

**Comment by JCulley** [comment]
Actually I just searched it quickly and found they did add a CraftItemEvent recently in one of the versions not sure if it’s only 1.12 but I’ll add the quest support for whatever version it was added for and up.

**Comment by darkblazeman** [comment]
Awesome, thanks!

**Comment by JCulley** [comment]
After looking into it the CraftItemEvent doesn't seem to work when actually crafting an item while I was testing. The implementation seems rather convoluted and isn't very clear so unfortunately I won't be able to add this
