### ISSUE TITLE
Quests not saving during creation

### ISSUE THREAD

**Issue by AtomixCM** [JCulley/ProQuests-Documentation#158]
https://hastebin.com/pobesevugi.sql
Spigot: 1.8

The quest isn't saving the blocks required that I set for it in the editor. I set it to 2500000 but it keeps going back to 50.

**Comment by JCulley** [comment]
Please follow the guidelines. https://github.com/JCulley/ProQuests-Documentation/wiki/Error-Guidelines

**Comment by AtomixCM** [comment]
https://hastebin.com/pobesevugi.sql
Spigot: 1.8
Spigot Account: CM_lectric
There seems to be a problem with the quest editor. I'm not sure what it means by this menu is already loaded. All I can say is that the edits don't save.

**Comment by JCulley** [comment]
Description wasn't very useful and I would appreciate if you would add more information if you are going to open an issue in the future. Regardless this is not an issue. If you look at your log it clearly states that it is not loading the newly edited file as there is already a quest loaded with the same identifier. This is the case when you edit pre-existing quests as a safeguard it won't override it unless explicitly told to. The file was already saved all that is required is a simple /proquests reload.

Concluding with this I would like to mention this is not something you should be opening an issue for at all. Please do your own analysis and try to figure out your own problems before opening any issues, and if you do feel it needs to be escalated please provide an adequate description, and supporting documents. This was not something that I needed to get involved with as its not even an error in the end. Provided you had checked the config file generated on your server by the editor you would have noticed it had already been modified and saved with the changes you had made.

**Comment by AtomixCM** [comment]
Okay, understood. Would you mind pointing me to the place in your wiki where it says you must reload the plugin for these changes to take effect?

**Comment by JCulley** [comment]
There’s not.

**Comment by AtomixCM** [comment]
Okay, thanks. Maybe you should consider adding that to the wiki.

**Comment by JCulley** [comment]
There’s really no reason nor place to put it on the wiki page as it can be inferred by the console log messages. Thanks for your opinion on the matter though.
