### ISSUE TITLE
Quest Menu Editor Freeze

### ISSUE THREAD

**Issue by AtomixCM** [JCulley/ProQuests-Documentation#161]
Spigot: 1.8
Spigot Link: https://www.spigotmc.org/members/cm_lectric.232281/

When I go ahead and start editting a menu and click all the way to the last page on the editor, I can't do anything on the last page. When I hit esc, proquests freezes. I can't type in chat or run any commands. 

Once I run "proquests reload" in config and relog, I then gain access to using the plugin again. However, I would assume that you don't want your in-game editor freezing editors in the middle of creating a menu. 

Thank you.

https://hastebin.com/udubideneg.erl

**Comment by JCulley** [comment]
I’m going to respond to the “error” you are encountering and have removed any parts which generally have nothing to do with what you are actually trying to report.

I discovered this issue actually last night while I was testing a new feature myself and it will be fixed in the upcoming update.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=231536
