### ISSUE TITLE
Please provide more examples

### ISSUE THREAD

**Issue by aulrone** [JCulley/ProQuests-Documentation#165]
This was my obvious setup for an obtain quest but it doesn't work. Please provide more examples, especially with some external quest types. Like I wouldn't even know to do askyblock level... level: 1000?

type: OBTAIN_QUEST
material: COBBLESTONE;0;64
duration: 9999
repeat_delay: 600
repeatable: true
cancelable: true
command_start: false
editable: true
start_actions:
- '[Message]&fYou accepted the &6Cobble Generator&f quest.'
complete_actions:
- '[Title]&bCobble Generator &fCompleted!'
- '[Message]&fReceived &a+20 XP Levels&f.'
- '[Message]&fReceived &2$&a2,500&f.'
- '[ConsoleCommand]xp +20L %player%'
- '[ConsoleCommand]eco give %player% 2500'

**Comment by JCulley** [comment]
Use the in-game editor if you don’t understand. Please stop opening useless issues. In addition not a single one has followed any guidelines.
