### ISSUE TITLE
Async Command Crashing Server

### ISSUE THREAD

**Issue by LeDadSnatcher** [JCulley/ProQuests-Documentation#167]
When one of my players joins, it crashes my server with this error: https://pastebin.com/m6Uj1rgW

It says it is this plugin and this is a major issue because everytime he joins, this happens. 

I'm not sure what it is either because I don't have any quests which should issue those commands

I am using version 2.0.7 on 1.8.8. My Spigot username is DenyCC

**Comment by JCulley** [comment]
Please update to adhere to the guidelines or this will be closed.

**Comment by JCulley** [comment]
Still doesn’t follow the guidelines as you have not included your entire log file. This is also in no way an error, you can debug yourself by actually reading the stacktrace you have provided or wait for someone else to assist you.

**Comment by LeDadSnatcher** [comment]
If I include the whole log file, will it be publicly available? Player IPs aren't something I want getting out and in doing so, I'd technically be breaking GDPR.
