### ISSUE TITLE
[ProQuest 2.0.7] - PlaceholderAPI not working

### ISSUE THREAD

**Issue by Melowelei** [JCulley/ProQuests-Documentation#168]
1. Spigot Account : **https://www.spigotmc.org/members/__melowelei__.378949/**.
2. Spigot Version : **CraftBukkit version git-Spigot-596221b-86aa17f (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT**.
3. ProQuest Version : **https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/update?update=231536**
4. Problem : The PlaceholderAPI placeholders are not working, I tried to parse it with the "/papi parse [The Placeholder]" and it's only showing the placeholder not replacing with what it should.
5. Example 1 : When I use "/papi parse %proquests_total_active_quests%" it show the "%proquests_total_active_quests%" in chat instead of show for exemple "0" if I don't have any active quests.
6. Example 2 : When I use "/papi parse %proquests_total_points%" it show the "%proquests_total_points%" in chat instead of show for exemple "0" if I don't have any active quests.

**Comment by JCulley** [comment]
This doesn’t follow the guidelines as you failed to provide a log file. Regardless, this is not and error as the PAPI parse command only works with expansions whereas ProQuests just provides them directly within the base plugin. Actually try the placeholder somewhere else and you will see it working.

**Comment by Melowelei** [comment]
I added the **[PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/)** placeholder on the **[CustomGUI](https://www.spigotmc.org/resources/customgui-new-ownership-updates-underway-sale.7386/)** and it look still **[not working](https://imgur.com/5AWTX6D)**.
How do you explain others plugins **[PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/)** placeholders are working, but for ProQuest none of the placeholders you listed are working ?

**Comment by JCulley** [comment]
Provide a log file if you wish for any further assistance.

**Comment by JCulley** [comment]
`[17:24:27] [Server thread/INFO]: [ProQuests] Enabling ProQuests v2.0.6.1`

You are not in fact using the latest version, so don't ask for any support until you update.

**Comment by Melowelei** [comment]
There is the new **[latest.log](https://hastebin.com/inilecemej.md)** with the latest **[ProQuest](https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/)** version, sorry about that.

**Comment by JCulley** [comment]
A registration call was missed for the expansion, has been addressed for the next update.

**Comment by Melowelei** [comment]
Okay, I will wait the next update and try it, thanks.

**Comment by Melowelei** [comment]
Any news about the issue please ?

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/update?update=239764
