### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LandonEZ** [JCulley/ProQuests-Documentation#169]
The server starts with this error:

24.07 00:47:22 [Server] WARN Exception in thread "Craft Scheduler Thread - 45" 
24.07 00:47:22 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin ProQuests v2.0.7 generated an exception while executing task 9421
24.07 00:47:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
24.07 00:47:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
24.07 00:47:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
24.07 00:47:22 [Server] INFO at java.lang.Thread.run(Thread.java:748)
24.07 00:47:22 [Server] INFO Caused by: java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(Lorg/bukkit/OfflinePlayer;Ljava/lang/String;)Ljava/lang/String;
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.Messages.setPlayerPlaceholders(Messages.java:39)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.Messages.setPlaceholders(Messages.java:144)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.Messages.setPlaceholders(Messages.java:26)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:36)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.QuestUtil.checkActiveQuests(QuestUtil.java:10)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.listeners.PlayerJoin$3.run(PlayerJoin.java:33)
24.07 00:47:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
24.07 00:47:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

Then, no command does anything.

**Comment by LandonEZ** [comment]
Made a new issue

**Comment by JCulley** [comment]
You could’ve just added it here but ok.
