### ISSUE TITLE
PlaceholderAPI Unsupported Version

### ISSUE THREAD

**Issue by LandonEZ** [JCulley/ProQuests-Documentation#170]
Spigot Account : https://www.spigotmc.org/members/rebelcraft.141340/
Spigot Version : TacoSpigot 1.8.8
ProQuest Version : 2.0.7
Problem : An error pops up in the Console and no commands work
Example 1 : /quest doesnt work
Example 2 : /creator doesn't work

Error:
24.07 00:47:22 [Server] WARN Exception in thread "Craft Scheduler Thread - 45"
24.07 00:47:22 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin ProQuests v2.0.7 generated an exception while executing task 9421
24.07 00:47:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
24.07 00:47:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
24.07 00:47:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
24.07 00:47:22 [Server] INFO at java.lang.Thread.run(Thread.java:748)
24.07 00:47:22 [Server] INFO Caused by: java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(Lorg/bukkit/OfflinePlayer;Ljava/lang/String;)Ljava/lang/String;
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.Messages.setPlayerPlaceholders(Messages.java:39)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.Messages.setPlaceholders(Messages.java:144)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.Messages.setPlaceholders(Messages.java:26)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:36)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.util.QuestUtil.checkActiveQuests(QuestUtil.java:10)
24.07 00:47:22 [Server] INFO at com.culleystudios.proquests.listeners.PlayerJoin$3.run(PlayerJoin.java:33)
24.07 00:47:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
24.07 00:47:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

**Comment by JCulley** [comment]
This still does not follow the guidelines provide your complete log file as stated in the guidelines and do not open another issue for this. Also don’t name your issues just “error” it’s very undescriptive.

**Comment by LandonEZ** [comment]
Literally, I bought your plugin for 14 damn dollars and you can't just help me. Honestly a dick move.

**Comment by JCulley** [comment]
All I said is provide the log file? What’s the issue here?

**Comment by LandonEZ** [comment]
I sat here and gave you all the info and you still wouldn't do anything. Why do you need a log file when I gave you the error it is pertaining to? Plus, how do you even send a log file?

**Comment by JCulley** [comment]
You’d think I was asking for something complex here. Just copy the contents onto a site like pastebin and provide the link.

**Comment by LandonEZ** [comment]
from /logs?

**Comment by JCulley** [comment]
Yes.

**Comment by LandonEZ** [comment]
You can use the command once then it says Internal Error. I believe the error is at the bottom: https://pastebin.com/wesHRw2T

**Comment by JCulley** [comment]
As can be read from the error it’s unable to find a PlaceholderAPI method which was introduced in the latest version.

This is also stated in the log even if you don’t know how to read a stacktrace:

> [12:47:23] [Server thread/INFO]: [ProQuests] PLACEHOLDER_API version mismatch, ProQuests references version 2.9.1. If you are using the latest version open an issue on GitHub for an updated version! You will not receive support regarding this hook while using a mismatched version

So either remove PlaceholderAPI or update it.

I’m going to add a check which will just disable PlaceholderAPI if this method is not found although it doesn’t change the fact that you have to ensure you’re using support dependencies otherwise there’s not much I can do. In the future please investigate a little further before opening an issue as it’s clearly stated in the log that the versions do not match.

Going to leave this open for the check to be added however the issue is resolved.

**Comment by LandonEZ** [comment]
Fixed

**Comment by LandonEZ** [comment]
thank you

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/update?update=239764
