### ISSUE TITLE
Error With Block Place Quest

### ISSUE THREAD

**Issue by LandonEZ** [JCulley/ProQuests-Documentation#171]
I would put all my Spigot name and everything but I just opened a ticket and he knows who I am.

Anyways, when you try to do a Block Place quest, every block you place completes the quest and this error:
(its at the bottom)
https://pastebin.com/aS87Vb2f

**Comment by JCulley** [comment]
Even if you just opened an issue please provide all of the information to meet the guidelines. As I said to you earlier please attempt to work through things yourself. Whatever command you are trying to run cannot be run async so you must prefix it with a [SyncTask]. This is noted in the documentation.
