### ISSUE TITLE
ProQuests Reference Updates

### ISSUE THREAD

**Issue by Tyloonie** [JCulley/ProQuests-Documentation#172]
Spigot account: https://www.spigotmc.org/members/tyloonie.130061/
Spigot version: PaperSpigot-1.12.2
Log: https://hastebin.com/uzojiyupug.md

As you can see in the log, ASkyBlock, Buycraft and mcMMO needs to be updated. Thanks.

**Comment by JCulley** [comment]
Will look to update them for the next update

**Comment by JCulley** [comment]
References have been complied against the latest versions:

- ASkyBlock v3.0.9.4
- Buycraft v10.6.2
- mcMMO v1.6.0-SNAPSHOT

While updating the references is was discovered there were no API changes to any of them so they will all run as usual.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/update?update=239764
