### ISSUE TITLE
GUI Title Suggestion

### ISSUE THREAD

**Issue by Tyloonie** [JCulley/ProQuests-Documentation#174]
Hello,

This is merely a suggestion. Since you made it possible to change every single item in the GUI menu, I was wondering if it could become possible to change the GUI titles of the editor as well?

(Like this: https://gyazo.com/fef10abf7b76bb8458dce33af3e686b5)

**Comment by JCulley** [comment]
Not sure if this would be completely worthwhile to implement as it's currently used to display the identifier for the current item being edited. Could you explain your reasoning for adding the title customization seems how its really only a feature used by admins anyways? Also what are your thoughts on displaying the identifier of what you're currently working on?

**Comment by Tyloonie** [comment]
The default Minecraft vanilla GUI title is without any user defined colors. I see that you've been using &8 to color all admin GUI titles; it simply stresses me out since all my other GUIs on my server only has the vanilla GUI color which is the one that looks best in my opinion - it's the same color as when you open a chest, a furnace etc.

**Comment by JCulley** [comment]
Alright, the option has been added for the upcoming version release.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/update?update=239764
