### ISSUE TITLE
Help with wheat Break Quest

### ISSUE THREAD

**Issue by arkobat** [JCulley/ProQuests-Documentation#176]
I have a quest, where the player need to destroy 5 wheat crops.
But whenever they destroy them, it dosn't count.
Server version: 1.8
The quest config: https://pastebin.com/euEDk7NZ

**Comment by JCulley** [comment]
If you want to figure out your issues you should read up on data values as your answer will easily be found there. https://github.com/JCulley/ProQuests-Documentation/wiki/Materials-and-Data-Values

I'll modify this for you so someone from the community to explain it further if they choose to do so however like I said if you read up on it you'll know for other cases which you'll need data values in the future :)

**Comment by JCulley** [comment]
Seems how its been over a month i'm assuming you've taken my advice and read up on data values. Closing this issue.
