### ISSUE TITLE
Plugin not usable 

### ISSUE THREAD

**Issue by johnsoncui02** [JCulley/ProQuests-Documentation#177]
Spigot Username: https://www.spigotmc.org/members/johnsoncui02.292466/
Spigot Version: 1.12.2
Plugin Version: 2.0.7
Console Bug: https://pastebin.com/MpbZ4ZjB
Description: Not exactly sure what it entails, but it sums up to the plugin not responding to any of the commands such as /proquests, /proquests help, etc.

**Comment by johnsoncui02** [comment]
According to another Developer

AsyncPlayerChatEvent so error on chat event
org.bukkit.event.EventException: null so the written code can't be read by the console (JavaPluginLoader)
You need source code and check : line 306

**Comment by JCulley** [comment]
Hey,

So I can see you provided a snippet of your log however I will need the entire log to actually investigate the issue. As per the description if you can provide more details such as when does it occur, what were you doing exactly before it happened etc.

I appreciate the additional information provided by another developer however this 

> org.bukkit.event.EventException: null so the written code can't be read by the console

does not make any sense. I have reviewed countless stack traces whilst developing and will be able to do so when you provide me the entire log.

Thanks! :)

**Comment by johnsoncui02** [comment]
Additional Information: 
Validation Profile: https://www.spigotmc.org/members/johnsoncui02.292466/
Entire Log: https://pastebin.com/Hxb1AqgL

Error occurs when a player attempts to type anything in chat at all. Anything. ex. a b c, 123. More specifically, there's a error that is generated in console when a player joins the server.

**Comment by JCulley** [comment]
Seems as though the actions list attempting to be executed for the player is null. If the player it is attempting to execute for is yourself then it will not completely initialize your profile meaning you cannot utilize the plugin. You can reset the player data for the player experiencing the error and it will be resolved.

A safe guard has been implemented for the next update to prevent the actions passed from attempting to even be processed and will instead log to the console detailing the error that has occurred to prevent the plugin from becoming unusable for the player.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/update?update=239764
