### ISSUE TITLE
Delivery Quest Issue?

### ISSUE THREAD

**Issue by KodxQ8** [JCulley/ProQuests-Documentation#179]
Spigot Username: https://www.spigotmc.org/members/specialgamin.135348/
Spigot Version: 1.12.2
Plugin Version: 2.0.7
Console Bug: None
Description: When you try creating a delivery quest and choose to take items, the GUI makes you stuck where you can't exit the GUI.

**Comment by JCulley** [comment]
This does not follow the guidelines, please provide your log and additional information.

**Comment by KodxQ8** [comment]
https://hastebin.com/tapeminotu.sql
The point where I issue the command then do it shows no errors

**Comment by KodxQ8** [comment]
Another issue, when a player starts a delivery quest using the command, he has to start it again sometimes so the NPC can accept the items

**Comment by JCulley** [comment]
Please provide your **entire** log file as stated in the guidelines. Additionally keep issues relevant to a specific issue.

**Comment by JCulley** [comment]
Additional information requested has not been provided in over a week, closing this issue.
