### ISSUE TITLE
NPC Creation Issues

### ISSUE THREAD

**Issue by johnsoncui02** [JCulley/ProQuests-Documentation#180]
Spigot Username: https://www.spigotmc.org/members/johnsoncui02.292466/
Spigot Version: 1.12.2
Plugin Version: 2.0.7
Console: no sign of error
NPC Bug: https://i.imgur.com/RiwTIds.gifv
So, I want to create a quest that can start with an NPC. Like talk to an NPC then the quest will start by killing a mythicmob objective. So I created a NPC identifier name **test** and the quest is **test2**.  But when I edit the quest **test2** and try to bind NPC **test** to the Start NPC it wont recognize the NPC for some reason. Is this an intentional bug or am I do something wrong, apparently there is nothing stated in your Wiki so it might the process very confusing.

**Comment by JCulley** [comment]
You didnt follow the guidelines as you didn’t provide your log file, it is not optional. Regardless you have to reload the plugin for new NPC’s to be recognized before you can attempt to bind to them.
