### ISSUE TITLE
Balance Saving Issue

### ISSUE THREAD

**Issue by RubenStryker** [JCulley/ProQuests-Documentation#183]
Spigot Username: https://www.spigotmc.org/members/pichurrin.316310/
Spigot Version: 1.12.2
Plugin Version: 2.0.7
Console Bug: https://pastebin.com/7vTC0LnN
Description: 
Hi, I've been trying to get this plugin up and running for months.

It is really complicated and the support that has been given so far has been limited to "Update the plugin version", or "I do not understand you, publish a bug in github".
In short, I think the support is quite bad, even so ... I will expose the situation.

Well the steps that I have used to generate this error have been the following:

1. Create the menu
2. To finish creating the menu I need to create a mission.
3. I stop the creation of the menu, to do the mission.
4. I create the mission, in a very limited interface.
5. I return with the menu configuration.
6. I need an NPC to use it in the mission.
7. Stop the creation of the menu, to add the npc to the mission.
8. Configured or at least try, an npc (Errors everywhere and the NPC configuration is not saved) Example: Holodisplay and NPC player type with citizens.
9. I return to the configuration of the mission to select the action with the NPC (which then disappears)
10. I finish configuring the mission correctly and I save it.
11. I enter the menu configuration to add the mission slot.
12. Result = Can not find the identifier of the mission (Truly ridiculous), since he had saved it
13. I do a reload, to see if I can continue and fail!

**Comment by JCulley** [comment]
Hey there,

Will be happy to look into this once you provide your entire log file and also your malformed configurations which are the obvious root of this issue. Unfortunately there's not much I can do without adequate information. Also I don't appreciate the insults throughout so if you want me to investigate you will engage with constructive comments and opinions.

Thanks!

**Comment by RubenStryker** [comment]
You should understand that the plugin is pretty messy, you have to do 3 or 2 things at once, go stopping the creations of one to do or an NPC, or a menu. Then you need one of these three things (npc, menu and mission) are finished to finish the other, and others can not be finalized if they depend on others that have not yet finished.

Then I can pass the complete log, but no other error is seen nor how the configuration has not been saved ... which I find unfortunate.

I leave part of the last test, I do not like to risk much to delete the conversations and commands of the users go to delete some command entry executed by me.

Well I leave the last report: https://pastebin.com/EqtsMvkr

**Comment by JCulley** [comment]
> Will be happy to look into this once you provide your entire log file and also your malformed configurations which are the obvious root of this issue.

I don't believe I can be more clear, there's not much I can do unless you provide me the information I need to investigate. I don't understand in what way the design is "messy" you have to configure every aspect regardless so there's not really an easier way to do it. There is already a system in place to pause existing creators to work on others.

So provide your **ENTIRE** log file and also the malformed configs if you wish for any further investigation. I'm not asking for the world here.

**Comment by RubenStryker** [comment]
Here I leave the link, in the next days I will make another report to improve the environment to create missions, npc, menus and others.

In this .zip uploaded to the platform of Mega I have left the logs of the day of today of the server that I administer and all the configuration of the plugin.
https://mega.nz/#!7cJkmKTC!7B9-WweoaEiCjbOUhQ3QlcDl3ZJFufNNWgIXcfzt6WM
Greetings, I hope you can find the fault.

**Comment by JCulley** [comment]
I will not download files for my own security. Please provide them in plain text format.

**Comment by RubenStryker** [comment]
You are making many excuses for me, and complicating the support that you should give me.

Here the log: https://drive.google.com/file/d/14qx6_2bQ3Cqk7O0LpPsBGiXJZv6-fUWd/view?usp=sharing

Here are the files of your plugin: https://drive.google.com/drive/folders/1dsvU03kw0RwqR_exXcj41mqW5QiDBl9D?usp=sharing

It is no longer necessary to put your computer in danger, here you have them uploaded to the cloud.

Greetings and let your computer live a long time.

**Comment by JCulley** [comment]
Unfortunately you cannot preview .yml files in Google drive. Additionally the log file you provided does not include startup so it is of no use to me. I'm not making excusing I'm asking you provide sufficient information.

Thanks.

**Comment by RubenStryker** [comment]
What do you mean by not including the start?
I have given practically everything, what else can I offer?

**Comment by JCulley** [comment]
> Additionally the log file you provided does not include startup

As stated it does not include the server startup, therefor its not the entire log. You have not in turn actually provided me useable versions of anything to this point.

**Comment by RubenStryker** [comment]
The missions that it brings by default I had to delete them, because they were not erased by means of commands, they appeared as deleted and when restarting the server I returned to diamond only for speaking in a mission by default.

I was tired and I deleted it from the folder all the missions by default.

Regarding your last comment, the server does not currently restart it because we are making changes to the restart scripts. The server started for the last time 7 or 12 days ago.
But the tests I have started again, you just have to use the search engine and look at the first time you use / proquest.

A greeting.

**Comment by JCulley** [comment]
I'm sorry I read over your last message 2 times and still don't understand what you're saying. Regardless if you cannot provide me the following I will have no choice but to close the issue as there's nothing I can do without information to investigate.

1. You entire log file from server startup
2. Your malformed quest.yml files

I don't wish to continue with this back and forth, I would rather just investigate if an issue actually does exist.

**Comment by RubenStryker** [comment]
Well, I'm going to try to optimize all the problems that I have with this plugin.

For this I have started by deleting all the plugin settings and doing a basic test "Create a mission" and "link this mission to the menu that comes by default."

Logs: https://pastebin.com/X1nY6vqa
Quests.yml: https://pastebin.com/vUfYdEu3

The default functions work, they are simple and they work, although sometimes on a regular basis.
This is why I do not think that the quests should be in the file quests.yml, besides that this file does not appear nor generates anything.
![errorproquest](https://user-images.githubusercontent.com/24832320/44298674-78a4a000-a2e7-11e8-93e9-9760c9417057.PNG)

It's as if the missions that I believe do not exist, the same with the NPC.
And in this case, with the missions ... the logs do not see anything reflected!

But if I do a reload, it starts to fail and yesterday it gave me errors in click events in the interface.

I am looking forward to your response.

**Comment by JCulley** [comment]
> [12:45:35] [Server thread/INFO]: [ProQuests] Loading quests...
[12:45:35] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[12:45:35] [DiscordSRV - Initialization/WARN]: [DiscordSRV]
 
The current build of DiscordSRV is outdated by 28 commits! Get the latest build at your favorite distribution center.
 
Spigot: https://www.spigotmc.org/resources/discordsrv.18494/
Bukkit Dev: http://dev.bukkit.org/bukkit-plugins/discordsrv/
Source: https://github.com/Scarsz/DiscordSRV
 
[12:45:35] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'break-quest' quest
[12:45:35] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'enchant-quest' quest
[12:45:35] [Server thread/INFO]: [ProQuests] Succesfully loaded the 'chat-quest' quest

Based on the log file you have provided you never created/saved any quest whatsoever. They are not saved in the quests.yml by default as  “use_folders” is true by default.

I can clearly see in your log file you executed a create command but yet there is no evidence of you actually saving the quest. Additionally even if you did save the quest you would have to reload the plugin first or save it using the “OVERRIDE” or “OVERIDE ALL” methods as can be clearly read in the creator item descriptions. As of right now based on what you have provided me this doesn’t seem to be a plugin error of any sense and rather you just seem to be having difficultly following the process.

Please provide the actual .yml file of the quest file generated.

**Comment by JCulley** [comment]
Thanks that’s all I needed the entire time. What did you enter when you added the start cost to the quest?

**Comment by RubenStryker** [comment]
I put the following:
"VAULT; 10000"
Without the double quotes

**Comment by JCulley** [comment]
So I discovered the issue and it turns out all balance requirements have been saving incorrectly due to a missed function. A fix has been implemented I will be releasing it hopefully sometime today if not tomorrow.

Thanks for reporting this issue as it amazes me not a single person had given this error appears to have been in the plugin since at least the start of the year after doing a little digging.

I really do appreciate when people can provide errors such as this as it helps expand the plugin and addresses issues which I cannot always catch during private testing.

Thanks!

**Comment by RubenBarrionuevo** [comment]
I am glad to know that you have finally detected one of the many errors that it has, I am very surprised that no other user has noticed a failure like this.

Because it is something ... in my opinion, elementary. Maybe it's that many give up and do not continue

In the next few days, after trying the next update I will open another tickets with suggestions to improve the environment to create missions.

- Be able to use commands
- Options that are repeated or not defined very well as they work
- Failed with the NPC with Citizens
- Failures in environmental events
- The items that you put in your hand to carry out the mission do not work

And I sincerely hope to be able to put this plugin into operation and that it meets the expectations we had when buying it.

Regards and until next time

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-30-off-summer-sale-give-players-objectives.18249/update?update=239764
