### ISSUE TITLE
Help configuring progress actions

### ISSUE THREAD

**Issue by RubenBarrionuevo** [JCulley/ProQuests-Documentation#187]
Spigot Username: https://www.spigotmc.org/members/pichurrin.316310/
Spigot Version: 1.12.2
Plugin Version: 2.0.7.1
Description: 
Again I suggest the need for a tutorial that resolves certain issues.

The fact is that I am trying to perform a mission, in which 50 wither skeletons must be killed.

And I would like to add in some way that every time you kill 1 wither, you get a counter for the remaining number to kill.
But I still can not find the way to do this with the option of progress, I see the javascript and only see in the tutorial the variable %quest_remaining_duration%
![actionsjavascript](https://user-images.githubusercontent.com/24832320/44581428-e9433500-a79d-11e8-9dcf-3ac78ba70baa.PNG)

I get the feeling that the mission created does not progress, and as I commented in a previous suggestion ... in the last option of mobs
I do not know how to configure it!

I leave photos, because I do not see anywhere defined if the amount of mobs should be fixed on both sides, only in the last one, only in the first one or multiply the amount of mob set in both places 50 x 50
![requeriedmobs](https://user-images.githubusercontent.com/24832320/44581564-7c7c6a80-a79e-11e8-8752-5d330f5ede8c.PNG)
![totalmobs](https://user-images.githubusercontent.com/24832320/44581565-7d150100-a79e-11e8-870f-cca5052c1e9b.PNG)

I would value this help a lot, I do not think it is important, and I already told you something in the previous suggestion:
"There are many characteristics that are not well defined or there is not enough information about them.

But I see all this empty, it should not be like that ... it's not serious.
https://github.com/JCulley/ProQuests-Documentation/wiki/In-Game-Creator
If you do not have time see adding small parts as you can.

You do not have time to add it, but I do, to try everything?

Thanks for closing the post ahead of time."

I await an answer, greetings.

**Comment by RubenBarrionuevo** [comment]
Hi, I wanted to know the status of progress of the report I made

**Comment by JCulley** [comment]
I have already labelled it appropriately, whether or not other users are willing to offer their insight is out of my control.

**Comment by RubenBarrionuevo** [comment]
Ok, thanks definitely for nothing.

Definitely the plugin that I regret having acquired.

I will let the spigot team know and I will leave my comment.
You can close the topic, I will not need any more help.

The variables for the progresses I invented them out of nowhere, sure they work.
