### ISSUE TITLE
Problem with configuration (permissions)

### ISSUE THREAD

**Issue by MemorialThen** [JCulley/ProQuests-Documentation#188]
Hello,

So I have a problem.

Im using: TacoSpigot (1.8.9)
I don't know what versio of ProQuest im using have delete the version.
But my problem is simple!

Im using groupmanager, and im using permissions like that:

    - proquests.help
    - proquests.points
    - proquests.menu
    - proquests.menu.open.menu_1
    - proquests.quest.start.break_quest_1
    - proquests.quest.join.break_quest_1
    - proquests.quest.invite.break_quest_1
    - proquests.quest.kick.break_quest_1
    - proquests.quest.progress.break_quest_1
    - proquests.quest.cancel.break_quest_1
    - proquests.leaderboard

I can open my menu, but I cannot start the quest called: break_quest_1
Screen: http://prntscr.com/kn430u / http://prntscr.com/kn436s

When I use it with OP Permissions that work perfectly..
Someone have idea what wrong I do?

Thanks you!

**Comment by JCulley** [comment]
Follow the template and provide a link to your Spigot account and the complete log file from startup, otherwise I will have to close the issue.

**Comment by JCulley** [comment]
Never received a response when asked for specific information, closing.
