### ISSUE TITLE
QuestPackages Startup Error

### ISSUE THREAD

**Issue by Terrifical** [JCulley/ProQuests-Documentation#190]
**Spigot account** - https://www.spigotmc.org/members/godly.227924/

**Plugin version** - ProQuests 2.1-beta / ProQuests Packages 2.0.2

**Spigot Version** - Spigot 1.11.2 [Latest Build]

The startup error - https://pastebin.com/LgSAQEL6

**Comment by JCulley** [comment]
Please provide the complete log file as requested with all error reports.

**Comment by Terrifical** [comment]
https://hastebin.com/gocoxibopo.md

**Comment by JCulley** [comment]
Latest update fixes this issue (forgot to close this upon posting) https://www.spigotmc.org/resources/proquests-packages-add-on.31470/update?update=243091
