### ISSUE TITLE
Support for CrazyCrates & AdvancedEnvoys

### ISSUE THREAD

**Issue by xGodly** [JCulley/ProQuests-Documentation#192]
CrazyCrates: https://www.spigotmc.org/resources/crazy-crates-now-with-10-different-crate-types.17599/

AdvancedEnvoys: https://www.spigotmc.org/resources/⭕-advancedenvoys-⭕-extremely-customisable-supply-crates-1-7-x-1-13-x.57953/

CrazyCrates - 2nd most popular crates plugin:

• Opening a (crate)
• Open a (crate) 10x

AdvancedEnvoys - premium envoy plugin

• Opening x amount of envoys
• Opening x amount of envoys in a single drop

**Comment by JCulley** [comment]
CrazyCrates can be implemented, don’t understand the whole x10 thing however. If you’re referring to having it so they have to open 10 crates it will be customizable as is every other quest.

I have sent a PM to the author of AdvancedEnvoys requesting a copy of the plugin to access it’s API to create the quest, provided they’re okay with it. If not I unfortunately cannot add support for it.

**Comment by JCulley** [comment]
The author responded and will be adding the API needed for the quest.

**Comment by JCulley** [comment]
The author never got back to me, just reached out in an attempt to find out the status.

**Comment by JCulley** [comment]
After reaching out again the author has provided me a .jar and has mentioned the API includes the required events. This will be planned hopefully for the next release.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-1-give-players-objectives.18249/update?update=251793
