### ISSUE TITLE
Help with setting up ProQuests Packages.

### ISSUE THREAD

**Issue by Terrifical** [JCulley/ProQuests-Documentation#193]
I don't know where/how to start setting up ProQuest Packages. I can't find anything to help me either. I already made quests before ProQuest Packages was installed, and the menus. How can I hook ProQuest's Packages to that menu/quests? I'm very confused...

**Comment by Terrifical** [comment]
If you aren't going to give support to your buying you should have a WIKI dedicated to the ProQuest Packages addon. After all, we are the people that like your work so we buy add-ons so we can support you and give us, the buyers more content. 


You should also remove this line from the config. "If you have any questions feel free to ask me by
PM on spigot."

Not hating, just frustrated.

**Comment by JCulley** [comment]
Its in progress as can be seen here: https://github.com/JCulley/ProQuests-Documentation/wiki/Packages-Add-On

There is an example packages configuration provided, to use them in any ProQuests menu it is simply '{package_id}_{number}' the number refers to the random quest from the list to reference.

Thanks for pointing out that line it will be removed seems how everywhere else clearly states the GitHub here is the place to go for suggestions and error reports.

**Comment by Terrifical** [comment]
I don't understand, where do I add "{package_id}_{number}"

I'm sorry if I'm bothering you. I can promise you, I'm trying to figure it out on my own but I can't...
