### ISSUE TITLE
ProQuests can't hook into Holographic Displays

### ISSUE THREAD

**Issue by Terrifical** [JCulley/ProQuests-Documentation#194]
**Plugin Version**
2.1-beta ( Aug 27, 2018 )

**Spigot Version**
CraftBukkit version git-Spigot-28463de-a2af8f0 (MC: 1.11.2)

**Log File**
Error: https://pastebin.com/f8ASX5nz
Log: https://pastebin.com/eDzH5xBj

** Desc. **

Doesn't load up with the newest version of Holographic Displays. (Works with others)

Holographic Displays v2.3.0

**Comment by JCulley** [comment]
Please add a link to your Spigot account.

**Comment by Terrifical** [comment]
> Please add a link to your Spigot account.

https://www.spigotmc.org/members/godly.227924/

**Comment by JCulley** [comment]
Appears as if the author has modified the API to not allow instantiating of the API class, will have to look into it.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-give-players-objectives.18249/update?update=243829

**Comment by kaalitoukka** [comment]
[Uusi tekstiasiakirja.txt](https://github.com/JCulley/ProQuests-Documentation/files/2425124/Uusi.tekstiasiakirja.txt)
