### ISSUE TITLE
Numeric Placeholders - Default value

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#195]
Hello JCulley,
I would like a locale line to change the default "N/A" on the placeholders by another thing, I want to put 0.
If we take the example of the placeholder **%proquests_progress_{identifier}%**, when you don't have the quest specified, the placeholder is returning "N/A", that is what I would like to edit.
Thanks !

**Comment by JCulley** [comment]
I don't see the specific need for this as its more clear to the end user that its not active in anyway by providing "N/A". There's no need for the plugin to provide a statistic that is in fact invalid as the quest isn't even in progress.

**Comment by Melowelsa** [comment]
I understand, but when we use the placeholder to make a progress like "5/20 Blocks", with the N/A it look weird : "N/A/20 Blocks", that's why I would like to be able put something different of "N/A".

**Comment by JCulley** [comment]
*Edit* - I understand the request, however most of the functionality would have to be changed for any quest utilizing these specific identifier based placeholders. This would be a fairy large change simply for a very basic cosmetic purpose.
