### ISSUE TITLE
Permission not working - proquests.active.{amount}

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#196]
**➤ Spigot account :**
➥ https://www.spigotmc.org/members/__melowelei__.378949/

**➤ Plugin version :**
➥ 2.1.0.1-beta, build #378949

**➤ Spigot Version :**
➥ git-Spigot-596221b-86aa17f (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**➤ Link to log file :**
➥ https://hastebin.com/iwagehejit.md

**➤ Addition Information :**
➥ The permission "proquests.active.{amount}" is not working, I added "proquests.active.3" to my players, but he can have 4 quests.
> Steps to reproduce:
> 1. Add the permission proquests.active.3 to the player.
> 2. Make him trying to join more than 3 quests (4).
> 3. You notice you are able to have 4 quests active, but the permission should allow you for 3 max.

**Comment by JCulley** [comment]
Please provide your config.yml in a pastebin or plain text format

**Comment by Melowelsa** [comment]
I just took a look at the config as you told me to send it, and seen we can set the max actives quests (quest_settings.max_active), so that mean if I set 3 quests and the permission on the player is "proquests.active.5", he will be able to bypass this setting ?

**Comment by JCulley** [comment]
Correct, I assumed that was your issue and I added some clarification on the permissions page as it wasn’t 100 percent clear. The permission amount must be great than that defined in the config, if it is less than it the default config max active is used.
