### ISSUE TITLE
Plugin doesnt work

### ISSUE THREAD

**Issue by CancerCell** [JCulley/ProQuests-Documentation#197]
**Spigot account** - {  https://www.spigotmc.org/members/schiller.329403/1  }
<br>

**Plugin version** - {  2.0.7.1  }
<br>

**Spigot Version** - {  This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)  }
<br>

**Link to log file** - {  https://pastebin.com/G8FiNC8U  }
<br>

**Additional information** - {insert here}
It just doesnt work at all, like i get errors and stuff cant make any quests work properly
<br>

**Comment by JCulley** [comment]
This has already been resolved, either downgrade/remove holographic displays or use the beta #194
