### ISSUE TITLE
PLACEHOLDER_QUEST

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#198]
**➤ Spigot account :**
➥ **https://www.spigotmc.org/members/__melowelei__.378949/**

**➤ Plugin version :**
➥ 2.1.0.1-beta, build #378949

**➤ Spigot Version :**
➥ git-Spigot-596221b-86aa17f (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**➤ Link to log file :**
➥ **https://hastebin.com/imaxusorik.md**

**➤ Addition Information :**
➥ I'm trying to create a PLACEHOLDER_QUEST of %player_seconds_lived%, so I would like to make the quest finished when the player will live 60 seconds, but it's saying me "[ProQuests] Unable to load the 'live-quest' quest as it is not an eligble configuration", the quest : **https://hastebin.com/ewolimufib.makefile**

**Comment by JCulley** [comment]
Hi, this is not an error with the plugin use the in-game editor if you don’t know how to create the quest properly. I’ll leave it open if someone else wants to guide you through your configurations.

**Comment by Melowelsa** [comment]
I used the in-game creator and seen it's a different configuration, now it's working perfectly, thanks !
