### ISSUE TITLE
Version missmaches

### ISSUE THREAD

**Issue by CancerCell** [JCulley/ProQuests-Documentation#199]
Lazy to do all that stuff. 
Just errors cuz of versions missmach

**Factions UUID** Newest FUUID ver is **1.6.9.5-U0.2.2-b116**

**HOLOGRAPHIC_DISPLAYS** Newest version is **v2.3.0**

**PLACEHOLDER_API** your version:2.9.1. // newest ver: **2.9.2**

 **Vault** yours 1.5.6-b49 // newest **1.7.1**

**Comment by JCulley** [comment]
Will look to update these for the next release.

**Comment by JCulley** [comment]
These have been updated and the changes will be included in the next release.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-1-give-players-objectives.18249/update?update=246256
