### ISSUE TITLE
SlotMachineGUI - External quest type (WIN)

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#200]
➤ **Spigot account :**
➥ **https://www.spigotmc.org/members/__melowelei__.378949/**

➤ **Feature Requested :**
➥ I would like I new external quest type for the plugin **[SlotMachineGUI](https://www.spigotmc.org/resources/slotmachinegui-1-9-1-12.57142/)**, win X time at the SlotMachine.

**Comment by JCulley** [comment]
Seems how it is a premium resource I'll have to contact the author to see if there is any event API built in, and additionally if they would be willing to provide me a copy.

**Comment by JCulley** [comment]
Believe I had reached out to the developer at the time and never got a response. Going to close this as it’s rather old.
