### ISSUE TITLE
PLACEHOLDER_QUEST | Not working correctly !

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#206]
➤ Spigot account :
➥ **https://www.spigotmc.org/members/__melowelei__.378949/**

➤ Plugin version :
➥ 2.1.0.1-beta, build #378949

➤ Spigot Version :
➥ git-Spigot-596221b-86aa17f (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

➤ Information :
➥ I'm trying to make a quest using the PLACEHOLDER_QUEST, but when I start the quest, I can finish it automaticaly after 15 seconds, but do not have reached the value of the specific placeholder.
➥ Quest configuration : **https://hastebin.com/opedafuvuk.makefile**

**Comment by JCulley** [comment]
Please provide additional information, such as evidence showing what the placeholder value is returning using /papi parse \<placeholder\>, additionally you must update to the latest plugin version before I will provide any additional support. Lastly you must provide a plaintext version of your entire log from startup.

**Comment by Melowelsa** [comment]
**[Papi parse](http://image.noelshack.com/fichiers/2018/41/5/1539295748-erg.png)**
latest.log : **https://hastebin.com/oqosupiqiv.md**

**Comment by Melowelsa** [comment]
Any news ? I added the informations you requested, but still no reply.

**Comment by JCulley** [comment]
I currently have a lot going on and don’t have adequate time to investigate every issue at the moment. It will be looked into when I get a chance.

**Comment by JCulley** [comment]
Ive discovered the issue and it has been fixed for the next release.

**Comment by Melowelsa** [comment]
Thanks! Do you have an estimated date for the release?

**Comment by JCulley** [comment]
Sorry no, I’ve been trying to address issues I’ve been discovering along the way which apparently no one seems to be reporting so it’s taking longer than expected.

**Comment by Melowelsa** [comment]
Still not any news for an update ?

**Comment by JCulley** [comment]
Still some small changes that need to be made, I cannot provide an ETA as I have other responsibilities which are of higher priority.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-1-give-players-objectives.18249/update?update=251793

**Comment by Melowelsa** [comment]
@JCulley Since your fix, I have got another problem, that for I still reply there instead of recreate an issue, as I have the exact configuration except the new ProQuests build.
So imagine you have set the placeholder to 100 but the player have only 95, that mean he can't finish the quest.
There is a bug to finish the quest even if you don't have enought of the placeholder : 
1. Start a placeholder quest you wouldn't be able to finish,
2. Leave the quest and wait something like 15-20 seconds,
3. The quest will be finished.

**Comment by Melowelsa** [comment]
@JCulley

**Comment by JCulley** [comment]
You redescribed the exact same issue? I'll take another look however in my testing everything appeared to work fine.

**Comment by JCulley** [comment]
The quest would complete immediately if you failed any of the eligibility checks this includes if the unique identifier of the quest doesn't match. So by my best guess this was due to the fact multiple people had the quest active. This would mean that it would work in some cases but not others which is why my testing didn't have the same result.

Regardless this has been fixed.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-25-off-holiday-sale-give-players-objectives.18249/update?update=254155
