### ISSUE TITLE
Database | Console Error (spam)

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#207]
➤ **Spigot account :**
➥ **https://www.spigotmc.org/members/__melowelei__.378949/**

➤ **Plugin version :**
➥ 2.1.0.1-beta, build #378949

➤ **Spigot Version :**
➥ git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

➤ **Latest.log file :**
➥ **https://hastebin.com/zenifuyazo.md**

➤ **Information :**
➥ The console is spamming an error about the database, but the plugin look like to work correctly, so I can't give you more information about this error.
➥ Error : **https://hastebin.com/vitenicahi.md**.

**Comment by JCulley** [comment]
Please actually read the log before opening an issue. It clearly states that your database may be corrupt which is not a ProQuests issue.

**Comment by Melowelei** [comment]
How can you say it's not a ProQuests issue ? I'm using the SQLite file (database.db) and never edited it, I restarted the server and got this problem.
