### ISSUE TITLE
Version Mismatch | AutoSell

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#208]
The plugin **[AutoSell](https://www.spigotmc.org/resources/autosell.2157/)** is on latest version 1.8.6, but ProQuests still look into the version 1.8.1 (**[Error](https://hastebin.com/obetogexuh.cs)**).

**Comment by JCulley** [comment]
Please follow the guidelines.

**Comment by Melowelsa** [comment]
➤ **Spigot account :**
➥ **https://www.spigotmc.org/members/__melowelei__.378949/**

➤ **Plugin version :**
➥ ProQuests : 2.1.0.2-beta

➤ **Version mismatch :**
➥ AutoSell in ProQuest : 1.8.1
➥ AutoSell latest : 1.8.6

➤ **Spigot Version :**
➥ git-Spigot-596221b-86aa17f (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

➤ **Logs :**
➥ Startup : **https://hastebin.com/oqosupiqiv.md**
➥ Error : **https://hastebin.com/anuboteray.cs**

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-1-give-players-objectives.18249/update?update=251793
