### ISSUE TITLE
ProQuest error ShopGuiPlus

### ISSUE THREAD

**Issue by W4RTR1X** [JCulley/ProQuests-Documentation#209]
Hi,
I have got a problem with the plugin ProQuest , when i try to use shopguiplus placeholders i have got an error like that : 
http://image.noelshack.com/fichiers/2018/42/1/1539598263-t.png
Can you help me to solve my error ?
Sorry for my english x)

**Comment by JCulley** [comment]
Please update this to follow the guidelines.

**Comment by JCulley** [comment]
Closing as you have provided no additional information.
