### ISSUE TITLE
Not Work - Need Help 

### ISSUE THREAD

**Issue by Rayork** [JCulley/ProQuests-Documentation#210]
Spigot testing in 1.13.1 / 1.13 / 1.12

https://pastebin.com/w9zNYdVr

The plugins do not work. Yet I put them in the file the server detects it when I do "/ plugin" but when I type the command "/ proquests" or "/ creator" Nothing. 
Help !

I try only plugins proQuests again nothing.
I try i create new server, again nothing.

Server options:
Java 8
Use Spigot
Test with other plugins recommended, again nothing

**Comment by JCulley** [comment]
Close your dispute and remove your review or you will not get support.

**Comment by Rayork** [comment]
This was already done

**Comment by JCulley** [comment]
The dispute is still open so no you will not be receiving support until it is closed.

**Comment by Rayork** [comment]
is close

**Comment by JCulley** [comment]
This is the last comment I will post until you actually close it. No you have not closed the dispute.

https://gyazo.com/8182734e74dbddf5dd82a4cb08117468

**Comment by JCulley** [comment]
Closing as the dispute is still not resolved.
