### ISSUE TITLE
OFF_HAND cannot be resolved or is not a field

### ISSUE THREAD

**Issue by TheKillHDmc** [JCulley/ProQuests-Documentation#212]
**Spigot account** - TheKillHD
<br>

**Plugin version** - v2.1.0.2-beta
<br>

**Spigot Version** - patched_1.10.2.jar:git-Paper-916.2
<br>

**Link to log file** - https://pastebin.com/dKi4NJMA
<br>

**Addition Information**
I have updated the plugin to the last version and after a plugman load i got this issue

**Comment by JCulley** [comment]
Plugman reloads are unsupported as it can cause various errors, and compatability with Paper Spigot is not guaranteed. From the looks of it appears as though the Paper Spigot version you are using doesn’t support the off hand enum. If you can reproduce this issue on an official non fork Spigot version while utilizing proper restarts and additionally following the guidelines to include a link to your Spigot account, and your **ENTIRE** log file then I’ll look into it, but for now I’m closing this issue.
