### ISSUE TITLE
Turned automatically to red. Not working.

### ISSUE THREAD

**Issue by NeximaOz** [JCulley/ProQuests-Documentation#213]
➤ Spigot account :
➥ https://www.spigotmc.org/members/nexima.40441/

➤ Plugin version :
➥ 2.1.0.2-beta and 2.0.7.1 (I try both versions)

➤ Spigot Version :
➥ 1.12.1

➤ Information :
➥ When server opened firstly proquest work correctly no any error etc. But 2 min later turned to automaticaly red in plugins list. No any error no any message. When try run quest, proquest command etc nothing. Im try proquest different versions but same.

https://prnt.sc/l9ijwz

**Comment by JCulley** [comment]
1. This does not follow the guidelines. Provide your entire log file and a detailed analysis, a simple statement will not suffice.

2. You have already been blocked for a reason, why should I even provide you support?

**Comment by NeximaOz** [comment]
**1.** Server Log:
https://hastebin.com/ujusatemey.md

**2.** I don't know why i'm was getting blocked on github. Maybe i don't know github rules for proquests. But i think i do not wrong thing. I was just want help. Maybe i was open two or three open issue. Sorry for this.

**Detailed Analysis:**
Im opened server and everything seems good. I'm check logs no any error. Im joined the server and proquests correctly work. Example /quest etc. But 2 or 3 min later not work proquests commands. Just nothing. And im check the "/plugins" list Proquests showing red. Im again check console and logs again no any errors just nothing. Just this. Why ProQuests stopping and not work i no idea.

**Note:**
Yesterday i was updated this plugins;
- Jobs
- Vault
- TradeMe
- MythicMobs
- FastAsyncWorldEdit

**Comment by JCulley** [comment]
Until you remove your review you will not receive support.

**Comment by NeximaOz** [comment]
Deleted.

**Comment by NeximaOz** [comment]
My problem still continue with latest version.
