### ISSUE TITLE
COMPLETION_QUEST issue

### ISSUE THREAD

**Issue by weronicamc** [JCulley/ProQuests-Documentation#214]
**Spigot Account**
> https://www.spigotmc.org/members/weronica.83130

**Spigot account**
> weronicamc

**Plugin Version**
> 1.5.1.6.3

**Spigot Version**
> git-Spigot-99c2a37-3819f8d (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Log File**
> https://pastebin.com/jamtiPVF

**Addition Information**
> I created Completion quest
> I added lines to Required quests correctly
> I saved quest
> I reedited quest and lines into Required quests are empty
> I tryed to edit it in file, but quest didnt react - I completed required quests and copletion quest didnt complete.

**Additional Media**
> Link to gif: https://imgur.com/DqeODsJ

**Comment by JCulley** [comment]
As is stated support will not be provided for old versions. This may have been a very old issue (I can’t recall), so I’m closing this issue as just testing the creator now there are no issues in 2.1.1.

**Comment by weronicamc** [comment]
Ok, I try it 👍

**Comment by JCulley** [comment]
While on the page to add items once you hit “e” or whatever key you have the inventory set to it closes and reopens the current page. This is not an issue of any kind.
