### ISSUE TITLE
I cant create menu in in-game editor

### ISSUE THREAD

**Issue by weronicamc** [JCulley/ProQuests-Documentation#215]
**Spigot Account**
> https://www.spigotmc.org/members/weronica.83130

**Spigot account**
> weronicamc

**Plugin Version**
> 2.1.1

**Spigot Version**
> git-Spigot-99c2a37-3819f8d (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Log File**
> https://pastebin.com/pynuHDM7

**Addition Information**
> I use command /quest menu create "name of menu"
> I click on Next Page - nothing happens
> I cant save menu
> I click on settings for Menu Slots
> I set 1 quest to 1 slot
> I cant click to other slots
> I cant go anymore back to editor and save menu
> I try to use key ESC - nothing happens and my chat freeze
> I used command /creator resume "name of menu"
> Chat message - I cant resume any menu.

**PS.**
> I can create menus without in-game editor like file yml.

> I know about issues with version of plugins in log, but I cant update it to new version, because they are not compatible with my other plugins on version 1.12. I should update every server plugins and spigot to version 1.13, but it s not in my to-do list now. I m waiting to update other plugins.

**Comment by JCulley** [comment]
I’m sorry but from your description I don’t understand what the issue is, I would need a video or gif of some sort explaining the actual issue. Additionally I need your entire log file, not just a portion of it.

**Comment by weronicamc** [comment]
> I’m sorry but from your description I don’t understand what the issue is, I would need a video or gif of some sort explaining the actual issue. Additionally I need your entire log file, not just a portion of it.

https://pastebin.com/ZzjV0sj3

**Comment by weronicamc** [comment]
@JCulley GIF :) https://imgur.com/WbS7sw2

**Comment by JCulley** [comment]
While on the page to add items once you hit “e” or whatever key you have the inventory set to it closes and reopens the main page. This is not an issue of any kind.

**Comment by weronicamc** [comment]
> While on the page to add items once you hit “e” or whatever key you have the inventory set to it closes and reopens the main page. This is not an issue of any kind.

Solved :) thank you for help 👍 thank you for your time 🥇
