### ISSUE TITLE
ProQuests version mismatch Citizens, Vault, Worldguard

### ISSUE THREAD

**Issue by darkboomba** [JCulley/ProQuests-Documentation#220]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/darkboomba.268225/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.2
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - Paper version git-Paper-473 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/Mv5W9Si3
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - ProQuests has version mismatches with Citizens, Vault and World Guard.
I'm running the latest version of all three of these plugins. I even tried Vault 1.6.7 which was requested in ProQuests error. But even this would end in a version mismatch. Can you add support for a specific plugin version and all the versions above?
<br>

**Comment by JCulley** [comment]
> Spigot account - {insert here}

Please provide all requested information.

**Comment by darkboomba** [comment]
> > Spigot account - {insert here}
> 
> Please provide all requested information.

Oops, fixed.

**Comment by JCulley** [comment]
Your log file clearly states your using 2.1.1.1 and not 2.1.1.2. Regardless here's a simple analysis:

1. **Vault** - There is clearly something wrong with the naming convention of the version you downloaded as ProQuests looks for an exact match and this is provided in your log 

> [Vault] Loading Vault v1.6.7-b${env.TRAVIS_BUILD_NUMBER}

So in turn this is not a mismatch.

2. **Citizens** - Its a minor release on their end and I don't believe there are any API changes, I'll still update it anyways.

3. **WorldGuard** - It's a mismatch due to the subsequent build number (as I mentioned ProQuests looks for an exact string match), I'm not going to update ProQuests for every build. The version is still the same.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-25-off-holiday-sale-give-players-objectives.18249/update?update=258366
