### ISSUE TITLE
ProQuests - Error Passing InventoryClickEvent when creating a Tournament Quest Type through In-game editor

### ISSUE THREAD

**Issue by TrueCombat** [JCulley/ProQuests-Documentation#226]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/basiq.280403/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - ProQuests v2.1.1.2
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/XcALPb3K
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - When I attempt to create a tournament quest by clicking on the Tournament block icon in the in game editor it gives me the following error:
[Server thread/ERROR]: Could not pass event InventoryClickEvent to ProQuests v2.1.1.2
org.bukkit.event.EventException
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
Going to have to look into it.

**Comment by TrueCombat** [comment]
Would you be willing to give me a config example since there currently isn't any documentation on Tournament quests that I can test out the tournament plugin?

**Comment by JCulley** [comment]
I don’t have any example configurations to provide you. You had already asked me this and I had explained this already.

**Comment by TrueCombat** [comment]
Maybe I'm not making my self clear on what I mean by "Config Example".  I just would like to see the syntax for a tournament quest in the config file -- A simple snippet  image of a quest with tournament attributes would do.  Unless the configuration of these types of quests has nothing to do with the config, and its all done internally within the plugin.  

![image](https://user-images.githubusercontent.com/45925768/50127364-753e0880-0236-11e9-8d06-668d2846b57b.png)

**Comment by JCulley** [comment]
No I understand perfectly, however I don’t have any formatted tournaments configurations already created and I’m not going to whip one together just for this. I am however looking to fix the issue at hand with the creator.

I appreciate your understanding.

**Comment by TrueCombat** [comment]
I see that a fix has been implemented -- how long do you think it will be till the next release?

**Comment by JCulley** [comment]
It will be before the end of the year for sure, there are some other fixes and changes I’m working on. Can’t give exact details seems how the holidays are upon us and time is limited.

**Comment by TrueCombat** [comment]
Gotcha -- thanks!

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-25-off-holiday-sale-give-players-objectives.18249/update?update=258366

**Comment by TrueCombat** [comment]
Great -- the GUI issue is now resolved.  Although, I still seem to be having a bit of a problem getting everything working correctly -- There isn't documentation for tournament quests, and the setup with the GUI isn't going so well for me-- Could you please provide me with 1 sample of a working tournament for this plugin?  I've waited pretty patiently for this to work (I've owned these two plugins for years now) There is an example image of a tournament right on the plugin page-- could you just copy and paste the code from that example?
![image](https://user-images.githubusercontent.com/45925768/50547443-0631be00-0bff-11e9-8b97-3bc95ecc105c.png)
