### ISSUE TITLE
Save on quit feature for BungeeCord servers

### ISSUE THREAD

**Issue by 9hrack** [JCulley/ProQuests-Documentation#228]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details**
for BungeeCord server, let's suppose a player switches from server A to server B.

to perfectly share player data in both servers,
the A server need to save the player data to database when a player quits.
and B server need to load when a player joins

so I need an option that can enable/disable 'save-on-quit' feature.

**Comment by JCulley** [comment]
This is already in the plugin so I don’t understand why you opened this issue.
