### ISSUE TITLE
How to create quest package with addon Proquest Packages?

### ISSUE THREAD

**Issue by weronicamc** [JCulley/ProQuests-Documentation#234]
**Spigot Account** - https://www.spigotmc.org/members/weronica.83130/

**Plugin version** - 2.1.1.3

**Spigot Version** - git-Spigot-99c2a37-3819f8d

**Additional information**
I dont understand how to create packages with addon and I didnt find any info on wiki or on spigot wiki, nowhere.

Thank you for your help.

**Comment by JCulley** [comment]
An example configuration can be found in the config.yml. Regardless the format will more than likely be changed in the next coming update so I don’t plan on updating anything here until then.

**Comment by weronicamc** [comment]
Ok I set up it, but then I tryed command /quest packages start and answer was
"The package identifier does not exist"

My config: https://pastebin.com/YbkMqBfY

**Comment by weronicamc** [comment]
Sry, but I have still problem, I dont understand how I can start package. Can you help me? Thank you @JCulley .
