### ISSUE TITLE
Update WorldGuard to beta 3

### ISSUE THREAD

**Issue by Disorbs** [JCulley/ProQuests-Documentation#237]
**Spigot account** - https://www.spigotmc.org/members/disorbs.38572/
<br>

**Plugin version** -
> ProQuests v2.1.1.3.1
> WorldGuard 7 Beta 2 (latest from bukkit)
<br>

**Spigot Version** - Paper Spigot 1.13.2
<br>

**Link to log file** - https://hastebin.com/exetaqosag.md
<br>

**Additional information** -
> 1. Start the break quest default example quest
> 2. break a block at spawn
> 3. sends an error
<br>

**Error Log** - https://hastebin.com/hupurosala.pl

**Comment by JCulley** [comment]
They must’ve removed/changed the method declaration. If you want proper functionality downgrade your WorldGuard to beta 1 as that is what ProQuests was built against.

I’ll have to look into this to see what changes they have made.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-20-off-spring-sale-give-players-objectives.18249/update?update=270376
