### ISSUE TITLE
ProQuest doesn't work well

### ISSUE THREAD

**Issue by Ragnarak123** [JCulley/ProQuests-Documentation#238]
Spigot User Link: https://www.spigotmc.org/members/ragnarak.127214/

PaperSpigot Version: Paper version git-Paper-1595 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Plugin Version:  ProQuests v2.1.1.3.1

Full Log:  https://hastebin.com/dizaduzowu.md

Error Log: https://hastebin.com/nezarekeki.md

**Comment by JCulley** [comment]
It clearly states you are not using compatible dependency versions. Use the supported versions.
