### ISSUE TITLE
Menu configuration not working

### ISSUE THREAD

**Issue by DragonSurvival** [JCulley/ProQuests-Documentation#240]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - Kiruzx
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> 2.0.9.0.1

**Plugin version** - 2.1.1.3.1
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)

**Spigot Version** - git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/pasfhs.bash

**Link to log file** - https://hastebin.com/ogehokunot.md
<br> 

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - MY MENU WAS NOT OPERATED IN THE LATEST VERSION -> https://hastebin.com/pinafekuxa.bash
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - https://hastebin.com/pinafekuxa.bash
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
Gonna need more information as all you’ve provided is a menu YAML file with no explanation, what am I supposed to do with that?

Additionally you never provided a direct link to your Spigot account

**Comment by DragonSurvival** [comment]
Can you edit my MENU file?
Let it work on the latest version

SPIGOT: https://www.spigotmc.org/members/kiruzx.228517/

**Comment by JCulley** [comment]
I don’t write your configurations, that’s your job. It’s clearly seen in your log you have a YAML formatting error so use the in-game editor to manage your menus and you won’t have any formatting issues.

**Comment by DragonSurvival** [comment]
Okay thanks you!
