### ISSUE TITLE
PLACEHOLDER_QUEST | Check-Time Configuration

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#242]
➤ **Spigot account :**
➥ **https://www.spigotmc.org/members/__melowelei__.378949/**

➤ **Feature Requested :**
➥ I would like you to add a check-time configuration for the PLACEHOLDER_QUEST ! So we would be able to configuration each how much time the PLACEHOLDER_QUEST check if the player have the requiered value or not.

**Comment by JCulley** [comment]
The update delay is based off the ProQuests update event which is triggered every X seconds defined in the config.yml as the “update_interval”. So what you’ve described is already possible.
