### ISSUE TITLE
It automatically start all quests when I join

### ISSUE THREAD

**Issue by Meldiron** [JCulley/ProQuests-Documentation#247]
I cant find option to disable this in config but for some reason when I join server it starts all quests at once.
It results in getting a lot of spam in chat, can I disable it?

**Comment by JCulley** [comment]
Stop opening so many issues or I will be forced to revoke your access to do so. Please read the documentation and attempt to solve issues on you own. If you open an issue it must follow the guidelines which are for errors or suggestions, with the required information.

**Comment by Meldiron** [comment]
I didnt find answer in wiki, thats why I asked.. 50% of documentation is missing and you dont want to give me answers about how it works. It means its useless for me so I want my 20$ back.

**Comment by JCulley** [comment]
Clearly stated on this page 
https://github.com/JCulley/ProQuests-Documentaion/wiki/Commands-And-Permissions , so take a second and try to solve it yourself before immediately asking for help. You purchased software any support provided is at my own discretion. I’m happy to investigate errors however I’m not here to spend my time adddresing simple configuration issues which are documented.
