### ISSUE TITLE
BREED_QUEST throws error

### ISSUE THREAD

**Issue by Meldiron** [JCulley/ProQuests-Documentation#252]
**Spigot account** - https://www.spigotmc.org/members/meldiron.92826/

**Plugin version** - v2.1.1.3.1

**Spigot Version** - This server is running Paper version git-Paper-486 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Link to log file** - https://pastebin.com/YCDeTuFf
<br>

**Additional information** - Pretty simple to simulate - Create quest, set type to BREED_QUEST, set amount to 5, dont set any requred/allowed mobs (so all are allowed). Try to breed sheeps, wait 5 secs and error will appear in console
<br>

**Comment by JCulley** [comment]
This won't affect the actual progression of the quest but an extra validation has been added to avoid the NullPointerException for the next version

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-20-off-spring-sale-give-players-objectives.18249/update?update=270376
