### ISSUE TITLE
Coco Beans material not working properly

### ISSUE THREAD

**Issue by Meldiron** [JCulley/ProQuests-Documentation#253]
**Spigot account** - https://www.spigotmc.org/members/meldiron.92826/

**Plugin version** - v2.1.1.3.1

**Spigot Version** - This server is running Paper version git-Paper-486 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Link to log file** - 
Part1: https://pastebin.com/r0P1BGBJ
Part2: https://pastebin.com/yQmg2Qxq

**Additional information** - I tried both manual and in-game creator setup but OBTAIN_QUESTS with COCO_BEANS doesnt work (other materials like CARROT or WHEAT does). Here is my quest yml file: https://pastebin.com/jc4cyY7T

**Comment by JCulley** [comment]
If your issues are related to specific materials you are more than likely using incorrect non valid materials. The plugin checks the materials defined in Spigot, so please stop opening these issues when they are in no way related to ProQuests and rather how you are configuring the quests.

**Comment by Meldiron** [comment]
COCOA_BEANS is fully valid material name in spigot 1.13.2. your in-game editor generated this material name - its still an error report, right?
