### ISSUE TITLE
An Internal error occurred while attempting to perfom this command.

### ISSUE THREAD

**Issue by KLUnknOwN** [JCulley/ProQuests-Documentation#254]
I don't think I quite understand how to install or setup this mod> I've only done the mySQL, apparently it won't let me issue any commands not even /proquests. What exactly am I doing wrong to not be able to issue commands?

**Comment by JCulley** [comment]
I have absolutely no clue what this is in reference to. You have given no adequate description or information. Additionally you didn’t follow any of the guidelines so I’m going to go ahead and close this.

**Comment by KLUnknOwN** [comment]
I have resubmitted the issue with all required documentation.
