### ISSUE TITLE
Cannot Issue any commands *Dependency issue, plugin disabled.

### ISSUE THREAD

**Issue by KLUnknOwN** [JCulley/ProQuests-Documentation#255]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: 

**Spigot account** - {ihttps://www.spigotmc.org/members/klunknown.652557/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.3.1}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {spigot-R0.1-e5e5c7c6d43-6430d9c0ba7-e167e549afd.jar (MC 1.13.2) }
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {Pastebin wasn't working so I'll paste it here. The issue is emboldened.}

[2019-02-21 22:08:08] [INFO]: Preparing spawn area: 100%
[2019-02-21 22:08:08] [INFO]: Time elapsed: 3194 ms
[2019-02-21 22:08:08] [INFO]: [ProQuests] Enabling ProQuests v2.1.1.3.1
[2019-02-21 22:08:08] [INFO]: [ProQuests] Running build #652557[2019-02-21 22:08:08] [INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[2019-02-21 22:08:08] [INFO]: [ProQuests] Loading external plugin hooks....
[2019-02-21 22:08:08] [INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=[2019-02-21 22:08:08] [INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
_[2019-02-21 22:08:08] [INFO]: **[ProQuests] Disabling ProQuests due to a severe dependancy incompatibility.
[2019-02-21 22:08:08] [INFO]: [ProQuests] Please use the supported dependancy versions for ProQuests.**_
[2019-02-21 22:08:08] [INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[2019-02-21 22:08:08] [INFO]: [ProQuests] Disabling ProQuests v2.1.1.3.1
[2019-02-21 22:08:08] [INFO]: Server permissions file permissions.yml is empty, ignoring it
[2019-02-21 22:08:08] [INFO]: Done (5.151s)! For help, type "help"
[2019-02-21 22:08:08] [INFO]: UUID of player KiddLuthor is b1a5a4de-211b-42cb-954e-b476345e25b1

<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - 

I have figured out that the reason i cannot issue commands or get this mod started is because of the "severe dependency issue" which is disabling the plugin as soon as the server starts, what exactly do I need to do to get this solved? Thanks in advance.
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
Other issues have already been opened referencing the same oversight.

#239 
#244 

I thought it was pretty clear as it asks you to use “supported dependency versions” but I suppose I’ll somehow have to make it even more clear in a future update.
