### ISSUE TITLE
The plugin is disabled with us please help.

### ISSUE THREAD

**Issue by xXjojojXx** [JCulley/ProQuests-Documentation#257]
I bought your plugin and grabbed it on the server after the restart, the plugin was shown as red with / plugin I have taken a picture I have uploaded the loco the problem is it is disabled the plugin how do i activate that it is so red chatting with / plugin Sorry for my bad english use Google translator no matter what command I use the plugin skin me immediately error message purely in the console from the server please fastest possible help.
We use spigot version 1.13.2.

https://www.directupload.net/file/d/5387/3o8waohu_png.htm

https://www.file-upload.net/download-13532140/latest.log.html

**Comment by JCulley** [comment]
I will not say it again, I understand there may be a language barrier howveer it doesn’t seem as though you are attempting to follow them whatsoever. If you will not follow the guidelines then do no open any issues.
