### ISSUE TITLE
ProQuests disabled in 1.13.2

### ISSUE THREAD

**Issue by 4NxT98** [JCulley/ProQuests-Documentation#258]
Hello dear Dev,

i have a massive problem.
If i start my server with die ProQuest Plugins, the console give me following error message:

*** ProQuests ***
[ProQuests]: Enabling ProQuests v2.1.1.3.1
[ProQuests]: Running build #547748
[ProQuests]: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ProQuests]: Loading external plugin hooks....
[ProQuests]: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ProQuests]: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ProQuests]: Disabling ProQuests due to a severe dependancy incompatibility.
[ProQuests]: Please use the supported dependancy versions for ProQuests.
[ProQuests]: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ProQuests]: Disabling ProQuests v2.1.1.3.1

*** Spigot Version ***
git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Can you help me?

Much Love,
STOOKA.

**Comment by JCulley** [comment]
This does not follow the guidelines, if you will not follow the guidelines do not open an issue. I cannot help you if you don’t provide sufficient information to do so.

**Comment by 4NxT98** [comment]
What the fuck?!
I only ask you for help.

Quote: "If you have any issues with the plugin you will contact me by opening a GitHub issue and I will help you with your issue before you post a negative review stating something like "The plugin doesn't work"."

**Comment by xXjojojXx** [comment]
At least I'm not the only one who has the problem I get exactly the same copy button message if you do not want to help then there's a bad review.

**Comment by JCulley** [comment]
Follow the guidelines, it’s simple. 
https://github.com/JCulley/ProQuests-Documentation/issues/new?template=error-report.md
