### ISSUE TITLE
Using incompatible dependancies

### ISSUE THREAD

**Issue by xXjojojXx** [JCulley/ProQuests-Documentation#259]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/xxminixx.547748/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {ProQuests v2.1.1.3.1 Running build #547748 }
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://hastebin.com/eyohumotib.md}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - { When the server starts, it indicates that the plugin is not compatible with the current version of the server, and thus is turned off.}
<br>

**Comment by xXjojojXx** [comment]
And how are you now?

**Comment by JCulley** [comment]
This is not an issue and has been answered multiple times now. If you are using a dependancy plugin (not Spigot related as the log message states) which has made significant API changes the plugin will be unable to load due to incompatibilities to prevent further errors while running. The most common example is PlaceholderAPI.

#255 
#239 
#244

Additionally I don't appreciate the additional response because I didn't have time to respond to you within an hour. Considering I am under no obligation to provide support be glad I reply as quickly as I do.
