### ISSUE TITLE
Translate quests into German

### ISSUE THREAD

**Issue by xXjojojXx** [JCulley/ProQuests-Documentation#260]
We wanted to ask if there is a possibility to translate completely into German is also possible if it was possible Quest, menu completely in German

And thanks again for the help.

**Comment by JCulley** [comment]
Every messsge is configurable apart from the individual quest creators. So this is already possible.

**Comment by xXjojojXx** [comment]
When we have finished the translation we will send you the files.
We would like to help you with the German translation of your project if you accept that, you just have to let me know^^

**Comment by JCulley** [comment]
Yea sure thing if you want to provide the locale.yml I will create a separate section on the wiki dedicated to any community generated locale files. I’m sure any other non-English buyers will appreciate that :)
