### ISSUE TITLE
ProQuests Packages [Add-On] ERROR

### ISSUE THREAD

**Issue by DragonSurvival** [JCulley/ProQuests-Documentation#261]
**Spigot Account**
Provide a direct clickable link to your user profile.
> 

**Spigot account** - Provide a direct clickable link to your user profile.
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.3
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** Paper version git-Paper-1606 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://hastebin.com/yimomidube.md
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - why went i finish a packages quests in the menu it is not appear complete item it appear at waiting item (that i cant edit). Active, unavailible, availible still normal only complete item that isnt work.
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - link config ProQuests-Packages https://hastebin.com/akutefulet.bash
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
I’m sorry this doesn’t make much sense, additionally you didn’t provide a link to your Spigot account.

**Comment by JCulley** [comment]
No additional information was provided.
