### ISSUE TITLE
Proquests Packages addon menu "error"

### ISSUE THREAD

**Issue by Kiruzx** [JCulley/ProQuests-Documentation#262]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/228517/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - Lastest
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - get-Paper-1606
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://hastebin.com/yimomidube.md
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** -
1/ when join in server, i dont know why all my players auto accept all proquests-packages quests. (image below with note)
2/ when finish a quest in the menu (menu use all proquests-packages quest) it doesnt not appear with complete icon it blank that slot when click it, it will send refesh time message.
~ Menu config: https://hastebin.com/oviciqifuz.bash
~ proquests-package config: https://hastebin.com/keboguditu.bash
~ extra log with spigot trigger error:  https://hastebin.com/ebajiduxum.makefile
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - https://imgur.com/a/ROtlyaX
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
1) Read the permissions section on the wiki.

2) I do not understand what you are trying to say, additionally your provided media and the config files provided do not make it any more clear. I don’t understand why you attached a log message stating that you provided a null action when that has nothing to do with me?

**Comment by Kiruzx** [comment]
2. It said contact author plugin "Please notify author of plugin causing this execution to fix t
his bug! see: http://bit.ly/1oSiM6C" and null message from proquests plugin so i think i need to let you know.
1. Checked thanks
3. extra info for 2. I mean when ever i finish a quest. That quest does not appear with complete item on menu it just blank at that slot. The third picture is when i have not do the quest. And the second one is when i finish the quest. It does not appear with complete item like in config, it just blank

**Comment by JCulley** [comment]
I already stated you provided a null action, just because you configured it with an invalid action doesn’t mean I have any action to take. This is only a warning provided by Paper Spigot, but as I have stated has nothing to do with me.

Then the quest is probably in a waiting state, I have absolutely no clue how you have configured your quest so how am I supposed to know what you’ve done?

**Comment by Kiruzx** [comment]
Basic quests ? - here quests config: https://hastebin.com/afibarifop.bash
extra media: when i click to blank complete quests. https://i.imgur.com/No6P0Az.png
----------------
about the auto start i with member is ok but if i have op perm or * it will auto start

**Comment by Kiruzx** [comment]
hello ? @JCulley

**Comment by JCulley** [comment]
The link you have provided contains no content and additionally I have already stated what is more than likely the cause without having sufficient information. Please do not tag me if I haven’t responded, be patient. Thanks.

**Comment by Kiruzx** [comment]
wait what ? what do you mean "contains no content"

**Comment by Kiruzx** [comment]
i will update a gif later. anyway thank you for trying to understand.

**Comment by Kiruzx** [comment]
https://drive.google.com/open?id=1VXFz2xqx4NLJN4kaCxjGdvz-sQAgPWmK

**Comment by Kiruzx** [comment]
Video about this because i dont know how to explain to you: https://drive.google.com/open?id=1VXFz2xqx4NLJN4kaCxjGdvz-sQAgPWmK

**Comment by JCulley** [comment]
> Then the quest is probably in a waiting state

After watching the video my original statement stands. There is no evidence of any error occurring on a development level and seems highly linked to your configuration. Realistically there’s no much more I can do to investigate with the information you have provided so I advise you try my stated solution.

**Comment by Kiruzx** [comment]
thanks i just recheck again few time with default config and i missing 1 line sorry for wasting your time on this.
