### ISSUE TITLE
Please explain the In-Game Editor

### ISSUE THREAD

**Issue by 4NxT98** [JCulley/ProQuests-Documentation#264]
**Is your feature request a quest suggestion?**
Hello,
can you please update your Wiki informations? Because some users have big problems by creating NPC's ingame, because you dont have any help on your Wiki how to use the this feature.

Please fix!
Stooka.

**Comment by JCulley** [comment]
The in-game editor is rather self explanatory. There’s not much more I can do to explain how to use it.

**Comment by 4NxT98** [comment]
Are you kidding me?
You have nothing listed how to use this! 
This is a scam. Nice support -rep

See this: https://i.imgur.com/42fA2pZ.png
