### ISSUE TITLE
Tournament Challenges don't work + placeholders problems.

### ISSUE THREAD

**Issue by mlegok** [JCulley/ProQuests-Documentation#265]
**Spigot Account**
Provide a direct clickable link to your user profile.
https://www.spigotmc.org/members/mlegok.92886/

**Spigot account** - {insert here}
mlegok
**Plugin Version**
> Latest version

**Plugin version** - {insert here}
ProTournaments latest version
PlaceholderAPI 2.9.2

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Paperspigot 1.12.2 last build.

My problem:
Hi, developer. I needed a plugin for online challenges. To make it work, I had to buy Proquest, and then the addition "Tournaments". Despite the bad reviews, in which you accused users that they do not know how to customize the plugin, I still bought it.
I ran into a lot of problems.
First, in all normal paid plugins, there is an adequate configuration guide. There was absolutely no instruction for the plugin "ProQuests Tournaments", it is empty.
Ok, you said that the installation is simple, I installed the plugin, but the challenges did not work. I used your example config, but it does not work either. Placeholders also do not work.
The console writes that everything is in order.
Please resolve the issue here, otherwise I have to leave a bad review, open a complaint in spigotmc and paypal.

**Additional information** - {insert here}
<br>

Tournament-quest.yml config:
# ======================================================
# 
# ProQuests Version: 2.1.1.3.1 build: 92886
# Created by: JC_Plays_MC
# 
# ======================================================

type: TOURNAMENT_QUEST
duration: 3600
editable: true
repeat_delay: 0
repeatable: false
cancelable: false
command_start: false
cancel_after_timer: true
linked_quest: break
minimum: 1
progress_update: 30
start_date: 2019/03/27 05:00:00
complete_actions:
- '[Title] &aThe tournament has ended!'
progress_actions:
- '[ActionBar] &e&lBlock Tournament Leaders...'
- '[Delay=3][ActionBar] &a1st Place &7- &f%quest_position_1%'
- '[Delay=6][ActionBar] &b2nd Place &7- &f%quest_position_2%'
- '[Delay=9][ActionBar] &e3rd Place &7- &f%quest_position_3%'
- '[Delay=12][ActionBar] &eYour stats &7- &aPosition: &f%quest_position% &7- &bBlocks
  Broken: &f%quest_progress%'
actions:
- '[Delay=5][Title] &cUnplaced ;&7Thanks for participating!'
- '[Delay=5][GiveItem] DIAMOND;32;0'
team: SOLO
command_join: false
check_all: false
disabled: false
join_active: false
require_invite: false
author: f4d935bc-5e2e-38c9-96c7-d59d63cfa68b
required_quests: []
blacklisted_quests: []
allowed_worlds: []
blacklisted_worlds: []
allowed_regions: []
blacklisted_regions: []
complete_permissions: []
start_actions: []
return_actions: []
invite_actions: []
kick_actions: []
cancel_actions: []

Break.yml:
break:
type: BREAK_QUEST
duration: 0
repeat_delay: 0
repeatable: false
cancelable: false
command_start: false
cancel_after_timer: true
total: 500000000

Menu.yml
https://hastebin.com/editumigay.php

I'm also used your "game editor" and it not works. check.
![image](https://user-images.githubusercontent.com/7265575/54924242-60ec6480-4f25-11e9-9b56-a86aef444cce.png)

**Comment by JCulley** [comment]
This doesn’t seem like an “issue” and is rather just you complaining and attempting to force me to provide configuration assistance with the threats of PayPal disputes and bad reviews. You haven’t described any actual issue which I can resolve so there’s not much I can do when a legitmate issue is not reported. I’m going to close this issue now, if you open another issue of this nature simply complaining about the configuration then your access to post issues will be revoked.

**Comment by mlegok** [comment]
What you do with the placeholder? It doesn't work!

**Comment by mlegok** [comment]
I told you, the placeholder doesn't work.. Check the screen.
