### ISSUE TITLE
Advanced Abilities - External Quests

### ISSUE THREAD

**Issue by Kiruzx** [JCulley/ProQuests-Documentation#266]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - Numbers of time use abilities, upgrade class.
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - https://www.spigotmc.org/resources/advanced-abilities-10-off.21983/
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - None

**Comment by JCulley** [comment]
As this is a premium resource I have sent a request to the author requesting a version to utilize for integration. If they are not willing to provide a version for me to utilize as a dependency then I unfortunately cannot add it.

**Comment by JCulley** [comment]
Author will not provide me a copy to test with, so the suggestion will not be added.
