### ISSUE TITLE
Question: What are the required dependencies?

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#269]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/lambsauce.20408/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - latest
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - latest 1.13 paper
<br>

**Question** What are the dependencies for the plugin to be enabled? I have added LuckPerms, Vault and TheNewEconomy. I would recommend adding this to the wiki, I have seen multiple users ask this on the plugin thread.

**Comment by JCulley** [comment]
I have already closed numerous issues in relation to this (maybe look at a number of those). The latest update logs first bullet point was dedicated to this exactly so I don’t understand why you felt the need to open this.

There are no “required” dependencies however ProQuests will attempt to hook in to numerous plugins. If the version is not that which ProQuests references and there are severe API differences which ProQuests cannot resolve it will disable the plugin while clearly outputting the version ProQuests references.

**Comment by ghost** [comment]
I do think using a less hostile, condescending tone and being less strict would help you a lot in regards with upset customers.

But back on topic. I started the server with only ProQuests and it is still being disabled by incompatible dependency. Any ideas?

Server version: Paper version git-Paper-597 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Plugin version: ProQuests v2.1.1.4, build #20408
Server startup log: https://pastebin.com/8F2whvPY
