### ISSUE TITLE
Bug Entity hasPermission 1.7.10

### ISSUE THREAD

**Issue by courat** [JCulley/ProQuests-Documentation#270]
When I start the plugin, with PaperSpigot 1.7.10, I have this issue, and I can't use the plugin at all.
http://prntscr.com/ncrd84
http://prntscr.com/ncrdci

**Comment by JCulley** [comment]
This is not an issue with ProQuests but rather your PaperSpigot version not including the has permission function on entity objects. **ProQuests is only built, compiled, and tested with official Spigot builds. I cannot guarantee any compatibility with forks**

 Additionally you did not follow any of the issue guidelines. If you do not follow them in the future your issue may be closed without a response.

**Comment by courat** [comment]
Why it's insufficient ?
I gave you the error, and you say my paper version is not compatible ?
My version is the latest version of paper based on the latest version of Spigot.
Remove the "support" for 1.7.10 if you're too stupid to fix it.

**Comment by courat** [comment]
Same error with OfFiCiAl vErSiOn oF sPiGoT 1.7.10.
