### ISSUE TITLE
Materials and Data Values

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#271]
https://github.com/JCulley/ProQuests-Documentation/wiki/Materials-and-Data-Values

The Data Values for Log, Coal ore and more don't work.

I tried
-LOG;0
-LOG;1
-LOG;2
-LOG;3
-LOG2;0
-LOG2;1
-log;0
-log;1
-log;2
-log;3
-log2;0
-log2;1
-acacia_log;0
-ACACIA_LOG;0
...

None of them are Working

**Comment by ghost** [comment]
When there is no problem you are probably able to tell how to let the plugin only check for acacia logs an coal ore in a quest. the provided information (https://minecraft.gamepedia.com/Java_Edition_data_values#Data) says

-COAL_ORE;0
-ACACIA_LOG;0 (neither that nor ACACIA_WOOD;0)

but those doesn't work

**Comment by ghost** [comment]
No answer?
I can create a new bug report with all the information you want to get...

but either the provided information in the wiki is false (problably)
or the plugin has a significant bug in all versions

**Comment by JCulley** [comment]
Although you provided absolutely no relevant information (didn’t follow a single guideline) I can tell you with certainty that this has nothing to do with ProQuests. If you don’t configure the plugin with materials for your specific version then it obviously won’t work.
