### ISSUE TITLE
I'm sorry I am bothering you. 

### ISSUE THREAD

**Issue by AtomixCM** [JCulley/ProQuests-Documentation#276]
Can you please guide me through setting up the quest I am trying to set up that will not result in the problem I am experiencing? I don't have any region requirements or item requirements set up for the quest. I literally set up a TOKEN_ENCHANT_BREAK_QUEST with a number value, along with completion actions. Nothing more. Regardless, chunks are going missing, and removing ProQuests is the only remedy.

How do I fix this without having to completely remove ProQuests from my server?

**Comment by JCulley** [comment]
Issues are not for generalized discussions. I do not provide configuration assistance as I wouldn’t have enough time in my days to guide every buyer through step by step. If you don’t want to use the token enchant break quest, use an alternative such as a placeholder quest. That’s the extend of guidance I have time to provide information for. If you have any errors from ProQuests in the future (not config related) then feel free to open an issue.
