### ISSUE TITLE
TokenEnchant and ProQuests Incompatibility

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#277]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/cm_lectric.232281/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.5}
**TokenEnchant version** - {14.0.6-RC3}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {1.8.8}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://hastebin.com/kusocogabe.md}

<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - {iLarge chunks of land are being removed and sent to player inventories when any block is broken EVEN THOUGH there are no quests loaded. I thought the issue was the TOKEN_ENCHANT_BREAK_QUEST, but it is not. The two plugins are generally incompatible. This does not have anything to do with the blocks to inventory plugin, because it happens even when the blocks to inventory plugin is disabled. }
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by AtomixCM** [comment]
[TokenEnchant-14.0.6-RC3.zip](https://github.com/JCulley/ProQuests-Documentation/files/3175546/TokenEnchant-14.0.6-RC3.zip)
Here is the plugin so you can test it for yourself.

**Comment by JCulley** [comment]
Alright, ProQuests does not remove chunks or blocks or modify the world in any way shape or form. ProQuests does not listen to any events unless a player has a quest with the specific type active. Your issue is obviously related to something else if you’re continually having blocks being removed.

I will say it one last time, ProQuests does not modify blocks or the world and only listens to the events provided by the TokenEnchant plugin itself if a quest is active.

**Comment by ghost** [comment]
Okay, I just wanted to keep you updated.

**Comment by ghost** [comment]
I have filed for support with the developer of TokenEnchant. I will keep you updated as to what happens from here.

**Comment by ghost** [comment]
After reaching out to the support team of TokenEnchant, this is how they responded to my message:

> We have other server owners who uses that resource and informed us that that resource does have a tokenenchant related quest which indeed process tokenenchant's block break/explosion related events.

> We have no idea what sort of processing ProQuests do for the token enchant related events.
​
"Disabling TokenEnchant and leaving ProQuests running alleviates the issue."  <-- this is because ProQuests' TokenEnchant module won't be activated if TokenEnchant does not exist."

> "We will close this ticket since there is nothing for vk to look at (This is because TokenEnchant does not include any code related to ProQuests but ProQuests does include some code related to TokenEnchant)"

At this point, it seems as though I have no choice but to not use ProQuests on my server. If both yourself and the developers of TokenEnchant are unwilling to investigate the issue, ProQuests is now useless for me.

**Comment by JCulley** [comment]
Sorry to hear that but unfortunately there’s nothing for me to investigate in this situation. I’m not unwilling it’s just there’s nothing to investigate, every block provided by the event needs to be evaluated against the quest conditions. As I previously stated you can attempt a workaround using a placeholder quest with EZBlocks if you’re only attempting to gather total blocks broken.

**Comment by ghost** [comment]
I would do that, but simply having proquests and tokenenchant installed at the same time is causing the error. 

Would you be able to link me to the version that doesn't include the tokenenchant break quest?

**Comment by JCulley** [comment]
Sorry no, old versions are removed and no longer distributed to prevent maintaining support from multiple outdated versions.

**Comment by ghost** [comment]
Can you remove the tokenenchant module hook then?

**Comment by ghost** [comment]
I really want to be able to use your plugin...

**Comment by JCulley** [comment]
If the root of the issue lies when quests are not running then ProQuests is in no way responsible. Events are registered and deregistered individually per quest. If there are no quests active then the event will not be registered anywhere within the plugin. The only other TokenEnchant methods called are if you’re using TokenEnchant token balances to retrieve the player balance.

The option to disable hooks manually in a file was removed with the new dynamic loading system. I’ll open a suggestion to add a file to toggle which hooks to utilize but cannot guarantee any sort of timeframe as to when it will be added.

**Comment by ghost** [comment]
The error occurs even when there are no quests loaded.

**Comment by JCulley** [comment]
> If the root of the issue lies when quests are not running then ProQuests is in no way responsible

I don’t want to continue to repeat myself. Here is the issue to reference for the hooks file #279

**Comment by vk2gpz** [comment]
remove the following!  (you're telling other plugins which are listening to TokenEnchant's events that those blocks are exploded!  Why would do that every time a player break a block???)

Yes, you can claim that "ProQuests does not remove chunks or blocks or modify the world in any way shape or form", but you're telling other plugins that 40x40x20 blocks are exploded.  Plugins like AutoSell will respond to that event and will start removing those blocks!

It is rather irresponsible to suggest other plugins to remove those blocks and claiming that this plugin is not responsible for those block removals.

```
  @EventHandler
  public void breakList(BlockBreakEvent paramBlockBreakEvent) {
    ArrayList arrayList = new ArrayList();
    Location location = paramBlockBreakEvent.getPlayer().getLocation();
    int i = location.getBlockX();
    int j = location.getBlockY();
    int k = location.getBlockZ();
   
    for (int m = 0; m < 40; m++) {
      for (int n = 0; n < 40; n++) {
        for (int i1 = 0; i1 < 20; i1++)
        {
          arrayList.add(location.getWorld().getBlockAt(i + m, j - i1, k + n));
        }
      }
    }
 
   
    TEBlockExplodeEvent tEBlockExplodeEvent = new TEBlockExplodeEvent(paramBlockBreakEvent.getPlayer(), paramBlockBreakEvent.getBlock(), arrayList, 0.0F);
    Bukkit.getPluginManager().callEvent(tEBlockExplodeEvent);
  }
```
