### ISSUE TITLE
Re-add hooks toggle file

### ISSUE THREAD

**Issue by JCulley** [JCulley/ProQuests-Documentation#279]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - Add back the previously removed hooks.yml file to allow for overriding the dynamic loading (only for disabling).
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - N/A
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - N/A

**Comment by ghost** [comment]
Approximately how long do you think it will take to add this hooks file back? I am very eager to start using your plugin again...

**Comment by JCulley** [comment]
I cannot provide a timeline, thanks for your patience.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-give-players-objectives.18249/update?update=278998
