### ISSUE TITLE
FISH_QUEST Error

### ISSUE THREAD

**Issue by Ssomarrr** [JCulley/ProQuests-Documentation#281]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

https://www.spigotmc.org/members/ssomar.641604/
<br>

**Plugin Version**
> Proquest 2.1.1.5

<br>

**Spigot Version**
> paper-1612

<br>

**Log File**
https://pastebin.com/2L6kEHGM

<br>

**Addition Information**

When I fish a fish it does not do anything and it shows me a console error.
> 
> Steps to reproduce:
> 1. Take a fishing rode
> 2. and fishing

<br>

**Comment by JCulley** [comment]
The simple answer is the official Spigot 12.2 builds contain the getHook() method in the fishing event whereas the Paper Spigot version you are using does not (hence the error).

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/event/player/PlayerFishEvent.java?at=refs%2Fheads%2Fversion%2F1.12.2

I do not provide any official support for Paper Spigot for instances like this.

**Comment by Ssomarrr** [comment]
I have test with spigot 1.12.2 ajd again error https://pastebin.com/nBBzG8D7
