### ISSUE TITLE
Chunks being removed?

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#282]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/cm_lectric.232281/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.7}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8)}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://hastebin.com/icewebisuf.md}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - {Massive chunks of land being removed on block break:
1) Problem does not occur when tokenenchant is unloaded.
2) Server still lags on block break even with tokenenchant unloaded, however the massive chunks of land are not being removed if tokenenchant is unloaded.
3) Disabling every single hook in hooks.yml still allows the error to occur.}
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
Provide additional media please. I have already stated that ProQuests doesn’t remove or modify blocks in any way so to believe this has anything to do with ProQuests makes little to no sense. I need a visual representation of this “issue”.

**Comment by JCulley** [comment]
Additionally if as you stated this doesn’t occur when TokenEnchant is unloaded then it seems rather obvious that TokenEnchant is the culprit here.

**Comment by ghost** [comment]
It doesn't happen if ProQuests is unloaded either...

**Comment by JCulley** [comment]
The only difference I can see in your log is that it appears ProQuests is still attempting to hook into WorldGuard to check if the player has permission to break the block (result of disabling the WorldGuard hook). I’ll have to see why that method is trying to be accessed but it would not result in the removal of chunks.

**Comment by ghost** [comment]
![2019-05-24_13-20-05](https://user-images.githubusercontent.com/29317588/58345570-b0b4b280-7e26-11e9-8b86-c35e873dbc3a.gif)

**Comment by ghost** [comment]
![2019-05-24_13-21-31](https://user-images.githubusercontent.com/29317588/58345687-eb1e4f80-7e26-11e9-9a20-5cb108cf08fe.gif)

**Comment by JCulley** [comment]
Interesting, but no ProQuests doesn’t remove blocks. Can you provide the relevant log from the time you broke the block +- 1-2 minutes.

**Comment by ghost** [comment]
https://hastebin.com/fiqobihoro.http

**Comment by ghost** [comment]
What would happen if you completely removed the tokenenchant module?

**Comment by JCulley** [comment]
So just the WorldGuard error odd, nothing pointing to any other issues specifically. The TokenEnchant hook will not be removed as there are other individuals using ProQuests to consider.

**Comment by ghost** [comment]
Would you consider sending me a .jar with the tokenenchant module removed so I can use your plugin?

**Comment by JCulley** [comment]
No I’m not going to compile and maintain versions specifically for individuals.

**Comment by ghost** [comment]
Don't maintain it then. I just want to be able to use your plugin man.

**Comment by ghost** [comment]
I really don't like leaving terrible reviews for plugins on spigot.

**Comment by JCulley** [comment]
I would’ve considered it until you said that. ProQuests has absolutely no part in modifying blocks, these removals are not being performed by ProQuests.

Take your threats of leaving terrible reviews elsewhere because I could care less. You’ve already posted a terrible review in the past anyways why would my reaction now be any different. Doing so will quickly result in all support being cut off all together.

So feel free to do as you wish but I am certainly locking this thread now.
