### ISSUE TITLE
Data values of rotated logs

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#284]
referencing: https://github.com/JCulley/ProQuests-Documentation/issues/272

First thank you for the material list. Maby it would be a good suggestion to link the materials in your wiki for all version.

The problem now is that I either can not or don't know how to enter all data values.
When I want to let players farm for example all Oak Wood I have the material LOG and Data Value 0. But because for all logs there are more than just a one digit data value (they have 4 bits) it occurs, that the plugin only counts oak logs that are facing upwards.

So although I tried many ways there is no obvious way to enter the second data value for the orientation.

https://minecraft.gamepedia.com/Log

**Comment by ghost** [comment]
Before you answer again: I found the solution to add it to allowed materials.

but there is an 'error' in your plugin. 
You are not able to create an quest "Farm one stack oak and one stack birch-wood"
because you can add them both to allowed materials and set a total of 128 but when you want to set birch and oak to 64 each at required materials, you can't, because each of them hat 4 different data values.
(oak: LOG;0, LOG;4, LOG;8, LOG;12, birch: LOG;2, LOG;6, LOG;10, LOG;14)

please correct, if im wrong

**Comment by JCulley** [comment]
No one had brought this to my attention until now. I was unaware that the data value varies based on the direction the log is facing.

I believe that this is the only block which has a data value based on rotation (unless you know of others) so I'll see about working out some sort of generic value to put specifically for logs.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-40-off-flash-weekend-sale-give-players-objectives.18249/update?update=280321
