### ISSUE TITLE
TOKEN_ENCHANT_BREAK_QUEST Total value capped at 2.147E9

### ISSUE THREAD

**Issue by CMlectric** [JCulley/ProQuests-Documentation#285]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/cm_lectric.232281/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.9}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {1.8.8}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://hastebin.com/uwagixobow.md}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - {Although an update stated that the token_enchant_break_quest ws updated to use a double value instead of an integer, the quest is capping total values at 2.147E9. It would be preferable to expand this to actually utilize double values.}
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
Looks like I missed the initial constructor (still an Integer). I will allow access to your initial account again, and provide you support however will not tolerate any indecencies in the future. I'll admit it was my mistake however threats of poor reviews as an attempted leverage will result in a bans of any accounts in the future and you will not receive any support whatsoever.

**Edit** - Additionally you do not have any permission to redistribute the JAR (which you obviously did to involve VK). Any unauthorized redistribution will result in the software access being revoked.

**Comment by vk2gpz** [comment]
He did not redistribute the jar file. I do not have any direct interaction with him and my support team has given a strict instruction to accept nor use any pieces of software, which we do not have legitimate ownership. 

Anyone could have spotted the mistakes from the code this user has reported on the discussion forum of your plugin. 

Again, this user did not do wrong doing as you accused.

**Comment by JCulley** [comment]
> He did not redistribute the jar file. I do not have any direct interaction with him and my support team has given a strict instruction to accept nor use any pieces of software, which we do not have legitimate ownership.
> 
> Anyone could have spotted the mistakes from the code this user has reported on the discussion forum of your plugin.
> 
> Again, this user did not do wrong doing as you accused.

I don’t understand what your point here is. The code was posted as a “response” from your support team. I’m well aware that they had no issues publicly redistributing JARs as they publicly posted links to the TokenEnchant JAR on two separate occasions where I refused them and removed the posts immediately.

Thanks to whoever pointed out the initial legacy code from testing, however I’m discussing redistribution. Realistically I don’t understand why you’re speaking on behalf of the user. Regardless I don’t want this getting off topic.

**Comment by CMlectric** [comment]
I think we all did what was needed to fix the bug, and thats what counts

**Comment by vk2gpz** [comment]
I made the post because you assume too much and accuse others without trying to find out the background nor listening to others. 

My support team has never possessed nor used your program to make their suggestion to this user.

**Comment by JCulley** [comment]
Thanks for your insight VK. So how about we end this discussion.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-40-off-flash-weekend-sale-give-players-objectives.18249/update?update=280321
