### ISSUE TITLE
Quests that are enabled with autostart are not autostarting

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#287]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/cm_lectric.232281/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.9}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {1.8.8}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://pastebin.com/qvhdQSC7}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - {Although a player is granted the permissions for autostarting quests, and the quests themselves have autostarting enabled, the quests are still requiring the player to click them in the menu to start them.}
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
I will need the YAML files of the quests in question.

**Comment by ghost** [comment]
Here is one of the quest .yml files. They all look like this one, just with different rewards and different total values.
https://pastebin.com/4vBT8Xf0

**Comment by JCulley** [comment]
And what permissions have you provided your players?

**Comment by ghost** [comment]
- proquests.active.100
    - proquests.quest.autostart.blocklegend
    - proquests.quest.autostart.blockannihilator
    - proquests.quest.autostart.blockdevastator
    - proquests.quest.autostart.blockdominator
    - proquests.quest.autostart.blockmaster
    - proquests.quest.autostart.blockexpert
    - proquests.quest.autostart.blockpro
    - proquests.quest.autostart.blocknovice
    - proquests.quest.autostart.blockbeginner
    - proquests.quest.autostart
    - proquests.quest.progress.blockbeginner
    - proquests.quest.start.blockbeginner
    - proquests.menu.open.prestigequests
    - proquests.menu.open.blockquests

**Comment by ghost** [comment]
Even as an OP I don't have them autostarted.

**Comment by JCulley** [comment]
Which one did you send me “blockbeginner”? If so can you please also provide me another with the identifier and I’ll test it later.

Also you have to give the start permission for each quest, I only see you providing a single one?

**Comment by ghost** [comment]
I sent you BlockAnnihilator. I'll send you another.
https://pastebin.com/rq4xxPgp

Even with the start permission, autostart was not activating block beginner for the player. Mind you, the quests aren't autostarting for an Opped player either, even though they have * perms.

**Comment by JCulley** [comment]
So I took the exact YAML configuration file you provided for "BlockAnnihilator" changed only one thing making it of type BLOCK_BREAK rather than TOKEN_ENCHANT_BLOCK_BREAK and it auto started fine for me as an OP.

Players wouldn't get any notification of the quest starting as you do not have it setup as such, and you don't have any progress actions defined so they would be unable to check their progress as well.

How are you verifying that it wasn't started? Additionally are you saying that these quests are not auto started **but** they can still start them from a menu you have setup?

**Comment by ghost** [comment]
1) I'm unsure of how to set up progress actions -> I'll take a look at the wiki
2) I need it to be TOKEN_ENCHANT_BREAK_QUEST so the enchanted pickaxes count for blocks too.
3) The quests all show "click to start" when looking at the quest menu. Only after clicking them to start do they show that they are in progress. Assumingly, I would expect the quests to all show as in progress if they have autostart enabled.

**Comment by ghost** [comment]
I believe the quest type is TOKEN_ENCHANT_BREAK_QUEST not TOKEN_ENCHANT_BLOCK_BREAK right?

**Comment by JCulley** [comment]
1. They're just like complete actions but can be seen when running /quest progress \<id\> not required just something I'd mention
2. I don't have TokenEnchant to test with however the autostart is not dependent on the quest type.
3. Then correct they have not been started. You must have something incorrect with your permissions.

GIF of me running your quest file non-op with perms (added a start action so you could visually see it start):
https://gyazo.com/27f1bd7ea3599ba0d67ef5d774003b59

Screenshot of the permissions:
https://gyazo.com/dbcad0f951e879603d9301e4ff369b8c

**Comment by JCulley** [comment]
Players have to have the start permission to begin a quest regardless, so I'm guessing it was auto starting for "blockbeginner" however none of the others in your scenario.
