### ISSUE TITLE
Quest Progress - Show the actual progress of the quest at hand 

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#288]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - {It is to my understanding that there are only progress_actions (much like start actions). It would be great if a player could check their progress and see, say 1059/1060 blocks broken (if it is a block breaking quest). 

I'm sure this would get more complicated when it comes to multistage quests. However, it would be nice to see your progress towards completing a quest.

Sorry if this feature already exists. I just have no idea how to do it then.}
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - {insert here}
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - {insert here}

**Comment by JCulley** [comment]
Progress actions perform the exact thing you described. Didn’t notice the “by hand” in the title, however you could just use the action bar.

**Comment by ghost** [comment]
How to I use progress actions to show the quest progress?

**Comment by ghost** [comment]
There are no actions in the wiki that point to showing a players progress through a quest.

**Comment by JCulley** [comment]
https://github.com/JCulley/ProQuests-Documentation/wiki/Placeholders

**Comment by JCulley** [comment]
I have added an example to the actions page.
https://github.com/JCulley/ProQuests-Documentation/wiki/Actions
