### ISSUE TITLE
Permission Quest not completing although player has the required permissions to satisfy the quest 

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#289]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/cm_lectric.232281/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.9}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {1.8.8}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://pastebin.com/qL95szeU}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - {I have permission quests set up that require a player to have a permission like "ezprestige.prestige.1", but even though the player has the permission, and the quest is registering as in progress (as per the quest menu), the quest is not completing.}
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
First thing, provide your log file for each issue. Additionally try to refrain from opening so many and try to work through it a bit yourself before opening an issue.

The quest validates based on the the string permissions provided and is updated every time the QuestUpdateEvent is called (which is whatever you have it defined as in the config). This is due to the fact there are no events for notifying of a permission change so it is not performed in real-time.

**Comment by ghost** [comment]
I've set the quest update in the config to 3, and have been on for a long time, but the player still isn't being credited for completing the quest even though they have the permission.

Here is my config.
https://pastebin.com/zf37eEv8

**Comment by ghost** [comment]
This problem is still persisting. 
The quest is started for the player, but it is not completing for them.

This problem is not happening for an OP, only for a normal player.

**Comment by JCulley** [comment]
> This problem is not happening for an OP, only for a normal player.

Then the player doesn't have the permissions. It takes the list and uses the entity hasPermission() function provided by Bukkit. If your permission plugin isn't properly registering them within Bukkit you have another issue all together.

**Comment by ghost** [comment]
I fixed it by reentering the permission required into proquests
