### ISSUE TITLE
Console error with no additional information.

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#291]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/cm_lectric.232281/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.9}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {1.8.8}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://pastebin.com/gjfdETuS}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - { This error triggered as I was editing a quest menu unrelated to that of the buycraft quests.
https://pastebin.com/sqdqfuqp}
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
1. Please stop enclosing everything in curly braces, they are meant to be replaced and it breaks every link you provide.

2. Why do you believe that this has anything to do with the BuycraftQuest buycraft is not mentioned anywhere in the error you provided.

3. You only provided half of the error which would be fine as I could check the full log however you didn’t provide the full log with this occurrence as I did not see it anywhere within. Provide the ENTIRE log file relevant to when the issues occur or there’s nothing I can investigate.

**Comment by ghost** [comment]
Sorry, I missed the part that said buycraft. I will be sure to stop entering my info in the braces. I will keep an eye out for the error again.

**Comment by JCulley** [comment]
> I could check the full log however you didn’t provide the full log

Also as I said if you don’t provide the full log then I can’t get a better understanding of the situation. Thanks for understanding.
