### ISSUE TITLE
Repeatable Quests Issue | Quest Timer Check Issue

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#292]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/cm_lectric.232281/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.9
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - 1.8.8
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/iEtft1Rt
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - 
When starting a quest that runs on a timer, and has a repeat delay, two things are happening.
1. The quest will only update the timer and run out of time once the player opens the menu.
2. Once the quest runs out of time and gets canceled, players can start the quest again instantly without having to wait for the repeat delay.

Here is the error: 
https://pastebin.com/rZyvW1pX

Here is the quest.yml: 
https://pastebin.com/jrzanijg
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
1. Not an issue, it's designed this way. It updates the status on menu opens, player joining, player leaving, and anytime a quest listener is called. There's no point in wasting performance by validating every single players quests every single second.

2. Once again it was designed this way. It was not in any consideration to keep track of any and all quest that players did not complete. The repeat delay is taken into consideration when a quest is completed successfully. Adding a repeat delay for cancelled/failed quests would require a large overall.

3. I have no clue what the "error" you provided from your log is referring to as once again it is only a portion of what would be output. Regardless it would have nothing to do with whatever you've mentioned here.

Regardless neither of these are "issues" so I don't understand why this was opened. Please use the issues purely for suggestions and actual error reports.
