### ISSUE TITLE
Break Quest negative count

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#293]
**Details** - Count placed blocks negative at break block event
<br>

**Additional information** - When a player start a break quest 'break 10 Stone' he can simply place the stone and then break the blocks to complete the quest. By counting the placed stones negative for the break quest it would make it more difficult for players to cheat

**Comment by JCulley** [comment]
I don't believe i'm going to implement this as its rather flawed in theory. What if a player placed a block and another broke it, should the original player really be penalized?

If these are for specific regions (like a Prison mine) I suggest you only allow for progress within those regions and then block specific block placement within those regions.
