### ISSUE TITLE
Data loss by Plugin

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#295]
Referencing https://github.com/JCulley/ProQuests-Documentation/issues/290 and https://github.com/JCulley/ProQuests-Documentation/issues/201

There is no answer given in any of the threads. The Problem occurs with both: sqlite and mysql.

In mysql I can see that the correct data are being override by corrupt data. There is no cause identifiable as I told you via Spigot PN.
The SQL Database was created by the Plugin itself and works in 99% of the cases. But sometimes there is data loss.
Same with sqlite and this database is completely generated by proquests

**Comment by JCulley** [comment]
This does not follow any of the guidelines in place, so it would have been closed for that reason alone however I have already provided an answer you refuse to read apparently.

> There is no defined answer as to which it needs as the answer is there is no specific requirement. You can modify the table as you wish as long as the columns and table names stay in tact and can hold the expected value types. **It will work with UTF-8 however you need to manually change any columns to accommodate larger values ie. change it to TEXT, BLOB or whatever.**

> **It is your responsibility to manage your database** as you wish, ProQuests simply initializes the tables and columns it needs.

If the size of the data exceeds that of what is acceptable in the table (character wise) then the database will ignore the insert/update. I clearly stated the following:

**It will work with UTF-8 however you need to manually change any columns to accommodate larger values ie. change it to TEXT, BLOB or whatever.**

Do not open any other issues regarding this.
