### ISSUE TITLE
Cycleable Quest Menu

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#300]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - Ability to create a menu that will cycle quests on a Timed basis basis. This would require you to add the various quests to a quest pool, and then create a menu that will feature these quests based on some form of randomization or proceeding order. 

For example - I create a "Daily" Quest Menu, and add 9 quests to the quest pool. I then select the slots in the menu where the quests will appear. Let's say I select 3 menu slots for quests to appear. This would mean that 3 quests will be selected for those 3 slots on a daily basis. Once a quest is completed, it would follow the standard behaviors that quests follow as defined in their setup.

This would allow for players to choose from different quests that are only available daily, or weekly, or whatever time period is selected. 

I know that there is already the option to create daily quests, however, it would be ideal if these daily quests could be mixed up a bit, so that players aren't completing the same exact quests every 24 hours.
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - {insert here}
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - {insert here}

**Comment by JCulley** [comment]
You just described the exact functionality of the packages add-on
