### ISSUE TITLE
MySQL create table syntax error

### ISSUE THREAD

**Issue by Xofters** [JCulley/ProQuests-Documentation#301]
**Spigot account** - https://www.spigotmc.org/members/xofters.551077/
<br>

**Plugin version** - 2.1.1.12
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - git-PaperSpigot-unknown (MC: 1.8.8)
<br>

**Link to log file** - https://pastebin.com/EfUqfE4S
<br>

**Additional information** -
Mysql not loading at all, not even creating Tables.
<br>

**Additional media** - NONE
<br>

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-20-off-independence-day-sale-give-players-objectives.18249/update?update=284904
