### ISSUE TITLE
ProQuests Packages Wiki

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#302]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - Without any documentation, it is difficult to set up packages. I would appreciate if there were instructions added to the wiki.
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - {insert here}
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - {insert here}

**Comment by JCulley** [comment]
This is not a feature suggestion.

**Comment by ghost** [comment]
How am I supposed to use packages then?
