### ISSUE TITLE
Fishing Broken?

### ISSUE THREAD

**Issue by Xofters** [JCulley/ProQuests-Documentation#303]
Spigot account - https://www.spigotmc.org/members/xofters.551077/

Plugin version - 2.1.1.13

Spigot Version - git-PaperSpigot-unknown (MC: 1.8.8)

Link to log file - https://pastebin.com/74bbuGxR

Additional information -
Fishing broken, and not registering.
[12:31:32] [Server thread/ERROR]: Could not pass event PlayerFishEvent to ProQuests v2.1.1.13
org.bukkit.event.EventException

Additional media - NONE

**Comment by JCulley** [comment]
This has already been addressed, use official Spigot builds and you won’t have any issues. I have no control over what methods forks decide to remove/modify.

**Comment by JCulley** [comment]
Duplicate of #281
