### ISSUE TITLE
Plugin version mismatches

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#305]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/c_sd.8097/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {2.1.1.13}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {git-Paper-637 (MC: 1.13.2)}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://pastebin.com/TT8JHUxK}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - {I have the last version of all of these mismatch plugin errors. Can you tell me what i have to do?}
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
Provide a list of the dependencies which ProQuests references that are stated to have a mismatched version and provide the according links to the updated versions. Please try to provide some information when opening issues, as what you have provided has been very vague and useless from the beginning.

**Comment by ghost** [comment]
Buycraft(ProQuest references version 10.6.2.): Bukkit 1.13 (Actual version 12.0.2)
Citizens(ProQuests references version Citizens v2.0.24-SNAPSHOT (build 1595): https://www.spigotmc.org/resources/citizens.13811/ (Actual version: 2.0.25)
Holographics Display(ProQuests references version 2.3.0.) : https://dev.bukkit.org/projects/holographic-displays (Actual version: 2.3.2)
Player Points(ProQuests references version 2.1.4): https://dev.bukkit.org/projects/playerpoints (Actual version: 2.1.5)
Vault(ProQuests references version 1.6.7): https://www.spigotmc.org/resources/vault.34315/ (Actual version: 1.7.2)
WorldGuard(ProQuests references version v7.0.0-beta03.): https://dev.bukkit.org/projects/worldguard (Have the same version) 
These's all plugins that give mismatch error. @JCulley

**Comment by ghost** [comment]
@JCulley

**Comment by JCulley** [comment]
Updated to the latest versions,  the latest PlayerPoints download states the version is 2.1.4 in the plugin.ym

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-20-off-summer-sale-give-players-objectives.18249/update?update=286847
