### ISSUE TITLE
NPC Not Selecting

### ISSUE THREAD

**Issue by octobertx** [JCulley/ProQuests-Documentation#308]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {insert here}
<br>
https://www.spigotmc.org/members/novisyt.706024/
**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {insert here}
<br>
2.1.1.13
**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {insert here}
<br>
git-Spigot-76236cb-9cd1111 (MC: 18.8)
**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {insert here}
<br>
https://pastebin.com/nL6hVKAB
**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - {insert here}
<br>
Plugin works completely fine until trying to set a start and end NPC for the quest. It says it's not a registered NPC even though I have registered it and when I do the command while in creator mode, it doesn't say anything and keeps telling me to do the command.
**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>
https://gyazo.com/504ed4739ba6158571d65c7d727bd7ba
**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
1. Stop ignoring the format, if it says “{insert here}” why are you continually ignoring that. The format is just a mess and makes it confusing to read.

2. You obviously haven’t actually registered the NPC you are “claiming” to have created. Additionally you have provided no sufficient evidence, photos, configurations to back any of your statements so from my view point the only possible scenario is that there is no issue and the ProQuests NPC does not in fact exist.
