### ISSUE TITLE
Help WorldGuard

### ISSUE THREAD

**Issue by MrBaguette07** [JCulley/ProQuests-Documentation#311]
**Spigot account** - {https://www.spigotmc.org/members/mrbaguette07.491605/}
<br>

**Plugin version** - {2.1.1.14}
<br>

**Spigot Version** -  (MC: 1.12.2)
<br>

**Addition Information**
Hello,

I'm coming to you for the "ProQuests" plugins,
the players fail to increase break blocks on the worldguard regions,

is it possible to disable this in the configurations or from a flag worldguard?

Thanks for your help
MrBaguette07 

ps: I am French I am sorry for mistakes

**Comment by JCulley** [comment]
I have no clue what the “Issue” here is and you never provided your log file. I do not provide configuration assistance, issues are for errors and suggestions. Please provide all of the required information and an understandable description.

**Comment by MrBaguette07** [comment]
I can possibly provide the logs of proquests written on the console but I can not provide the logs file for reasons of confidentiality.
https://pastebin.com/SFUGh01H

**Comment by JCulley** [comment]
If you cannot provide the required information and a descriptive summary then I’m going to close this issue.
