### ISSUE TITLE
Add the miningblocks plugin

### ISSUE THREAD

**Issue by MrBaguette07** [JCulley/ProQuests-Documentation#312]
**Details** - Would it be possible to add the compatibility with the plugin "miningblocks", make it that the players can break and that it counts in the quests. it allows the players not to usebug worldguard.
<br>

**Link to plugin** - https://www.spigotmc.org/resources/miningblocks-1-8-1-14.6438/
<br>

**Additional information** - I do not think I have more to add, just do it when we activate worldguard and miniblocks it does not count broken blocks, so if possible added miningblocks that will allow to add points as soon as we break a block.

**Comment by JCulley** [comment]
I don’t understand this request. The plugin “miningblocks” as far as I can see simply regenerates the blocks, if for some reason it is canceling the block break event then you would have to contact the developer of the plugin. They should not be cancelling the event unless the action is being prevented which is not the case here as they reset the block to a new type.

Additionally you keep mentioning WorldGuard and I have no clue what that has to do with anything.
