### ISSUE TITLE
Issues while restarting using PlugMan

### ISSUE THREAD

**Issue by ColaIan** [JCulley/ProQuests-Documentation#314]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/420439/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.14
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - git-Spigot-6e94473-7ad3a1f (MC: 1.14.3)
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/raw/Gk81HRLb (because I have over 100 plugins, the log is too big to be uploaded, sorry for shrinking it a little bit, ask me for the log file if needed)
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - Type /quest menu, and then every character you type after it will cause an error
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
![image](https://user-images.githubusercontent.com/43201383/61359569-267d4d80-a8af-11e9-8324-1959bca9815d.png)

<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by ColaIan** [comment]
If it's a SQL problem then hope you can make a wiki page or make a plugin work right out of the box because I don't even know what should the table be called nor what should it contain (like integer, column names and etc)

thanks <3

**Comment by JCulley** [comment]
Please try to read the logs yourself, as can be seen it’s trying to access a class which no longer exists, so stop using PlugMan. Hot swapping (which is what plugman does) is not recommended. If you are not executing full server starts/stops then you may experience issues.

If this issue is still persistent after properly restarting your server provide the entire log, your reduced version will not be acceptable.

**Comment by ColaIan** [comment]
that persists even when I'm not using plugman
I'll resend the full log in a new issue as you have closed this already
