### ISSUE TITLE
AutoRemove

### ISSUE THREAD

**Issue by JoesonHoang01** [JCulley/ProQuests-Documentation#315]
**Details** 
Once a quest is completed, if the option to autoremove is set to true in the completed quests file (the quests inside the quests file and not the quest.yml), the quest will be removed from the players quest menu but can be added again if picked up

**Comment by JCulley** [comment]
I’m sorry I don’t understand what you’re asking for at all. Please provide a better more detailed description.

**Comment by JoesonHoang01** [comment]
Simplified: make it so that quests can be removed from the players gui after they have completed it

Extended:
If in the <quest name>.yml the option 'auto-remove' is set to true, then the quest will be removed from the players gui and not go on cooldown after completion. If 'auto-remove' is set to false then the quests will act as they do now and stay in the player's gui but the player is unable to select the quest since it's on cooldown.

**Comment by JCulley** [comment]
This seems pointless. There is already a “waiting” stage for all quest menu items for a reason.
