### ISSUE TITLE
1.14.3 Tab completion error

### ISSUE THREAD

**Issue by ColaIan** [JCulley/ProQuests-Documentation#316]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/420439/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.14
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - git-Spigot-6e94473-7ad3a1f (MC: 1.14.3)
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/wGrJ0YTg

<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - Type /quest menu, and then every character you type after it will cause an error
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - 

Configs: 
[ProQuests.zip](https://github.com/JCulley/ProQuests-Documentation/files/3404308/ProQuests.zip)

![image](https://user-images.githubusercontent.com/43201383/61359569-267d4d80-a8af-11e9-8324-1959bca9815d.png)

<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day** (just to declare that it's 9:04AM and it's another day : ) )

**Comment by JCulley** [comment]
> All provided media must be accessible online, download links will not be accepted

I won't download files. Please upload them to a paste site as stated.

**Comment by ColaIan** [comment]
@JCulley https://pastebin.com/kqXjtPQL this is the config.yml

**Comment by ColaIan** [comment]
and please stop from flagging issues instantly after you've replied to it, that's so annoying. You should flag issues after the another person has replied or had wait a decent amount of time. This is totally impolite to someone who waited you for weeks just to get a reply from you!

**Comment by TwerkRekt** [comment]
this developper is a shit lol

**Comment by JCulley** [comment]
Please provide your menu files seems how this is related to your menus.
