### ISSUE TITLE
Gangs+ and PlaceholderAPI version mismatches

### ISSUE THREAD

**Issue by AlessioTW** [JCulley/ProQuests-Documentation#318]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/xscorpion93x.132770/}
<br> 

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** -  {2.1.1.14}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {git-PaperSpigot-"8b18730" (MC: 1.8.8)}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {https://pastebin.com/iZP2exm4}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - I'm using the latest version of these plugin:
Gang_Plus(ProQuests references version 2.3.0): https://www.spigotmc.org/resources/gangs-1-7-1-14.2604/ - (Actual version: 2.6.2)
PlaceholderAPI(ProQuests references version 2.9.2): https://www.spigotmc.org/resources/placeholderapi.6245/ - (Actual version: 2.10.3)
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by TwerkRekt** [comment]
this developper is a shit lol

**Comment by JCulley** [comment]
Updated both references, there were no API changes (for the portions ProQuests references at least) so there should be no impact should you choose not to update for some reason.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-give-players-objectives.18249/update?update=304027
