### ISSUE TITLE
BlockBreak doesn't work

### ISSUE THREAD

**Issue by Halbgod** [JCulley/ProQuests-Documentation#319]
Version 1.14.4
Current Version of ProQuest
======================
So the break_block event is recognized by the Plugin. 
Even the first default Quest you implemented doesn't work. The Timer is running but the items won't get counted. I tried to adjust the needed item to grass_block but it still doesn't count.

Is there any fix?

**Comment by JCulley** [comment]
Closing as it doesn’t follow any of the guidelines. Don’t open another unless you’re willing to provide the required information and a detailed description.
