### ISSUE TITLE
Click to check progress option

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#321]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - It would be nice if on active quests, you could click them in the menu which would trigger the progress actions. This way, players wouldn't need to type the command to check the progress of the particular quest. It would be much easier to just view the active quest in the menu, and then have it show you whatever progress actions you setup.
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - {insert here}
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - {insert here}

**Comment by JCulley** [comment]
Is there a reason you wouldn’t just display it with menu items? Seems kind of counter intuitive in my opinion as you would have to close the menu any time a player clicks an active quest.

That’s kinda the whole point of having refreshing/animated menu items as they never have to leave the menu.

**Comment by ghost** [comment]
Ohhh I see now. Thank you for clearing this up! I should have thought of
that.

**Comment by JCulley** [comment]
No worries, I’ll close this issue. If later on you or anyone else decides this would be a feature you would still want added it wouldn’t be too difficult to add.
