### ISSUE TITLE
Packages | View quests in package bunch only if players have permission to see it

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#322]
**Is your feature request a quest suggestion?**
If so please provide a clear explanation of the functionality and the specific requirements you want to be included.

**Details** - Right now, it seems the only thing you can do with having daily quests is having a universal set of daily quests show for all players. If a player doesn't have permission for the quest, it shows up as unavailable. What I would like to see is instead of taking up a spot saying unavailable, I would prefer the package just shows quests that the players have permissions for instead. Sorry if I can already do this. I'm just not sure how.
<br>

**Does your feature request require another plugin?**
If your request involves another plugin (this includes but is not limited to quests, balance types, teams etc.) you MUST provide a link to the plugin page

**Link to plugin** - {insert here}
<br>

**Addition Information**
Provide as much additional information explaining the request. This includes but is not limited to images, screenshots, or links to other examples which provide a better understanding The more specific you can be the better as it will help us get a better idea of your vision.

**Additional information** - {insert here}

**Comment by JCulley** [comment]
The add-on is not designed to work in such a way, the order is randomly chosen and doesn’t take into consideration whether a user has permission. If this was the case it would have to store a specific list tailored to each player every time it is refreshed.

This would require a complete re-write and overall is an overhead which I don’t believe is at all necessary.

You can always just make separate tiers of your packages and give permissions to different users to view individual menus for each.

**Comment by ghost** [comment]
Thank you for this idea!
