### ISSUE TITLE
Token_Enchant_Break_Quest only tracking blocks broken by a token enchant.

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#323]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/cm_lectric.232281/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.14
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - 1.8.8
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/a3N3X6dF
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - When mining, only pickaxes enchanted with a special tokenenchant break enchantment like explosive or excavation are being tracked. This is not optimal since a player is still breaking blocks. If you could, please make it so that all regular block breaks AND tokenenchant breaks are tracked within this quest.

I am using the tokenenchant break quest to track all of the blocks broken from a player throughout their time on the server. Simply using the break quest doesn't suffice since it doesn't track the blocks broken from the tokenenchant block breaks.

If you could include both the tokenenchant breaks and the regular breaks in the tokenenchant break quest, it would be of massive help and improvement to the quest.

Thank you!
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
The quest is designed to listen for breaks from the event passed by token enchant, so it is working as expected. This is not an error.

The idea is to provide a quest only tracking those blocks broken with an enchant, not those without.

**Comment by ghost** [comment]
I understand it is working as described, but it is not optimal. Would you
be able to make it include regular breaks as well?

**Comment by JCulley** [comment]
Then you should realistically use a placeholder quest if you want a players total block breaks.

**Comment by ghost** [comment]
Thank you for your understanding. You have been very helpful in explaining how to best use your plugin. Great work man, it works well after you get past the beginning hurtles of setting it up and understanding how it works.
