### ISSUE TITLE
Entity selected is not a registered NPC 

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#326]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/cm_lectric.232281/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.14
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - 1.8.8
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/8zh1LKy3
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - So we created a quest called BorisPickaxe. We then created an npc using citizens. We create the npc using /quest npc create PrisonerJim. We then link every field in that little menu to prisoner jim. Then we go to edit the BorisPickaxe quest. We try to link the quest to the npc, but it says what is displayed in the attached picture.
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - https://media.discordapp.net/attachments/337851419757641729/629176163134078976/unknown.png
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
You’re honestly just wasting my time at this point. I don’t understand how opening an issue for a valid error message could possible be an error seems how you don’t bother to even attempt to elaborate. 

There’s a reason why I explicitly state to not open more than one issue a day. I am not meant to be your first point of contact, I am meant to be the last option if a series of problems exists. You  are a system administrator responsible for your own setup so do your own RCA and testing first.

Thanks.

**Comment by ghost** [comment]
I am creating an NPC using /quest npc create "identifier", and then linking all of the fields to the desired NPC by right clicking. Then when it gives the option, I am saving and exiting the menu.

I then do /quest edit "identifier", click Start NPC, right click the NPC I just created through /quest npc create "identifier", and then it gives me the "valid error message".

Instead of thinking I'm "wasting your time", can you please investigate this for yourself? I don't think you remember when you insisted that the token_enchant_break_quest chunk removal bug wasn't your fault and wasn't a problem related to your plugin, when in reality, it 100% was. Maybe this is an error as well. 

Have more patience while you are at it please. I know you might be busy, but I'm just trying to use your plugin man.

**Comment by JCulley** [comment]
> I am not meant to be your first point of contact, I am meant to be the last option if a series of problems exists. 

You didn’t even verify if the NPC exists, you know how I know this? If you had actually even attempted and did a reload then it would be registered. NPC’s are not loaded until a reload occurs.

Please don’t state I need more patience when you aren’t even attempting to solve your own problems. Support is something I provide above and beyond your initial sale. You are responsible for 10% of all of the issues opened, and majority of them are simple questions or an unwillingness to try to figure it out yourself. Provided I charged you for my support you would owe me hundreds of dollars.

If you open any future issues where it is clear it is not a problem, or that you didn’t attempt to work through it yourself I’m just going to remove your access from opening issues.

You are in fact wasting my time.

**Comment by ghost** [comment]
Okay, thank you for letting me know that I needed to reload the plugin. I don't know how to solve problems with a plugin I didn't make.

**Comment by JCulley** [comment]
Then being a system administrator is not for you.
