### ISSUE TITLE
placeholder %proquests_total_completed_quests%

### ISSUE THREAD

**Issue by TwerkRektDev** [JCulley/ProQuests-Documentation#327]
**Spigot account** - https://www.spigotmc.org/members/mrbaguette07.491605/
<br>

**Plugin version** - 2.1.1.15
<br>

**Spigot Version** - Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
<br>

**Link to log file** - https://hastebin.com/uxukozixab.md
<br>

**Additional information** - 
Hello, the placeholderapi does not work very well, it calculates the number of quests but not those repetitive, so example I have a repetitive quest with two days delay it will not count
<br>

**Comment by JCulley** [comment]
So I take it this is more of a suggestion as it’s not an error as that’s how the system is designed. The total completed quests in fact refers to the unique quests which have been completed.

The program was not designed to track the amount of times a specific quest has been completed, and would require a massive overhaul to achieve the desired state you are proposing.

Realistically this would be a massive change with little added benefit, so I’m going to have to unfortunately say no to this request.
