### ISSUE TITLE
Menu Materials do not appear.

### ISSUE THREAD

**Issue by OOmerBey** [JCulley/ProQuests-Documentation#328]
**Spigot Account**

# https://www.spigotmc.org/members/nexima.40441/

**Plugin Version**
 
# ProQuests Version: 2.1.1.14 build: 17757

**Spigot Version**
# Paper version git-Paper-1618 (MC: 1.12.2)

**Log File**
# There are no warnings or errors in the logs.

**Addition Information**
Hello there.
I'm using your plugin, but I can't configure it because of the difference in configuration between your old and new versions.

When I drop the plug-in into the plugins file and start the server, it does not give warning and error in the console, but the materials do not appear in the menu as shown in the picture.

I didn't make any adaptations to the files you created completely your configuration.

**Menu configuration file**

1- https://hastebin.com/arufizukes.php

**Quests configuration file **

1- https://hastebin.com/izuvucuxay.makefile
2- https://hastebin.com/ahokeqelev.makefile
3- https://hastebin.com/wigosucoye.makefile

**Example Picture**
1- https://i.hizliresim.com/dLdzgp.png
1- https://imgyukle.com/i/EwAOvh

**Comment by JCulley** [comment]
Please provide you log file. As stated in the template I don’t care if you don’t see any warnings or errors it is required.

**Comment by OOmerBey** [comment]
It's sad to buy the plug-in for money and then meet a very rude plug-in owner.

https://hastebin.com/ikemisiyid.md

**Comment by JCulley** [comment]
Thanks for calling me rude when you want assistance. Your log only shows the startup, I would like a full log up to the point of you opening the menu with the “issue” occurring (no players join at any point with the log you have provided).

Additionally all of the information you have provided me is rather conflicting, so please send me a PM on Spigot so I can verify you are the owner of the account of the buyer.

**Comment by OOmerBey** [comment]
You're resisting not to help people. you are also really very but very rude! This attitude takes you away from people!
I regret choosing you!

**Comment by JCulley** [comment]
I don’t understand how I’ve been resistant in any way, I just want the required information before I’m going to move forward.

So are you going to provide the updated log, and send me a PM? If not then I guess I’ll close this?

**Comment by JCulley** [comment]
Closing this seems how you have yet to provide me the updated log, and also haven’t sent me a PM on Spigot.
