### ISSUE TITLE
Block break bug

### ISSUE THREAD

**Issue by xdLulux** [JCulley/ProQuests-Documentation#330]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {https://www.spigotmc.org/members/skah.704626/}
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - {LATEST --> 2.1.1.15}
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - {PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest}
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - {there is 0 errors https://pastebin.com/JtWy2iNa}
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - { > there is no errors just a feature that doesn't work. I can't seem to make the break block thing to work with blocks such as REDSTONE_ORE;0 and some other stuff such as GOLD_ORE;0 }
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {https://gyazo.com/b2ca209a4f05a4b0f10d27c4dbdbe9e9}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
If you open another issue regarding this you will not have access to open anymore, it’s simple.

Do not open issues for something which is not an error. If you have misconfigured something it is your responsibility to correct the issue.

You literally opened another issue with the same information except provided a useless video of the creator and you breaking some random blocks, what does this have to do with anything? What am I supposed to do with this? 

Don’t open any other issues unless you are willing to provide a DETAILED EXPLANATION with accompanying information to assist in the debugging process.

**Comment by xdLulux** [comment]
I am requesting help and you can't even help me ? I didn't config anything I just looked at the item data and bam if you have a '_' it won't work please help your customers
