### ISSUE TITLE
Quest didn't finish.

### ISSUE THREAD

**Issue by Ragnarak123** [JCulley/ProQuests-Documentation#332]
Firstly, i can't create a mob kill quest wih a spesific named mobs. Secondly, https://pastebin.com/X8KijriR this quest is working well but when i add spesific metarial like cobblestone it was broken. It count cobblestone there is not problem but when player reach 64/64 quest didin't finish. here is quest https://pastebin.com/tJv1cjTA . I reinstalled and tried but it didin't work again. There is no error in console. How can i fix it ? Please, help me.

**Comment by JCulley** [comment]
This doesn’t follow the issue format. If you are going to open an issue follow the template with the required information.
