### ISSUE TITLE
Player's quest data and progress always lost

### ISSUE THREAD

**Issue by mlegok12** [JCulley/ProQuests-Documentation#334]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/mlegok.92886/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - Latest version
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - Paper spigot 1.13.2 Latest version
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - There are no traces in logs.
<br>

**Addition Information**
Hello, my friend! I hope only you can help me cause you are the creator of this plugin.
That problem connected with players data. Database connected to mysql, it works perfectly without any errors in log. But sometimes (i didn't note the time) player data wipes and they start quests from beginning. I have had this problem since i bought your plugin.

**Comment by JCulley** [comment]
Hi, without more information and details which I could actually investigate and look into I can’t very well address this “issue” especially seems how you seem to be the only one reporting this. Typically if it is a single case of something like this it is specific to how your server is setup and managed rather than it being a software issue.

So if you can provide more information please do so, otherwise I’ll have to close this ticket.

**Comment by mlegok12** [comment]
I dunno what i can provide to you, cause no errors in console was viewed.  I have only this problem: players progress always being deleted in some period of time. If i had some error, i'd provide you logs. I have this problem in different minecraft server builds..

**Comment by JCulley** [comment]
Alright, well unfortunately with the amount of information you have provided there’s not much I can do. So I’m going to have to go ahead and close this.

**Comment by mlegok12** [comment]
So, what information do you need for working with this problem?

**Comment by JCulley** [comment]
Anything which would point towards an evident issue in the software rather than just conjecture.
