### ISSUE TITLE
Scoreboard with progress bar

### ISSUE THREAD

**Issue by mlegok12** [JCulley/ProQuests-Documentation#336]
My profile: https://www.spigotmc.org/members/mlegok.92886/
Hello! I have a problem! I have read documentation, and i've found placeholder %proquests_progress_bar_questname%
How could i change that string to get the progress bar of any active quest, not certain? Cause players do the quests and they need the progress bar of active quest. If i leave this string like this, players will only get the progress of first quest, not the second and etc.

**Comment by JCulley** [comment]
Hi, this is not possible as players can have many quests active.

Additionally issues are not for questions, they are purely for errors or suggestions. If you do not follow the format in the future your tickets will be closed without a response.

**Comment by mlegok12** [comment]
So, can i ask you about condition? Player selected 3 quests and Progress bar will show the progress only  for the FIRST selected quest? And then he should do the second quest, and it will show it's progress bar, and after that he will do the third quest and etc.. The progress bar will be showen only for 1 quest! It will be a perfect function of plugin.
I need it quickly, so can i pay for it and you do this function for me in PM?
