### ISSUE TITLE
Two problems need to be improved

### ISSUE THREAD

**Issue by AntiThesis1250** [JCulley/ProQuests-Documentation#337]
1."Packages" should reset the task cooling in the previously accepted package when resetting

2.There are some problems in the detection of ProQuest's task of getting items. Sometimes the item can not be detected, sometimes the wrong item will be deducted

If this problem is solved, I will buy "tournaments"

**Comment by AntiThesis1250** [comment]
![QQ截图20200218233831](https://user-images.githubusercontent.com/31405319/74751285-fdd78f00-52a7-11ea-9953-19cab4624626.png)
When the task is completed, ProQuest will take the items from this location first, whether it is the required items or not

**Comment by AntiThesis1250** [comment]
Sometimes I have enough items, but I can't finish the task

**Comment by AntiThesis1250** [comment]
When prompted that I don't have enough items, I put the required items in the position in the picture, and the task can be completed

**Comment by JCulley** [comment]
Hi,

This doesn’t follow either the error format or the suggestion format. Please keep issues to a single specific topic. I’m going to close this, feel free to open these issues individually with the proper format.

Additionally please refrain from commenting multiple times and try to provide as much information up front as possible.
