### ISSUE TITLE
On the improvement of "package" function

### ISSUE THREAD

**Issue by AntiThesis1250** [JCulley/ProQuests-Documentation#339]
**Details** - I hope that each quest in the quest package can only be completed once before the reset
And can start immediately after the package is reset

**Additional information** -But using "duration" or "repeat delay" can cause two problems: 
   After packet reset:
1. The "repeat delay" does not end, and the task cannot start
2. The "duration" is not over, and the task is still in progress

**Comment by JCulley** [comment]
Can you please format this using the provided feature request template. Also I still don’t follow what the actual suggestion is here, can you please clarify as to what you mean. I don’t understand what you mean when you say “ the player may not see the task” or what you are referring to when you say “cooling state”, packages simply randomizes the specific quest based on a list of options.

**Comment by AntiThesis1250** [comment]
> Can you please format this using the provided feature request template. Also I still don’t follow what the actual suggestion is here, can you please clarify as to what you mean. I don’t understand what you mean when you say “ the player may not see the task” or what you are referring to when you say “cooling state”, packages simply randomizes the specific quest based on a list of options.

Is this format OK?

**Comment by AntiThesis1250** [comment]
> Can you please format this using the provided feature request template. Also I still don’t follow what the actual suggestion is here, can you please clarify as to what you mean. I don’t understand what you mean when you say “ the player may not see the task” or what you are referring to when you say “cooling state”, packages simply randomizes the specific quest based on a list of options.

Is this format OK?

**Comment by JCulley** [comment]
I don’t think it’s necessary to cancel the previous quest if the package is cycled, there are many scenarios where people may not want this functionality.
