### ISSUE TITLE
Progress bar of quest continues to fill

### ISSUE THREAD

**Issue by mlegok12** [JCulley/ProQuests-Documentation#340]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - {insert here}
https://www.spigotmc.org/members/mlegok.92886/

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - Last Version
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - Paper 1.13.2 Last version
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator

**Additional information** - Hi, my friend! Now i have a problem with your plugin
When you do some quests, for example, placeholder quest. Craft 5 TNT, 5 PISTONS
if i craft more tnt (more than 5, for example 10) the progress bar continues to fill. In normal case he should stop filling
As the same i have problem with another type of questions for example Mob kill quest. I have to kill 10 sheep, 10 zombie, 10 pig
If i kill more than 10 sheeps the progress bar also continues to fill but he mustn't do it.
<br>

**Comment by mlegok12** [comment]
Quest config:
type: PLACEHOLDER_QUEST
team: SOLO
duration: 0
repeat_delay: 0
repeatable: true
cancelable: true
command_start: false
command_join: false
check_all: false
cancel_after_timer: true
editable: false
disabled: false
join_active: false
require_invite: false
author: f4d935bc-5e2e-38c9-96c7-d59d63cfa68b
start_actions:
- '[Title] &6Квест &fначался!'
complete_actions:
- '[Title] &aПоздравляем!;&7Награда: &6$&f&l10000'
- '[ConsoleCommand] eco give %player% 10000'
- '[AddPoints] 10'
cancel_actions:
- '[Title] &fКвест сброшен!;&7Начните задание &cзаново!'
required_quests: []
blacklisted_quests: []
allowed_worlds: []
blacklisted_worlds: []
allowed_regions: []
blacklisted_regions: []
complete_permissions: []
progress_actions: []
return_actions: []
invite_actions: []
kick_actions: []
start_values: true
required_placeholders:
- '%statistic_craft_item:TNT%;5.0'
- '%statistic_craft_item:PISTON%;3.0'
- '%statistic_craft_item:HOPPER%;3.0'

**Comment by mlegok12** [comment]
required_placeholders:
- '%statistic_craft_item:TNT%;5.0'
- '%statistic_craft_item:PISTON%;3.0'
- '%statistic_craft_item:HOPPER%;3.0'

**Comment by mlegok12** [comment]
start_values: true

**Comment by JCulley** [comment]
You didn’t provide your log.

**Comment by mlegok12** [comment]
23.02 16:35:24 [Server] INFO Mob Spawn Range: 4
23.02 16:35:24 [Server] INFO Experience Merge Radius: 3.0
23.02 16:35:24 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
23.02 16:35:24 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
23.02 16:35:24 [Server] INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
23.02 16:35:24 [Server] INFO Random Lighting Updates: false
23.02 16:35:24 [Server] INFO Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
23.02 16:35:24 [Server] INFO Max TNT Explosions: 100
23.02 16:35:24 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
23.02 16:35:24 [Server] INFO Item Despawn Rate: 6000
23.02 16:35:24 [Server] INFO Item Merge Radius: 2.5
23.02 16:35:24 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
23.02 16:35:24 [Server] INFO View Distance: 10
23.02 16:35:24 [Server] INFO Arrow Despawn Rate: 1200
23.02 16:35:24 [Server] INFO Zombie Aggressive Towards Villager: true
23.02 16:35:24 [Server] INFO Nerfing mobs spawned from spawners: false
23.02 16:35:25 [Multicraft] Skipped 126 lines due to rate limit (30/s)
23.02 16:35:25 [Server] INFO [Essentials] Enabling Essentials v2.17.0.0
23.02 16:35:25 [Server] INFO [Essentials] Attempting to convert old kits in config.yml to new kits.yml
23.02 16:35:25 [Server] INFO [Essentials] No kits found to migrate.
23.02 16:35:25 [Server] INFO [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
23.02 16:35:25 [Server] INFO [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.
23.02 16:35:25 [Server] INFO [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
23.02 16:35:26 [Server] INFO [Essentials] Loaded 20977 items from items.json.
23.02 16:35:26 [Server] INFO [Essentials] Using locale en_GB
23.02 16:35:26 [Server] INFO [Essentials] ServerListPingEvent: Spigot iterator API
23.02 16:35:26 [Server] INFO [Essentials] Starting Metrics. Opt-out using the global bStats config.
23.02 16:35:26 [Server] INFO [Vault] [Vault][Economy] Essentials Economy hooked.
23.02 16:35:26 [Server] INFO [Essentials] Using Vault based permissions (LuckPerms)
23.02 16:35:26 [Server] INFO [HolographicDisplays] Enabling HolographicDisplays v2.3.2
23.02 16:35:26 [Server] INFO [HolographicDisplays] Enabled player relative placeholders with ProtocolLib.
23.02 16:35:26 [Server] INFO [TitleManager] Enabling TitleManager v2.1.5*
23.02 16:35:26 [Server] INFO [ProQuests] Enabling ProQuests v2.1.1.15
23.02 16:35:26 [Server] INFO [ProQuests] Running build #92886
23.02 16:35:27 [Server] INFO [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
23.02 16:35:27 [Server] INFO [ProQuests] Loading external plugin hooks....
23.02 16:35:27 [Server] INFO [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into advanced_envoys
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into askyblock
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into auction_gui_plus
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into auction_house
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into auctions
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into autorank
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into autosell
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into battle_levels
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into buycraft
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into chat_reaction
23.02 16:35:27 [Server] INFO [ProQuests] Successfully hooked into citizens
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into crate_keys
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into crazy_crates
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into custom_bosses
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into custom_shops
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into dailybonus
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into ez_blocks
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into ez_ranks
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into factions
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into factions_uuid
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into gangs_plus
23.02 16:35:27 [Server] INFO [ProQuests] Successfully hooked into holographic_displays
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into jobs
23.02 16:35:27 [Server] INFO [ProQuests] Unable to hook into lucky_blocks
23.02 16:35:32 [Multicraft] Skipped 72 lines due to rate limit (30/s)
23.02 16:35:32 [Server] INFO [ProQuests] Unable to locate any npcs to load...
23.02 16:35:32 [Server] INFO [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
23.02 16:35:32 [Server] INFO [ProQuests] Loading menus...
23.02 16:35:32 [Server] INFO [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
23.02 16:35:32 [Server] INFO [ProQuests] Unable to load the '1' menu as it is not an eligble menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'default' menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'monthly-leaderboard' menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'default3' menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'completed-leaderboard' menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'lifetime-leaderboard' menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'kronika' menu
23.02 16:35:32 [Server] INFO [ProQuests] Unable to load the 'tournament' menu as it is not an eligble menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'pvp' menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'subbota' menu
23.02 16:35:32 [Server] INFO [ProQuests] Succesfully loaded the 'weekly-leaderboard' menu
23.02 16:35:33 [Server] INFO [LeaderHeads] Enabling LeaderHeads v3.1.8.3*
23.02 16:35:33 [Server] INFO [LeaderHeads] Cracked by t0R
23.02 16:35:33 [Server] INFO [LeaderHeads] Loaded automatic reward: kills
23.02 16:35:33 [Server] INFO [LeaderHeads] Loaded automatic reward: votes
23.02 16:35:33 [Server] INFO [LeaderHeads] Hooked into Citizens
23.02 16:35:33 [Server] INFO [LeaderHeads] Hooked into HolographicDisplays
23.02 16:35:34 [Server] INFO [PlaceholderAPI] Placeholder expansion registration initializing...
23.02 16:35:34 [Server] INFO [PlaceholderAPI] Successfully registered expansion: statistic
23.02 16:35:34 [Server] INFO [PlaceholderAPI] Successfully registered expansion: vault
23.02 16:35:34 [Server] INFO [PlaceholderAPI] Successfully registered expansion: player
23.02 16:35:34 [Server] INFO [PlaceholderAPI] Successfully registered expansion: math
23.02 16:35:34 [Server] Startup Done (9.908s)! For help, type "help"
23.02 16:35:34 [Server] INFO Timings Reset
23.02 16:35:34 [Server] INFO [HolographicDisplays] Found a new version available: v2.4.1
23.02 16:35:34 [Server] INFO [HolographicDisplays] Download it on Bukkit Dev:
23.02 16:35:34 [Server] INFO [HolographicDisplays] dev.bukkit.org/bukkit-plugins/holographic-displays
23.02 16:35:34 [Server] INFO [Citizens] Loaded 1 NPCs.
23.02 16:35:34 [Server] INFO [PlaceholderAPI] An update for PlaceholderAPI (v2.10.4) is available at:
23.02 16:35:34 [Server] INFO [PlaceholderAPI] https://www.spigotmc.org/resources/placeholderapi.6245/
23.02 16:35:34 [Server] INFO [Vault] Checking for Updates ... 
23.02 16:35:34 [Server] INFO #------------------- Chest Commands Errors -------------------#
23.02 16:35:34 [Server] INFO 1) Invalid YAML configuration for the menu "itemshop.yml". Please look at the error above, or use an online YAML parser (google is your friend).
23.02 16:35:34 [Server] INFO 2) The menus "donate.yml" and "menu.yml" have the same command "menu". Only one will be opened.
23.02 16:35:34 [Server] INFO 3) The icon "madona11" in the menu "prefix-2.yml is overriding another icon with the same position.
23.02 16:35:34 [Server] INFO 4) The icon "oras121111" in the menu "shop (2).yml is overriding another icon with the same position.
23.02 16:35:34 [Server] INFO #-------------------------------------------------------------#
23.02 16:35:34 [Server] INFO [Vault] No new version available
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-turtle
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-phantom
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-cod
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-salmon
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-pufferfish
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-tropicalfish
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-drowned
23.02 16:35:35 [Server] INFO [LeaderHeads] Statistic is not in list, adding it: va-dolphin
23.02 16:35:35 [Server] INFO [PlaceholderAPI] 167 placeholder expansions are available on the cloud.
23.02 16:35:35 [Server] INFO [PlaceholderAPI] 2 installed expansions have updates available.
23.02 16:36:05 [Server] INFO CONSOLE issued server command: /list 
23.02 16:36:36 [Server] INFO CONSOLE issued server command: /list 
23.02 16:37:08 [Server] INFO CONSOLE issued server command: /list 
23.02 16:37:39 [Server] INFO CONSOLE issued server command: /list 
23.02 16:38:10 [Server] INFO CONSOLE issued server command: /list 
23.02 16:38:41 [Server] INFO CONSOLE issued server command: /list 
23.02 16:39:13 [Server] INFO CONSOLE issued server command: /list 
23.02 16:39:44 [Server] INFO CONSOLE issued server command: /list
