### ISSUE TITLE
1.7.10 paper spigot not working

### ISSUE THREAD

**Issue by franklintra** [JCulley/ProQuests-Documentation#344]
**Spigot Account**
https://www.spigotmc.org/members/ttgaming.491218/
**Spigot account** - {insert here}
<br>
**Plugin Version**
Latest
**Plugin version** - {insert here}
<br>
**Spigot Version** - PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar
<br>
**Link to log file** - https://hastebin.com/badogacudu.shell
<br>
**Additional information
No configuration at all gives me this error with proquests when I use command /quests

**Comment by JCulley** [comment]
Support for PaperSpigot is not provided.
