### ISSUE TITLE
issue with tame quest

### ISSUE THREAD

**Issue by Devillion** [JCulley/ProQuests-Documentation#47]
My spigot account: https://www.spigotmc.org/members/goflish.21294/
Using latest 1.12.2 spigot version
pastebin file: https://pastebin.com/w3sH1QKi

When I select Allowed Types for (tame quest) and then I typed, "HORSE" into chat this is what I get: https://i.imgur.com/W7OvypH.png

Someone else on my discord is having the same issue, so it's not just me.

**Comment by iKingM** [comment]
I have the same problem.

**Comment by iKingM** [comment]
where is the author ?
