### ISSUE TITLE
Error with placeholdersAPI and proquests

### ISSUE THREAD

**Issue by maxlehot1234** [JCulley/ProQuests-Documentation#51]
Hi,

I get this error in the console for no reason that spam the console.

https://hastebin.com/iwayanehug.css

Spigot profile: https://www.spigotmc.org/members/maxlehot1234.6658/
ProQuests 2.0.3.3
Java 8
PaperSpigot: 
![image](https://user-images.githubusercontent.com/5159244/34363884-f1f52b76-ea4d-11e7-8fa1-c8d024e0ef66.png)

I have: PlaceholderAPI 2.8.2

Thank you so much and happy holidays.

**Comment by JCulley** [comment]
You have not provided your log file.

**Comment by maxlehot1234** [comment]
What is the hastebin link? It contain the ONLY error I have...




mercredi 3 janvier 2018 17:27 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by JCulley** [comment]
As is clearly stated in the guidelines please provide your ENTIRE log file.

**Comment by maxlehot1234** [comment]
To reveal our server plugins? Not a good thing :( 




mercredi 3 janvier 2018 20:13 -0500 de notifications@github.com  <notifications@github.com>:
