### ISSUE TITLE
Internal error when open a menu

### ISSUE THREAD

**Issue by iKingM** [JCulley/ProQuests-Documentation#54]
Link to spigot account : https://www.spigotmc.org/members/weshcanneapeche.49778/
Plugin version : 2.0.3.3
Spigot version : 1.8.8
Link to log : https://pastebin.com/2XTUyrUj

When I want to open a menu with the command /quest menu (name of the menu) there is the following message in the chat :  "An internal occurred ...."

**Comment by JCulley** [comment]
You only sent me the startup for ProQuests which is useless to me. Please provide the entire log (startup to present time) otherwise I have no way to resolve your issue. This is more than likely a configuration issue.

**Comment by iKingM** [comment]
the log with the error : https://pastebin.com/by5bKcvq

**Comment by JCulley** [comment]
> Please provide the entire log (startup to present time)

**Comment by iKingM** [comment]
https://pastebin.com/XWUMxHKU

**Comment by JCulley** [comment]
You have a quest with complete actions that are null, so its throwing the error. Fix this and you'll be fine. I will add a failsafe for this in the future although I don't understand why you would leave a complete action value as null.
