### ISSUE TITLE
Command Not Working

### ISSUE THREAD

**Issue by TheKillHDmc** [JCulley/ProQuests-Documentation#55]
My spigot account: https://www.spigotmc.org/members/thekillhd.29836/
Using PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
pastebin file: https://i.gyazo.com/b8d1d81451f53b2c16a0a37fb794d214.png

I tried the command /proquests player quest KCP_TaacTicx start quete3 but it's not working 
My quests : https://i.gyazo.com/7becf5d6cd9eda711ad4e91e41bf887b.png

**Comment by JCulley** [comment]
Doesn’t follow guidelines, and that just means the quest does not exist or was not loaded properly due to a configuration error. Use the in-game editor for creating quests.
