### ISSUE TITLE
ProQuest - quest npc error when reloaded quest

### ISSUE THREAD

**Issue by minepaoz** [JCulley/ProQuests-Documentation#56]
- Spigot Version: TacoSpigot-1.8.8-latest
- java  jre 8 64bit
when i created Quest and npc Its work
but when i reload quest
npc and quest is not linked
i don't know what i can tell with you but i uploaded errors
Take a look this video
http://mc-challenge.net/Bugsreport/ProQuest.mp4

**Comment by JCulley** [comment]
No profile link, no server log, not detailed enough as I really don’t even understand what you’re trying to say. Follow the guidelines if you wish to reopen with a proper description https://github.com/JCulley/ProQuests-Documentaion/wiki/Error-Guidelines
