### ISSUE TITLE
Suggestion : BattleLevels

### ISSUE THREAD

**Issue by iKingM** [JCulley/ProQuests-Documentation#57]
Spigot account : https://www.spigotmc.org/members/weshcanneapeche.49778/

Hello,
I am writing to know if you could add to your plugin the update of the following plugin : 

- BattleLevels : https://www.spigotmc.org/resources/battlelevels.2218/
Currently the version of BattleLevels accepted by Proquests is 6.9.1 and the latest version of this existing plugin is 8.2.2.
I've created a lot of quest with BattleLevels and I do not think I'm the only one using this plugin with Proquests so I think it would be nice to adapt version 8.2.2 with Proquests

Thanks in advance for your answer

iKingM

**Comment by JCulley** [comment]
As it is a premium resource the author would have to be willing to provide me a copy of the plugin. I will ask him however I cannot guarantee anything.
