### ISSUE TITLE
ASync

### ISSUE THREAD

**Issue by PepRally01** [JCulley/ProQuests-Documentation#58]
https://www.spigotmc.org/members/peprally.488151/
I am using PaperSpigot 1.8.8
https://pastebin.com/Gqc11HcV

Hello,
I got ProQuests for my server and I am having a problem with Async. Whenever more than 1 players join the game, the server stops working and crashes. This problem first originated after I got ProQuests.

**Comment by JCulley** [comment]
You will not receive support for old version.
