### ISSUE TITLE
Can You Fix ProQuests NPC not save data?

### ISSUE THREAD

**Issue by minepaoz** [JCulley/ProQuests-Documentation#59]
- Spigot version: TacoSpigot-1.8.8-latest
- Java version: Java Runtime Environment 8 (64Bit)
ProQuests version: 2.0.3.3
Citizens version: 2.0.16-SNAPSHOT
---------------------------------------------------------------
For Reason 
Please take a look My Video:
http://www.thunpao.me/Bugsreport/ProQuest.mp4

**Comment by JCulley** [comment]
Does not follow the guidelines.

**Comment by minepaoz** [comment]
I have not bought a week yet. It's expensive. And I had a bad experience.
I bought several premium plugins already. He always helped me when I was having trouble explaining, suggesting, and fixing problems.

**Comment by minepaoz** [comment]
I'm not English People I may not be able to understand your language easily. But.. Thank you for the answer.
