### ISSUE TITLE
Problem with already started quests

### ISSUE THREAD

**Issue by iKingM** [JCulley/ProQuests-Documentation#60]
Link to spigot account : https://www.spigotmc.org/members/weshcanneapeche.49778/
Plugin version : 2.0.3.3
Spigot version : 1.8.8
Link to log : https://pastebin.com/CyattfCU

I noticed a problem when we disconnect from the server with a quest already started.
When we return to the server we can not complete the quest

Example: My quest is "break 10 blocks"
I start the quest then I break 5 blocks and I disconnect.
When I come back and I break 5 blocks the quest does not end.

**Comment by JCulley** [comment]
1) That’s not your whole log as there is no evidence of anyone joining or leaving
2) I personally just tested this on a test server with no issues/errors so I would need more information
