### ISSUE TITLE
Problem with already started quests

### ISSUE THREAD

**Issue by iKingM** [JCulley/ProQuests-Documentation#61]
Link to spigot account : https://www.spigotmc.org/members/weshcanneapeche.49778/
Plugin version : 2.0.3.3
Spigot version : 1.8.8
Link to log : https://pastebin.com/u2RJi7C6

I noticed a problem when we disconnect from the server with a quest already started.
When we return to the server we can not complete the quest

Example: My quest is "to kill 25 sheeps"
I start the quest then I kill 17 sheeps and I disconnect.
When I come back and I kill 8 sheeps the quest does not end.

You can see in this log (https://pastebin.com/rQLxNQzm) that I kill 25 sheeps but the quest does not finish.

**Comment by JCulley** [comment]
As I had previously stated in your last issue you had opened I have tested this on a private test server with it properly tracking the kills/progress even on logout. You have provided no extra information relating to this issue but instead tried to explain to me how 17+8=25 (which is rather obvious) so I have no choice but to close it.
