### ISSUE TITLE
No quest record creation

### ISSUE THREAD

**Issue by sad10x** [JCulley/ProQuests-Documentation#63]
Step 1: Edit a quest.
step 2: choose an option (example: command start)
Step 3: save creation
Message: you have successfully created the quest: XXX

test: / quests start XXX
result: you connot strart this quest via command

Step 4: Edit the same quest
Step 5 (Check): No actions between "Step 1 and 4" have been recorded.

**Comment by JCulley** [comment]
I have absolutely no clue what this is regarding. Follow the guidelines if you want a response.

**Comment by sad10x** [comment]
profil:
https://www.spigotmc.org/members/sadx.282080/
plugin: 2.0.3.3
[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-7754231-9a1f5ee (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

A PLAINTEXT WEBSITE =>? ? ? I can copy paste here if you want, I type A PLAINTEXT WEBSITE on google, I understood nothing, and I do not even know if what I saw corresponds to your request.)
