### ISSUE TITLE
does not save changes

### ISSUE THREAD

**Issue by sad10x** [JCulley/ProQuests-Documentation#64]
profil: https://www.spigotmc.org/members/sadx.282080/
plugin: 2.0.3.3
[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-7754231-9a1f5ee (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
why ask for the version of the server? It is the first line of the log
https://pastebin.com/ikUQNPdQ

Step 1: Edit a quest.
step 2: choose an option (example: command start)
Step 3: save creation
Message: you have successfully created the quest: XXX

step 4: test: / quests start XXX
result: you connot start this quest via command

Step 5: Edit the same quest
Step 6 (Check): No actions between "Step 1 too 3 " not been registered

And since the Google translation of your message was:
I do not see where the problem is (google translation + interpretation)

So I specify (although it may seem normal) but I tend to believe that when I click on "save", well it records!
But if you re-read my "step" you will understand "where the problem is"

And finally, a bit of civility.
That I took 1 hour just to translate your request / understands, having to try to put a problem as clearly as possible ((step 1 2 ...)
And this see closing the application, while just leave open waiting for useful items.
It's rude, badly polite, and rest his contempt on a simple "I'm not obliged to help you" is to forget that any service / machine / has a share of after sales.
Unless you consider that your work is flawless, perfect, without reproach, and that the quintessence of purity passes through your fingers during coding.

Knowing that as a user, I am not exempt from error, I remain humble and ask for a cordial exchange to help me understand why I have this problem.
Thank you

**Comment by JCulley** [comment]
You still have very portly described your “error” and have provided me something in which I basically have nothing to work with. If you could provide your files or anything of actual use to me other than a statement that would be fantastic.

**Comment by sad10x** [comment]
At the last news:
-You are demanding when it comes to having an after-sales service.
Certainly, I'm complying.
And so I provided what he asked me to start this discussion.
And your answer is (charming and very adult):

Give me useful files.


As far as I know, if I have a hard time translating / interpreting your queries, it's not to guess the "useful files" that you want.
So, I propose, one more faith, in this courtesy that characterizes us:
What do you want as a file, info?

  Know that all this will be recorded in case of dispute Paypal, to prove that your software is defective, and that I tried, really, to solve the problem.
So let's try, please, not to come to such actions.
I just want to know the procedure to follow, the information you want to solve this problem.

Just keep in mind:
-I translate everything on google, which makes interpretation difficult (and sometimes changes sentences)
-I am not a computer scientist, I will do my best to put together the information you request.

Thanks in advance (google translation)

**Comment by JCulley** [comment]
Hey, 

So I don’t really know how I’ve been “demanding” however if you want support and help usually you have to provide the requested information. I don’t believe this is a odd request regardless if you can translate it or not, if you cannot provide sufficient information to assist you how would you expect me to do so?

Please provide the file for the quest in which you believe is somehow not working. I still don’t understand what your problem even is you you have not adequately described the problem.

You don’t have to continually say that you have to translate everything, it really doesn’t make a difference as English responses are the only ones you will recieve from me.

Now as per you threatening with a PayPal dispute that will not be tolerated and if you continue to badger me with these various digs you have (which is rather surprising for someone who’s having an issue translating) then you will not be receiving any support whatsoever. Which when purchasing any resources on Spigot MC you are acknowledging you may not receive any to begin with. I do this as a courtesy to fix any potential issues, I am under no obligation to do so, please remember this.

So I’m conclusion please provide an adequate description which fully explains the issue along with whatever files you may be referencing causing said issue. Thanks.

**Comment by sad10x** [comment]
definition of harassment: Attacks or ongoing solicitations in order to exhaust or torment the victim.
I do not harass you.

In terms of reimbursement, there are your terms and conditions, and there is law.
Selling a program that does not do what it says is a scam.

So I repeat, what is the file you want?
It's not telling me to give you a file for each answer that I'm not going to guess which one. You are the creator of this program, so you know what you use to understand the problem. Not me.

I repeat my problem:

-I create a quest.
- step 2: I edit this quest by activating the "command start" parameter
- I click on "save creation"
I have the confirmation message: you have successfully created the quest: XXX (xx is a generic name for the example)

I test: / quests start XXX
the program:: you connot start this quest via command
(so it does not work)
For a reader to understand the problem: the command start option allows to launch the quest via a command. (what I do in the test)

I return to edition mode of the XXX quest
The "command start" option is not activated. while I activated it (step 2) and your program meant that the quest was: "you have successfully created the quest"

My problem: I activate an option of the program, and it does not take it into account.

Which file do you want for this problem?

**Comment by JCulley** [comment]
> You are demanding when it comes to having an after-sales service.

> And your answer is (charming and very adult)

> Know that all this will be recorded in case of dispute Paypal, to prove that your software is defective

> But if you re-read my "step" you will understand "where the problem is"

> Unless you consider that your work is flawless, perfect, without reproach, and that the quintessence of purity passes through your fingers during coding.

If this is not condescending and abundantly rude when speaking to someone who you expect to help you, I don't know what is.

From your log it can be seen you have somehow modified in a way which produces an error preventing it from loading. `[00:45:46] [Server thread/INFO]: [ProQuests] Unable to load the 'lune' quest`

Having just created a brand new quest on my own private server I had no issues modifying it using the in-game editor and could start it without issue. Consider this issue closed, and without providing more information to adequately explain any future issue you may not receive a response.

All the best.

**Comment by sad10x** [comment]
Pour paypal:

Il faut savoir que la modification de quête est exclusivement basé sur une interface graphique simple: 
Un bouton: active une option.
Dire que mes actions ont engendré une erreur signifie donc que son programme a une erreur, car je n'utilise que son interface propres.

Si besoins de preuve, j'ai enregistrer ses autres réponses a d'autres utilisateur, prouvant qu'il ne résoud pas les erreur, mais ce contente de clôturer les demandes en rejetant la faute sur l'utilisateur.
Ce message est unilatéral, car Jculley a clôturer notre discuter, et donc, ne le liera pas.
