### ISSUE TITLE
ProQuests not working

### ISSUE THREAD

**Issue by PepRally01** [JCulley/ProQuests-Documentation#65]
https://www.spigotmc.org/members/peprally.488151/
I am using PaperSpigot 1.8.8
https://pastebin.com/X51p6Q4s

Hello,
I don't know what is going on. I can't use any ProQuests commands. I just updated ProQuests so it shouldn't be that.

Thanks,
PepRally

**Comment by JCulley** [comment]
Fixed, please update to the newest version. If the issue persists please feel free to open another issue. https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=206488
