### ISSUE TITLE
 NPC is not recognized

### ISSUE THREAD

**Issue by nuangtr** [JCulley/ProQuests-Documentation#66]
Error : https://youtu.be/xVQJX9MAQ9Q
Spigot account:  https://www.spigotmc.org/members/nuangwaneiei.175306/
Proquest version : 2.0.3.4
Server version : CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)  You are 42 version(s)
Log : https://gist.github.com/nuangtr/54512fc8d1ca275e4a7dfeb0ce140e8e

Not working. I associate a new Quest to a NPC, and is not activating the quest.
If you restart the server, the NPC is not recognized.

**Comment by nuangtr** [comment]
All file proquests
https://www.dropbox.com/s/twdvywgdaeku0a5/All_File_ProQuests.rar?dl=0

**Comment by JCulley** [comment]
> [21:54:00] [Server thread/INFO]: [ProQuests] Unable to locate any npcs to load...

I can clearly see from your log that you have not registered any NPC's within the plugin so that would be why. If you don't define the NPC in ProQuests you cannot link it to any quests.

**Comment by nuangtr** [comment]
Thanks, I can use it
