### ISSUE TITLE
Problem with the leaderboard

### ISSUE THREAD

**Issue by Darkphenixs01** [JCulley/ProQuests-Documentation#68]
Spigot account: https://www.spigotmc.org/members/darkphenixs.40927/
There is a problem with the leaderboard.
I installed Proquest 2.0.3.4 without modifying the config with no other plugin, on a spigot-1.8.8-R0.1.
I connected 3 accounts on the server and I did the basic quests and when I /quest leaderboard,  it puts me 1 player out of 3 at random on the first 10.
There is no error in the console.
Log: https://gist.github.com/Darkphenixs01/41baddcf78ebcf015784a23041cd2136
How to fix this bug?
![2018-01-28_19 39 18](https://user-images.githubusercontent.com/35899335/35485712-b1284422-0463-11e8-9db6-c14b18000b08.png)

**Comment by JCulley** [comment]
I don’t understand what the issue is, if every player has the same amount of points then the database will randomly sort them.

**Comment by Darkphenixs01** [comment]
except that there is only 1 out of 3 in the leaderboard

**Comment by Darkphenixs01** [comment]
??

**Comment by JCulley** [comment]
Sorry I had forgotten about this issue being open. Just finished looking into it and have published a version fixing this issue. https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=210540
