### ISSUE TITLE
[WorldGuard Issue] I have an issue with allowed regions config

### ISSUE THREAD

**Issue by maxlehot1234** [JCulley/ProQuests-Documentation#69]
Hi,

I just want to report an issue I have with allowed region.

The plugin detect the player region and not the block region, so this cause a problem with allowed region config. If the player was outside a mine for example when breaking blocks, blocks are not count as break. Player need to be inside the region to break blocks inside the mine, so this was really bad for  prison server .
Check the video I made: https://youtu.be/zXfJqWyKR-g

My spigot account: https://www.spigotmc.org/members/maxlehot1234.6658/
I use ProQuests 2.0.3.5 version
I use PaperSpigot version:
![image](https://user-images.githubusercontent.com/5159244/36337129-98a4a8e2-135d-11e8-8090-da003f30d53c.png)
My server logs: ( i REALLY DON'T know why you need this for this type of issue, but here it is)  https://pastebin.com/kxpuQr1h
WorldGuard version I have: http://builds.enginehub.org/job/worldguard/10047

Hope you have a lot of informations in this issue.

If not, let me know if you need something else for it so I can provide more informations to you.

Thanks a lot and have a nice day/night to you

**Comment by maxlehot1234** [comment]
And @JCulley  Any idea for this issue?

Thanks again and sorry for the bump

**Comment by JCulley** [comment]
Hey,

This is not an issue and rather is designed this way to accommodate all quest types as it is a universal option for all quests based on the players location. The easiest solution is if you simply define a region for the mine including the bordering area.
