### ISSUE TITLE
Proquest tournament issue

### ISSUE THREAD

**Issue by Kira07** [JCulley/ProQuests-Documentation#73]
Hello, i'm not able to use proquests tournament, i'm using last version or proquests and running spigot 1.8.8.
Spigot : https://www.spigotmc.org/members/kira_07.24271/
Log : https://hastebin.com/uditijepeq.md

**Comment by Kira07** [comment]
Bump

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-tournaments-add-on.30049/update?update=220298
