### ISSUE TITLE
Problem witch reward leaderboard

### ISSUE THREAD

**Issue by Darkphenixs01** [JCulley/ProQuests-Documentation#75]
Spigot account: Darkphenixs01
Proquest Version: 2.0.3.5
Spigot Version 1.8.8
Log: https://github.com/Darkphenixs01/problem-reward-leaderboard/issues/1
Problem:
The Rewards leaderbeard are not given to the player.
And when the player is not connected at the time of udapte rewards his tells him his position with 0 points.

I did not touch the config.

Some Photos:
![2018-02-25_19 39 30](https://user-images.githubusercontent.com/35899335/36645264-41f6d17c-1a66-11e8-970a-3c2aa3732952.png)
![2018-02-25_19 39 32](https://user-images.githubusercontent.com/35899335/36645266-44a2c2a0-1a66-11e8-9950-7850d679e8a7.png)
![2018-02-25_19 40 15](https://user-images.githubusercontent.com/35899335/36645267-46d0ebf6-1a66-11e8-8f32-5d3ee3ca92ea.png)
![2018-02-25_19 40 32](https://user-images.githubusercontent.com/35899335/36645268-483b3b5e-1a66-11e8-8f64-a3c3fb58ddc7.png)

**Comment by JCulley** [comment]
If you didn’t change the config then it can be seen that the Diamonds/Emeralds are in your inventory and both players received their reward, I can look into it saying 0 points however it’s irrelevant in the rewards being given.
