### ISSUE TITLE
crashing the server after getting reward

### ISSUE THREAD

**Issue by eric2788** [JCulley/ProQuests-Documentation#77]
Spigot Account: https://www.spigotmc.org/members/caxerx.19956/
latest plugin version: yes
Spigot Version: Spigot 1.12.2 latest
Error Code: https://pastebin.com/HJKwCpJj

When I joined my server, it will be started two quests automatically, those are one-time quests and I am sure there isn't any option for starting a quest on join.When one of them has finished, it started crashing the server after getting reward, and appeared the error code as above.

my all external plugin version are both latest

**Comment by JCulley** [comment]
Please provide the entire log file or the issue will be closed.

**Comment by eric2788** [comment]
here's the full log
https://pastebin.com/Wt4xAFha

**Comment by JCulley** [comment]
So you had already opened an issue which I closed as it is due to your configuration. Has nothing to do with the plugin throwing any errors. https://github.com/JCulley/ProQuests-Documentation/issues/76
