### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by Hailethanh11** [JCulley/ProQuests-Documentation#78]
# ======================================================
# 
# ProQuests Version: 2.0.3.5 build: 27795
# Created by: JC_Plays_MC
# 
# ======================================================

type: KILL_MONSTER_QUEST
mobs: Zombie
total: 50
duration: 86400
repeat_delay: 86400
repeatable: true
cancelable: true
command_start: true
editable: true
start_actions:
- '[Title] &aNhiệm vụ bắt đầu;&7Nhiệm vụ: &7Nhiệm vụ: &2Giết 50 Zombies'''
complete_actions:
- '[Title] &bNhiệm vụ hoàn thành!;&7Thưởng: &a5 &9Points'
- '[ConsoleCommand] points give %player% 5
- '[AddPoints] 25'

**Comment by JCulley** [comment]
This doesn’t follow any guidelines and I have no clue what this is in reference to.
