### ISSUE TITLE
NPC is not recognized

### ISSUE THREAD

**Issue by mosza1999** [JCulley/ProQuests-Documentation#80]
Error : https://youtu.be/xVQJX9MAQ9Q
Spigot account: https://www.spigotmc.org/members/mosza1999.185467/
Proquest version : 2.0.3.5
Server version : CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Log : https://pastebin.com/69Ee9feK

Not working. I associate a new Quest to a NPC, and is not activating the quest.
If you restart the server, the NPC is not recognized.

The same problem with the nuangtr player. So I borrowed his video.
My version is 1.8.8. I can not upgrade citizen to 2.0.22.

**Comment by JCulley** [comment]
You never created any NPC’s in ProQuests 

“[18:10:20] [Server thread/INFO]: [ProQuests] Unable to locate any npcs to load...”

**Comment by mosza1999** [comment]
# ======================================================
# 
# ProQuests Version: 2.0.3.5 build: 185467
# Created by: JC_Plays_MC
# 
# ======================================================

npc_type: MENU
author: 4de3d122-8685-3fa7-8f61-0e686adc1c4b
editable: false
entity_type: PLAYER
name: testnpc
location: world,-247.5519,10.0000,1706.5164
citizen: 2771b628-c3ac-40de-ab57-9cf5daab1007
menu: default

**Comment by mosza1999** [comment]
I already created, but the plugin does not save it.
