### ISSUE TITLE
"use_folders: true" Error

### ISSUE THREAD

**Issue by mosza1999** [JCulley/ProQuests-Documentation#81]
Error : use_folders in config.yml
Spigot account: https://www.spigotmc.org/members/mosza1999.185467/
Proquest version : 2.0.3.5
Server version : CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Log1 : https://pastebin.com/69Ee9feK
Log2 : https://pastebin.com/dSQP80De

1. use_folders: true
[Server thread/INFO]: [ProQuests] Unable to locate any npcs to load...
when use command /quest reload. Data in Npcs floder will be lost immediately.

2. use_folders: false
Plugins can work normally.

Please consider
If the error message apologized. Sorry to annoy you
Thank you.

**Comment by JCulley** [comment]
“IF YOU OPEN MORE THAN 1 ISSUE EVERY 24 HOURS YOU WILL BE BLOCKED FROM INTERACTING WITH THIS REPOSITORY“

**Comment by mosza1999** [comment]
You do not think to fix it. And do not think to answer me?

**Comment by JCulley** [comment]
I will respond/address any “issues” once you stop spamming me with messages, and you uphold the guidelines in place.

**Comment by mosza1999** [comment]
I follow the rules you set. But my problem is still there.  T_T
