### ISSUE TITLE
Quest start auto

### ISSUE THREAD

**Issue by mosza1999** [JCulley/ProQuests-Documentation#82]
Error : Quest start auto (OP Player)
Spigot account: https://www.spigotmc.org/members/mosza1999.185467/
Proquest version : 2.0.3.5
Server version : CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Log : https://pastebin.com/5vcd5jx9
config : https://pastebin.com/dRsXFDVQ

Players with OP access to the server. Quests will start automatically. (I did not order it to run automatically.)
(Normal player quest does not start automatically.)
Do you have a way to fix. Don't start a quest automatically. When players with op access the server?
Thank you..

**Comment by JCulley** [comment]
You should read the permissions page, it clearly states that if a player has the permission to auto start a quest it will. So either don’t OP your players or negate the autostart permission.

**Comment by mosza1999** [comment]
I did not enter the autostart permission for admin.

**Comment by JCulley** [comment]
You should look into what giving someone operator status does before you give it to someone. If you are defined as an operator you are given all of the permissions unless you forcefully negate it using your permission plugin/manager.
