### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by dewobedil** [JCulley/ProQuests-Documentation#83]
**My spigot Account:** https://www.spigotmc.org/members/dewobedil.64311/
**ProQuest plugin version:** 2.0.3.5
**Spigot version:** CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Error logs:** https://pastebin.com/vRd6MpdE
**Error Information:** 
When i fresh install plugin and new database , this error appear. 

1. Quest not get progress when tool have damage, but when i got new fresh tool the progress continue
2. Saving ingame editor not change anything
3. /quest reset all not working (there is no demo in the video)

here is the video to explain and easy you to understand too.
https://youtu.be/elSM72Hq7e0

I think this bug appear because maybe the plugin trying to check the durability too hmm

**Comment by JCulley** [comment]
The log file is not optional, either provide it or I will have no choice but to close the issue.

**Comment by dewobedil** [comment]
Here is full latest.log
https://pastebin.com/vRd6MpdE

**Comment by dewobedil** [comment]
I got it fixed , it seems your plugin trying to create in_hand: config using 
data: 0

 instead 

data:-1

if i set data: 2 , the quest will count if the weapon got damage the third one or got durabilty 3

**Comment by JCulley** [comment]
It sets the default value to 0 when using the in-game editor as it is simply taking the data value of the item you supplied, which in this case is 0. As per the enchantments being produced with an invalid format I would have to look into it. Finally you mentioned:

> saving the data ingame and /quest reset all still not working

This doesn't make any sense to me trying to interpret and have yet to hear any issues regarding the reset command. If you could please elaborate and try to explain it that would be greatly appreciated.

**Comment by dewobedil** [comment]
Thank you!
and here is the preview

![preview](https://media.giphy.com/media/OStqpIWlf5jnXOwasI/giphy.gif)

**Comment by dewobedil** [comment]
found another bug about OBTAIN_QUEST
my quest config https://pastebin.com/LTdKGhLy
my menu config https://pastebin.com/Qr5evnP0

but when i start the quest the progress will be N/A and the quest cant get any progress
![preview](https://i.imgur.com/2NyySYR.png)

all of this created ingame

**Comment by JCulley** [comment]
It can only be executed from console due to it being a command which deletes all of the data (also requires a verification).
