### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by JuraGamer** [JCulley/ProQuests-Documentation#84]
please help me my ip server is fptcraft.com

https://cdn.discordapp.com/attachments/309655245313671168/424566782909612042/2018-03-17_205626.png

**Comment by JCulley** [comment]
https://github.com/JCulley/ProQuests-Documentation/wiki/Error-Guidelines

**Comment by JuraGamer** [comment]
The plugin doesn't work

https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/
