### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by JuraGamer** [JCulley/ProQuests-Documentation#85]
The plugin doesn't work. I have tried all the way, updated the latest version install the related plugin but it still does not work
https://www.spigotmc.org/members/bivipvnkg0.287465/

**Comment by JCulley** [comment]
This still does not follow the guidelines. Please update and provide **relevant** information or this issue will be closed.

**Comment by JuraGamer** [comment]
I am very difficult to communicate with you, what I need is why this plugin does not work

**Comment by JuraGamer** [comment]
When /pl then it has the red "ProQuests" plugin.

**Comment by JCulley** [comment]
This is your last opportunity to follow the guidelines by providing the server log, a valid description of the issue (not just "when /pl then "ProQuests" plugin it has the red). What you have provided is of no use to me, and I cannot help you unless you provide more information. So please do so.

**Comment by JuraGamer** [comment]
I Have used cracked Plugin before , i think you were knowing that you blocked my server , and then i bought your plugins , why are you stills blocking my server

**Comment by JuraGamer** [comment]
I used to have trouble with Plugin before, I think you already know that you blocked my server and then I bought your plugin so you can block it

**Comment by JuraGamer** [comment]
I am Vietnamese, so I can not understand English

**Comment by JuraGamer** [comment]
Since I am Vietnamese, I can not understand English

**Comment by JuraGamer** [comment]
I have overcome it, thank you wish you a good day
