### ISSUE TITLE
Backup system

### ISSUE THREAD

**Issue by dewobedil** [JCulley/ProQuests-Documentation#87]
Hello we need backup system when the plugin trying to reload the config but it fail. Then the plugin create backup for you for last known good config.

Thank you,
regards dewobedil

**Comment by JCulley** [comment]
Will consider this however you can already use the in-game editor to avoid this issue completely. If you choose to edit he config yourself you should really be testing it with a YAML validated first.

**Comment by dewobedil** [comment]
yeah of course , i know how to avoid this but that feature will help many people. because i once accidenly got all quests removed because 1 parse error lol

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=226243
