### ISSUE TITLE
Spawn reason

### ISSUE THREAD

**Issue by dewobedil** [JCulley/ProQuests-Documentation#88]
We need this feature to be implemented, its really useful condition to let you set the quest to kill zombie from how they spawn (NATURAL, SPAWN_EGG,etc)

spigot docs: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html

**Comment by JCulley** [comment]
I will consider this however it would require complete refactoring of mob quests which would break all existing quests which is not ideal.

**Comment by JCulley** [comment]
Its been quite some time since this was suggested, I don't have time to do major refactoring so I'm going to close this issue.
