### ISSUE TITLE
MYSQL not work.

### ISSUE THREAD

**Issue by nuangtr** [JCulley/ProQuests-Documentation#89]
Error: https://gist.github.com/nuangtr/c21ebf77590ed10386aec3162aea6628
Log: https://gist.github.com/nuangtr/771762bba2f0f46c64e4cf737c901fec
Spigot account: https://www.spigotmc.org/members/nuangwaneiei.175306/
I use the last version of ProQuests  2.0.3.5
Server version : CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by dewobedil** [comment]
read this description
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

you know what to do and double check i think

**Comment by JCulley** [comment]
You database is configured with too much overhead (most likely due to the encoding you type have specified), something you can easily change on your databases end.
