### ISSUE TITLE
Automatically start all quests

### ISSUE THREAD

**Issue by Tyloonie** [JCulley/ProQuests-Documentation#90]
Hello! Just came back to check out all updates on the plugin, damn it has become something epic.

I am however wondering about something... My friend and I would like to make a server with somewhat remarkable achievements. I know there is an achievement plugin for this specific thing, I just simply miss the costumizable and unique aspect of that part.

My question therefore sounds as following: Is it possible to make all quests start automatically on first join just like the default **break-quest** automatically starts after installing the plugin? If not, maybe you could add an option to the config.yml which automatically starts all quests on first join?

Thank you

**Comment by JCulley** [comment]
Yes you can set any quest to autostart, refer to this page and the “other permissions” section https://github.com/JCulley/ProQuests-Documentation/wiki/Commands-And-Permissions

**Comment by Tyloonie** [comment]
Arh, so all I gotta do is add the **proquests.quest.autostart.{identifier}** to autostart a quest?
Do you know if I can do **proquests.quest.autostart.***?
