### ISSUE TITLE
ProQuests Packages OBTAIN_QUEST

### ISSUE THREAD

**Issue by DatblockGames** [JCulley/ProQuests-Documentation#91]
Version: Paper 1.12.2
Account: https://www.spigotmc.org/members/datblock.20408/

Bug: The internal "OBTAIN_QUEST" type is not working through ProQuests Packages. When player has started the quest, have the required items in inventory, and try to complete the quest, plugin says "quest already active". It works without ProQuests Packages, so I figured something must be wrong with ProQuests Packages. No errors are shown in console, log.

**Comment by JCulley** [comment]
This does not follow the guidelines and is not a bug. Obtain quests do not finish automatically and require the player enter a command once they obtain everything

**Comment by DatblockGames** [comment]
I am aware that obtain quests do not finish automatically. I did not state that you could.

You can finish an obtain quest by clicking the icon in the menu, but this does not work when you make a quest through ProQuests packages. 

How is this not a bug? This is surely not intended behavior as it normally works without having to use a command.

**Comment by JCulley** [comment]
This is why you must completely explain your issue in detail as you never stated you were attempting to complete the quest using a menu item, all you stated was they had all the required items and were attempting to complete the quest.

In addition as I mentioned this does not follow the error guidelines so you can reopen a new issue following the proper guidelines in place.

Thanks.
