### ISSUE TITLE
[ERROR] ProQuests "PLACEHOLDER_QUEST" NullPointerException

### ISSUE THREAD

**Issue by yeshangyo** [JCulley/ProQuests-Documentation#93]
Spigot account: https://www.spigotmc.org/members/dr-jin.53931/
Spigot version: git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2)
ProQuests  version: 2.0.3.5
Server Lag: https://paste.ubuntu.com/p/kg2kRh4sf9/
Quest config: https://paste.ubuntu.com/p/cs8r46cz9S/
Server load plugins: 
- EasySetSpawn-2.0.jar
- LuckPerms-Bukkit-4.0.80.jar
- PlaceholderAPI-2.8.5.jar
- ProQuests.jar

**Comment by JCulley** [comment]
Use the latest update, thanks for reporting. https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=217960
