### ISSUE TITLE
i cannot reset a quests

### ISSUE THREAD

**Issue by minepaoz** [JCulley/ProQuests-Documentation#94]
when i write /quest reset all
they send 4 dight code to console
Example 
[ Proquests ] /quest reset 7421
and i writed
quest reset 7421 in console
but notification said [ ProQuests] The command you specified is invalid, use /quests help
how can i reset all of my quest
please solve my problem.

**Comment by JCulley** [comment]
Doesn’t follow any guidelines.

**Comment by minepaoz** [comment]
i followed a guideline but i cannot reset because... what?
if you want to look my video problem i can send it to you

**Comment by minepaoz** [comment]
https://cdn.discordapp.com/attachments/291207941326110720/428930374740213761/unknown.png
please look at my picture.

**Comment by JCulley** [comment]
https://github.com/JCulley/ProQuests-Documentation/wiki/Error-Guidelines
