### ISSUE TITLE
Obtain quest (Attempt #5342)

### ISSUE THREAD

**Issue by DatblockGames** [JCulley/ProQuests-Documentation#95]
Hello there, this is attempt #5342 of trying to get support.

**You MUST provide a link to your Spigot account**
- https://www.spigotmc.org/members/datblock.20408/

**You MUST be using the latest plugin version.**
- I am using the latest version of the plugins "ProQuests" and "ProQuests Packages" by the author "JC_Plays_MC".

**You MUST include your Spigot version (If you're using Spigot alternatives such as PaperSpigot, Sponge etc. you may not receive support depending on the error.)**
- "Paper version git-Paper-1369 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)"

**You MUST include a link to your ENTIRE log from A PLAINTEXT WEBSITE such as pastebin. (Links to download your log WILL NOT be accepted!)**
- https://pastebin.com/DSS0rAKX (I have posted all logs relevant to the two plugins. There are no errors in the log when the bug happens.)

**Please provide as much information as possible relating to your issue, otherwise it makes it difficult as we cannot always recreate errors.**

**The bug**

The internal "OBTAIN_QUEST" type is not working with ProQuests Packages. When player has started the quest, have the required items in inventory, and try to complete the quest by clicking the quest slot in the menu, plugin says "quest already active". It is possible to finish obtain quests this way when not using ProQuests Packages.
 
**The scenario** 

**Without ProQuests Packages**

I use the command '/quests' to open the default menu. In this menu there is an obtain quest to obtain 16 coal. I click the quest to start it and it says I started the quest. I then get 16 coal in my inventory and use the command '/quests' to open the menu again. I click the quest to finish the quest and it closes the menu and says I finished the quest. **Successful.**

**With ProQuests Packages**

I use the command '/quests' to open the default menu. In this menu I have a slot linked to a quest package. The current quest displayed is an obtain quest to obtain 16 coal. I click the quest to start and it says I started the quest. I then get 16 coal in my inventory and use the command '/quests' to open the menu again. I click the quest to finish the quest but it says I already started the quest. I am not able to finish the quest. **Unsuccessful.**

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-packages-add-on.31470/update?update=223521
