### ISSUE TITLE
ProQuests: Problem about /quest reset all on Console

### ISSUE THREAD

**Issue by minepaoz** [JCulley/ProQuests-Documentation#96]
Spigot Link: https://www.spigotmc.org/members/minepaoz.78763/
ProQuests Version: 2.0.3.6 
Spigot version: TacoSpigot-1.8.8-latest
Java version: java runtime environment 8 (64-bit)
i just tried to reset all of my quest but notification said : 
[ ProQuests] The command you specified invalid, use /quests help
please look at my picture
i'm not good English at all
![unknown](https://user-images.githubusercontent.com/24626435/38112800-3e98b92a-33cd-11e8-8612-a997dd3c3083.png)

**Comment by JCulley** [comment]
Please provide your entire server log.

**Comment by minepaoz** [comment]
https://pastebin.com/crtZpEaM

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-give-players-objectives.18249/update?update=223522
