### ISSUE TITLE
PLACEHOLDER_QUEST Abnormal cancellation of QUEST

### ISSUE THREAD

**Issue by yeshangyo** [JCulley/ProQuests-Documentation#98]
Spigot account: https://www.spigotmc.org/members/dr-jin.53931/
Spigot version: git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2)
ProQuests version: 2.0.3.6
PlaceholderAPI version: 2.8.2
Server Log: https://paste.ubuntu.com/p/5gF24W8xzW/

I found that canceling the quest will make the quest complete.

Can you follow the steps below to test
1.create a new test quest config: https://paste.ubuntu.com/p/6W4WgtwXTP/
2.use command: /quest start test
3.use command: /quest cancel test
4.Check the chat output
I found that canceling the quest will make the quest complete.

In addition, Also I found using: start_values: true
Will find the quest progress is not normal
Even if my PLACEHOLDER doesn't add value, it will make progress

**Comment by JCulley** [comment]
I’ll be honest I don’t understand what the issue is from your description. I understand there is a language barrier however if I am unable to interpret the issue it’s impossible for me to resolve it. Please provide a better description of the issue.

**Comment by yeshangyo** [comment]
Can you follow my steps for testing?
1. create a new qurst test config
`type: PLACEHOLDER_QUEST
team: SOLO
duration: 0
repeat_delay: 0
repeatable: true
cancelable: true
command_start: true
command_join: false
check_all: false
cancel_after_timer: false
editable: false
disabled: false
join_active: false
require_invite: false
author: 509eca53-c12e-4bbe-b510-89030234a5c8
cancel_actions:
- '[Message] cancel_actions'
complete_actions:
- '[Message] complete_actions'
start_values: false
required_placeholders:
- '%player_level%;999.0'
required_quests: []
blacklisted_quests: []
allowed_worlds: []
blacklisted_worlds: []
allowed_regions: []
blacklisted_regions: []
complete_permissions: []
start_actions: []
progress_actions: []
return_actions: []
invite_actions: []
kick_actions: []`
2. use command: /quest start test
3. use command: /quest cancel test
4. Check the chat output

**Comment by yeshangyo** [comment]
updated issue description

**Comment by yeshangyo** [comment]
Do you understand my error report?

**Comment by JCulley** [comment]
After reviewing the cancel command module specifically I confirmed that while cancelling a quest using the command it will never result in the complete actions being executed.
