### ISSUE TITLE
PLACEHOLDER_QUEST Abnormal cancellation of QUEST

### ISSUE THREAD

**Issue by yeshangyo** [JCulley/ProQuests-Documentation#99]
Spigot account: https://www.spigotmc.org/members/dr-jin.53931/
Spigot version: git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2)
ProQuests version: 2.0.3.6
PlaceholderAPI version: 2.8.2
Server Log: https://paste.ubuntu.com/p/5gF24W8xzW/

I found that canceling the quest will make the quest complete.

Can you follow the steps below to test
1.create a new test quest config: https://paste.ubuntu.com/p/6W4WgtwXTP/
2.use command: /quest start test
3.use command: /quest cancel test
4.Check the chat output
I found that canceling the quest will make the quest complete.

In addition, Also I found using: start_values: true
Will find the quest progress is not normal
Even if my PLACEHOLDER doesn't add value, it will make progress

Do you understand my error report?

**Comment by JCulley** [comment]
Do not repost the exact same issue multiple times.
